### ISSUE TITLE
Use nan to be compatible with newer Node.js versions.

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#1]
I need to use [nan](https://github.com/rvagg/nan) to make RobotJS compatible with newer versions of node.js.

**Comment by anand-seeenivasagam** [comment]
@octalmage, robotjs is awesome. I wanted to use this with latest node.js. When will this be ready? 
Thanks.

**Comment by octalmage** [comment]
I'm glad you like RobotJS! Unfortunately I'm not sure when it will be ready. It was harder than I originally thought and I need time to work on it.

**Comment by anand-seeenivasagam** [comment]
I am also trying to modify RobotJS using nan and it is harder than I imagined. Thanks for your response. :+1:

**Comment by octalmage** [comment]
No problem! I started the work here: 

https://github.com/octalmage/robotjs/tree/nan

I'll take a look now, see if I can make some progress.

**Comment by octalmage** [comment]
Actually got it working and converted a function: 

87fe58e29557b4af172fd6a2324be03f91c1a25a

I'll finish the rest later, should be much longer.

**Comment by anand-seeenivasagam** [comment]
Hey thanks, the node module got build successfully for the function mouseClick but when I tested that function it showed this error
    
    dyld: lazy symbol binding failed: Symbol not found: _clickMouse
    Referenced from: /Users/anand/git/robotjs/build/Release/robotjs.node
    Expected in: dynamic lookup

    dyld: Symbol not found: _clickMouse
    Referenced from: /Users/anand/git/robotjs/build/Release/robotjs.node
    Expected in: dynamic lookup

    Trace/BPT trap: 5

**Comment by octalmage** [comment]
Awesome! All of it compiled? Or just that function? and what version of Node.js? 

Thanks!

**Comment by anand-seeenivasagam** [comment]
At first I just compiled  that function then I made some changes to other functions by forking the project 09b115ec22351bf719be8601258952aa763e1419. And all of it is compiled in the node version 0.11.13 and woking.

**Comment by octalmage** [comment]
I saw that, thanks a ton man!

**Comment by octalmage** [comment]
@anand-seeenivasagam since your repository now contains code that is not cross platform it can't be merged. I finished the conversion myself.

**Comment by anand-seeenivasagam** [comment]
Thats allright! I will try to make the changes cross platform because we need it in future. Thanks! :)

**Comment by octalmage** [comment]
Awesome! Thanks again for your help!
