### ISSUE TITLE
Capture input actions (key and mouse)

### ISSUE THREAD

**Issue by willwade** [octalmage/robotjs#103]
Is there any plans to develop a hook system so we can map one keypress to another? (this may be useful.. http://stackoverflow.com/questions/5006821/nodejs-how-to-read-keystrokes-from-stdin )

**Comment by octalmage** [comment]
Not at the moment, not in RobotJS at least. I use nw.js or electron for my hotkey needs. I'm considering writing a separate library though, see #55.
