### ISSUE TITLE
robotjs fails on Trisquel

### ISSUE THREAD

**Issue by insanity54** [octalmage/robotjs#107]
os: Trisquel GNU/Linux 7.0, Belenos
node version: v4.1.1
robotjs version: 0.3.1

Problem: I get an error when requiring robotjs.

Here's `test.js`

```
var robot = require('robotjs');
```

When running `node test.js`-

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: /home/rabbit/scripts/mc-screenshot-twitter/node_modules/robotjs/build/Release/robotjs.node: undefined symbol: _ZN2v86Object3NewEv
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/rabbit/scripts/mc-screenshot-twitter/node_modules/robotjs/index.js:1:80)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Am I doing something wrong?

**Comment by octalmage** [comment]
Hi @insanity54! 

Do you have the requirements for Linux installed? Specifically the `libxtst-dev` and `libpng++-dev` packages. See: https://github.com/octalmage/robotjs#installation

**Comment by insanity54** [comment]
yessir I have both of those installed.

I just noticed that using node v0.10.40, there is no error and test.js runs without errors. Also I tested the first example in README.md with the mouse sine wave movement against both node versions v0.10.40 and v4.1.1.

4.1.1 results in the `undefined symbol: _ZN2v86Object3NewEv` error, while 0.10.40 does not.

**Comment by insanity54** [comment]
Hmm, actually I'd like to look into this a little more. I'd like to get robotjs running with a more recent version of node. What's _ZN2v86Object3NewEv? Got any clues? I'll do some digging.

**Comment by octalmage** [comment]
I'm pretty sure it's the compiled version of a nan function.

**Comment by octalmage** [comment]
I'm guessing that nan hasn't be updated to support 4.1.1 yet, maybe use 4.0.x for now?

**Comment by octalmage** [comment]
Actually what version of nan do you have installed? Try 2.1.0! I'll try to test some things later today.

**Comment by insanity54** [comment]
Oh gotcha, http://npmjs.org/package/nan.

I'm running nan 2.1.0 since that's what robotjs v0.3.1 pulled in. In robotjs's package.json the nan dependency version is, "^2.0.9" so I thought to try exactly 2.0.9 and edited robotjs's package.json to depend on nan, "2.0.9".

Installing nan 2.0.9 got robotjs up and running with node 4.1.1. I wanted to verify this by reproducing the original problem, so I uninstalled nan and robotjs and installed again. robotjs pulled in nan 2.1.0 again, but for some reason I can't reproduce! Perhaps my test environment was tainted when nan 2.0.9 compiled?

**Comment by insanity54** [comment]
Anyway, I have something that works so I'm happy. Thanks for your help, octalmage

**Comment by octalmage** [comment]
It seemed like maybe nan wasn't completely installed, since a function defined in the library was missing. Very strange! Please let me know if you encounter this again.
