### ISSUE TITLE
The typeString function doesn't work for special characters selected with the SHIFT key under Windows

### ISSUE THREAD

**Issue by ashleydavis** [octalmage/robotjs#108]
The typeString() function can't handle special characters that were selected via the SHIFT keys.

It works OK for alphabetical characters both upper and lower case.

Example:

```
var robot = require('robotjs');

setTimeout(
	function () {
		robot.typeString(":::::::::::::::::");
	}, 
	5000
);
```

Output
```
;;;;;;;;;;;;;;;;;
```

The timeout gives you 5 seconds in which to select a text box. This will then insert semicolons into the focused text box.

After investigating this further it appears that any special character that is selected with the SHIFT key is passed through as if SHIFT was not pressed.

Another example:
```
robot.typeString("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
```

Output:
```
1111111111111111111111111111111
```

I'm going to attempt to fix this, but if anyone can give me any idea why this might happen please let me know.

**Comment by ashleydavis** [comment]
I've traced this problem to the function `MMKeyCode keyCodeForChar(const char c)`. It calls VkKeyScan which converts a character to a key code. The returned key code contains the modifiers (eg SHIFT in my case) but the modifiers are ignored because they are not processed into the (presumably cross-platform) format that Robotjs expects.

**Comment by ashleydavis** [comment]
I've submitted a pull request #110 to fix this issue.

**Comment by octalmage** [comment]
This has finally been merged! Thanks again @ashleydavis!!

**Comment by octalmage** [comment]
This made it into v0.3.4, and it seems to be working great!
