### ISSUE TITLE
Get RobotJS working with nw.js 0.11.*

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#11]
Currently it's only working with nw.js 0.10.*.

**Comment by gasolin** [comment]
confirm robotjs works with nw.js 0.12.1, need install robotjs via io.js 1.2.0 (the correspondent version within nw.js, can use nvm to switch node/iojs versions)

read https://github.com/gasolin/webbymouse#build-for-desktop

**Comment by octalmage** [comment]
Yeah this was resolved at some point! Thanks!
