### ISSUE TITLE
Failed to install on Windows 7. Failed to locate "CL.exe"

### ISSUE THREAD

**Issue by happilymarrieddad** [octalmage/robotjs#111]
Hi, I installed visual studio 2015, the sdk and python but it says I'm missing the path to the WindowsSDKDir... which is weird because I installed the SDK from the wiki page. Do I need to add something to the windows environmental path or something? Thanks!
![capture](https://cloud.githubusercontent.com/assets/6416323/10698872/6e65d170-7970-11e5-9067-ebd0188eea5a.PNG)

**Comment by octalmage** [comment]
Run one of the following commands depending on your architecture:

```
call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x86
call "C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\Setenv.cmd" /Release /x64
```

The node-gyp readme has some other tips, but I believe the above should resolve this. 

https://github.com/nodejs/node-gyp#installation

Let me know if this helps!

**Comment by octalmage** [comment]
I'm going to close this issue, if you're still having problems please let me know!

**Comment by happilymarrieddad** [comment]
It works man. Thanks!
