### ISSUE TITLE
failed to build on raspberry pi

### ISSUE THREAD

**Issue by maxogden** [octalmage/robotjs#112]
heres the build log: http://pastebin.com/B9mXbH6j

**Comment by octalmage** [comment]
Looks like this is the issue: 

```
../node_modules/nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```

Can you update the compiler?

**Comment by maxogden** [comment]
Ah good catch. I'll give it a shot.

**Comment by octalmage** [comment]
Awesome let me know! I know for TravisCI I needed g++-4.8 and gcc-4.8, then I needed to set the `CXX` environment variable to `g++-4.8`, so maybe try that.

**Comment by octalmage** [comment]
I'm going to close this, feel free to reopen it if this is still an issue!
