### ISSUE TITLE
Use SendInput instead of mouse_event.

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#115]
[mouse_event](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646260(v=vs.85).aspx) is deprecated, so [SendInput](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646310(v=vs.85).aspx) should be used instead! 

#77 is related.
cc: @Deltatiger

**Comment by Deltatiger** [comment]
I will get started on converting everything to sendinput and start testing stuff out.

**Comment by Deltatiger** [comment]
Can SendInput be used instead of keybd_event. I think all the features we have so far can be ported onto SendInput. 
I was pretty much stuck with college work for the past 2 months so I couldn't push anything. Will get back to fixing this ASAP.

**Comment by octalmage** [comment]
No worries! I haven't touched this in around 2 months either, so I understand!

**Comment by octalmage** [comment]
This was resolved by #181. Thanks again @Deltatiger!
