### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by Qix-** [octalmage/robotjs#116]
```
$ npm --version
3.3.6
$ node --version
v4.1.1
$ node-gyp --version
v3.0.3
$ npm i robotjs
> robotjs@0.3.1 install /src/snip/node_modules/robotjs
> node-gyp rebuild

  CXX(target) Release/obj.target/robotjs/src/robotjs.o
../src/robotjs.cc:2:10: fatal error: 'nan.h' file not found
#include <nan.h>
         ^
1 error generated.
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
```

I even tried `npm i nan` on its own to no avail. Running on El Capitan.

**Comment by octalmage** [comment]
Does the nan directory exist in the robotjs node_modules directory?

**Comment by Qix-** [comment]
No, it wouldn't; NPM@3 onward has flat module systems. That could be it. I'm not able to confirm since the build fails, thus robotjs doesn't appear in node_modules to begin with.

**Comment by RainmanNoodles** [comment]
FWIW, I'm also seeing the same issue, so it's not an isolated thing. (node 4.2.1/node-gyp 3.0.3/npm 3.3.9)

**Comment by octalmage** [comment]
Alright, I know what needs to be done. I'll submit a PR.

**Comment by octalmage** [comment]
#117 should resolve this,  could you try building RobotJS from the [dynamic-nan-include](https://github.com/octalmage/robotjs/tree/dynamic-nan-include) branch? 

Thanks!

**Comment by RainmanNoodles** [comment]
Using `npm install git://github.com/octalmage/robotjs#dynamic-nan-include` gives me this error:

      CXX(target) Release/obj.target/robotjs/src/robotjs.o
    ../src/robotjs.cc:76:16: error: cannot initialize a variable of type 'MMMouseButton' (aka 'CGMouseButton') with an rvalue of type '_MMMouseButton'
            MMMouseButton button = LEFT_BUTTON;
                          ^        ~~~~~~~~~~~
    ../src/robotjs.cc:129:16: error: cannot initialize a variable of type 'MMMouseButton' (aka 'CGMouseButton') with an rvalue of type '_MMMouseButton'
            MMMouseButton button = LEFT_BUTTON;
                          ^        ~~~~~~~~~~~
    ../src/robotjs.cc:397:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
            *flags = MOD_ALT;
                   ^ ~~~~~~~
    ../src/robotjs.cc:401:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
            *flags = MOD_META;
                   ^ ~~~~~~~~
    ../src/robotjs.cc:405:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
            *flags = MOD_CONTROL;
                   ^ ~~~~~~~~~~~
    ../src/robotjs.cc:409:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
            *flags = MOD_SHIFT;
                   ^ ~~~~~~~~~
    ../src/robotjs.cc:413:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
            *flags = MOD_NONE;
                   ^ ~~~~~~~~
    ../src/robotjs.cc:425:13: error: cannot initialize a variable of type 'MMKeyFlags' (aka 'CGEventFlags') with an rvalue of type '_MMKeyFlags'
            MMKeyFlags flags = MOD_NONE;
                       ^       ~~~~~~~~
    ../src/robotjs.cc:479:13: error: cannot initialize a variable of type 'MMKeyFlags' (aka 'CGEventFlags') with an rvalue of type '_MMKeyFlags'
            MMKeyFlags flags = MOD_NONE;
                       ^       ~~~~~~~~

I saw this error before when I was running npm 2.x but I upgraded to 3.x and it changed to the `nan.h` error...

**Comment by Qix-** [comment]
Same thing here.

```
$ npm i https://github.com/octalmage/robotjs.git\#dynamic-nan-include

> robotjs@0.3.1 install /src/snip/node_modules/robotjs
> node-gyp rebuild

  CXX(target) Release/obj.target/robotjs/src/robotjs.o
../src/robotjs.cc:76:16: error: cannot initialize a variable of type 'MMMouseButton' (aka 'CGMouseButton') with an rvalue of type '_MMMouseButton'
        MMMouseButton button = LEFT_BUTTON;
                      ^        ~~~~~~~~~~~
../src/robotjs.cc:129:16: error: cannot initialize a variable of type 'MMMouseButton' (aka 'CGMouseButton') with an rvalue of type '_MMMouseButton'
        MMMouseButton button = LEFT_BUTTON;
                      ^        ~~~~~~~~~~~
../src/robotjs.cc:397:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
        *flags = MOD_ALT;
               ^ ~~~~~~~
../src/robotjs.cc:401:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
        *flags = MOD_META;
               ^ ~~~~~~~~
../src/robotjs.cc:405:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
        *flags = MOD_CONTROL;
               ^ ~~~~~~~~~~~
../src/robotjs.cc:409:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
        *flags = MOD_SHIFT;
               ^ ~~~~~~~~~
../src/robotjs.cc:413:13: error: assigning to 'MMKeyFlags' (aka 'CGEventFlags') from incompatible type '_MMKeyFlags'
        *flags = MOD_NONE;
               ^ ~~~~~~~~
../src/robotjs.cc:425:13: error: cannot initialize a variable of type 'MMKeyFlags' (aka 'CGEventFlags') with an rvalue of type '_MMKeyFlags'
        MMKeyFlags flags = MOD_NONE;
                   ^       ~~~~~~~~
../src/robotjs.cc:479:13: error: cannot initialize a variable of type 'MMKeyFlags' (aka 'CGEventFlags') with an rvalue of type '_MMKeyFlags'
        MMKeyFlags flags = MOD_NONE;
                   ^       ~~~~~~~~
9 errors generated.
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /src/snip/node_modules/robotjs
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "https://github.com/octalmage/robotjs.git#dynamic-nan-include"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! robotjs@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/snip/npm-debug.log
```

**Comment by octalmage** [comment]
Hmm, must be an El Capitan thing. It builds for Node v4.2.1 without issue. I'll have to find a way to test and work on this, it may be a couple of days. Sorry!

**Comment by jazzzz** [comment]
> #117 should resolve this, could you try building RobotJS from the dynamic-nan-include branch?

I had the same build error on Windows 10, it is fixed with the dynamic-nan-include branch!

**Comment by octalmage** [comment]
Awesome! I'll get it pushed out today with #114.

**Comment by octalmage** [comment]
I'm so curious what has changed here. Is it the compiler? I feel like it has to be. What version of Xcode are y'all running?

**Comment by octalmage** [comment]
It has to be gcc/g++, here's what I have: 

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

What versions do y'all have?

**Comment by SimulatedGREG** [comment]
El Capitan 10.11.1 & Xcode 7.1 (7B91b)
```xcode-select -v``` gives me version 2343, if that makes any difference

**Comment by octalmage** [comment]
@SimulatedGREG Could you check your gcc/g++ version? 

Thanks a ton!

**Comment by SimulatedGREG** [comment]
This?
```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by octalmage** [comment]
Yes thanks! And could you run `g++ -v`?

**Comment by SimulatedGREG** [comment]
Looks the same...
```
$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by octalmage** [comment]
Hmm, I thought I was on to something. I'll set up an El Capitan VM now.

**Comment by Qix-** [comment]
Hmm, first thought is that you shouldn't be relying upon GNU's compilers on OSX, because they're usually mapped to clang which can have different semantics. Should be looking at clang/clang++.

That being said:

```
$ clang -v
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by octalmage** [comment]
Yeah I'm having a hard time imaging exactly what has changed. I don't want to update my main OS and not be able to work on RobotJS, so I'm trying to get a VM going.

**Comment by octalmage** [comment]
And why does Node.js v0.12.7 build? Does node-gyp use different build tools here? I'm looking into this now.

**Comment by SimulatedGREG** [comment]
That was my main question, how in the world does v0.12.7 work.

```
Now using system version of node: v0.12.7 (npm v2.11.3)
...
 $ npm install robotjs
-
> robotjs@0.3.1 install /Users/gregholguin/Documents/Projects/Personal/twitch-plays-undertale/node_modules/robotjs
> node-gyp rebuild

  CXX(target) Release/obj.target/robotjs/src/robotjs.o
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  SOLINK_MODULE(target) Release/robotjs.node
robotjs@0.3.1 node_modules/robotjs
└── nan@2.1.0
```

**Comment by Qix-** [comment]
This is why I suspect it's a Nan issue.

**Comment by octalmage** [comment]
Since the original issue has been resolved, I created #118 to address the El Capitan issue. 

Thanks for the help guys!

**Comment by octalmage** [comment]
v0.3.2 published to npm which fixes this issue.

**Comment by prateekbh** [comment]
same problem is happening on mac os 11.4 node 15.x
