### ISSUE TITLE
Failed to install on Windows 7. Загрузка компонента Visual C++ "VCBuild.exe"  невозможна.

### ISSUE THREAD

**Issue by joker1t** [octalmage/robotjs#121]
![untitled-2](https://cloud.githubusercontent.com/assets/11577819/10814170/813f3cd8-7e3d-11e5-9557-c5824b61a510.jpg)

**Comment by joker1t** [comment]
Solution is to set Path Environment C:\Program Files (x86)\Microsoft Visual Studio 8\VC\vcpackages

**Comment by joker1t** [comment]
So, next problem is..

![image](https://cloud.githubusercontent.com/assets/11577819/10819897/1659364a-7e64-11e5-8f42-619caa0e8e1a.png)

**Comment by octalmage** [comment]
What version of Visual Studio do you have installed? Please try these instructions: 

https://github.com/nodejs/node-gyp#installation

Thanks!

**Comment by octalmage** [comment]
I'm going to close this, if you're still having issues please let me know!
