### ISSUE TITLE
selecting text with mouse commands

### ISSUE THREAD

**Issue by maxogden** [octalmage/robotjs#127]
I have some code like this:

```js
    robot.mouseToggle("down")
    robot.moveMouse(data.x, data.y)
    robot.mouseToggle("up")
```

I was hoping this would have the effect of selecting text, but I can't get the text to get highlighted Any ideas?

**Comment by octalmage** [comment]
Mouse events are really weird on Mac. I bet we'll have to specify that the mouse is down for the mouse move or something weird like that. I'll look into it this week!

**Comment by noonat** [comment]
Looked into this a little bit, and it seems like you need to pass one of the drag event types (kCGEventLeftMouseDragged, kCGEventRightMouseDragged, kCGEventOtherMouseDragged) to get this to do a selection. It seems like the mouse button *also* needs to be marked as down, neither is sufficient on its own.

**Comment by maxogden** [comment]
@noonat nice work.

So it sounds like maybe we'll need a `drag: true` option to `mouseToogle`?

**Comment by octalmage** [comment]
For sure! Either that or a separate mouse drag function.

**Comment by noonat** [comment]
I have a branch with a separate `dragMouse(x, y, button)` function, where button is optional and defaults to left. It seems to be working as expected.

@octalmage How would you like to handle testing for something like that?

**Comment by octalmage** [comment]
@noonat I currently don't have a way to test events like that, so don't worry about it for now. Create a pull request and I'll test it on all OSes manually. 

I created something that works locally, but it doesn't work on TravisCI: 

https://github.com/octalmage/robotjs/tree/keyboard-tests

See #98.

**Comment by noonat** [comment]
Opened #133 for this.
