### ISSUE TITLE
Issue with electron global shortcuts and typeString

### ISSUE THREAD

**Issue by raine** [octalmage/robotjs#128]
```js
var app = require('app');
var shortcut = require('global-shortcut');
var robot = require('robotjs')

app.on('ready', function() {
  shortcut.register('ctrl+x', function() {
    robot.typeString('test')
  });
});

app.on('will-quit', function() {
  shortcut.unregister('ctrl+x');
});
```

1. Go to empty Chrome address bar
2. Hit <kbd>ctrl-x</kbd>

Nothing happens.

But if you add a `keyTap` before the `typeString` in the shortcut handler, like so:

```js
robot.keyTap('f')
robot.typeString('test')
```

then, `ftest` will be entered when pressing the shortcut.

**Comment by raine** [comment]
The issue seems to be that <kbd>ctrl</kbd> is still held down when `typeString('test')` is called, so entered text is interpreted as <kbd>ctrl+t</kbd> etc. There would probably have to be some way to trigger it only after modifiers are released.

**Comment by octalmage** [comment]
Thanks for the info @raine!
