### ISSUE TITLE
keyToggle doesn't work

### ISSUE THREAD

**Issue by DaAwesomeP** [octalmage/robotjs#132]
The `keyToggle` method seems to act more like `keyTap`. It doesn't hold the key down for very long at all and definitely not until it is passed again with `up`.

NodeJS v4.2.1
Windows 8.1 Pro x64

**Comment by DaAwesomeP** [comment]
@octalmage can you confirm this issue? I haven't had a chance to test with other NodeJS versions or operating systems.

**Comment by octalmage** [comment]
This isn't an issue on Mac, I can test on Windows in a bit.

**Comment by octalmage** [comment]
Do you have example code to replicate the issue @DaAwesomeP?

**Comment by Deltatiger** [comment]
@DaAwesomeP  @octalmage  I can test it on windows. Example code and expected output will make all such testing easier.

**Comment by octalmage** [comment]
@Deltatiger awesome! I believe I used this app in the past to confirm key strokes:

http://aalapshah.in/qipress/

**Comment by DaAwesomeP** [comment]
@octalmage @Deltatiger I was only testing it with the space key. I am yet to publish [this](https://github.com/DaAwesomeP/firmata-hid) repo to NPM (I don't even have a README yet). Basically the [`index.js` file in `lib/`](https://github.com/DaAwesomeP/firmata-hid/blob/master/lib/index.js#L80-L84) includes the [`firmata.js` file](https://github.com/DaAwesomeP/firmata-hid/blob/master/lib/firmata.js#L21) and passes the two keyboard functions that I need to it (`keyTap` and `keyToggle`).

When it is in `continuous` mode, it will use `keyToggle`. See lines [64](https://github.com/DaAwesomeP/firmata-hid/blob/master/lib/firmata.js#L64), [68](https://github.com/DaAwesomeP/firmata-hid/blob/master/lib/firmata.js#L68), [105](https://github.com/DaAwesomeP/firmata-hid/blob/master/lib/firmata.js#105), and [109](https://github.com/DaAwesomeP/firmata-hid/blob/master/lib/firmata.js#L109).

I had to make a `continuousHack` mode as a workaround that is simply `keyTap` in a while loop. Ignore that.

**Comment by DaAwesomeP** [comment]
If you want to test it fully as the library is intended, fire up an Arduino programmed with Firmata and a button on a digital pin. Then edit the example config file to `continuous` mode.

**Comment by DaAwesomeP** [comment]
I apologize for the lack of code comments and general mess of code that it is, but I did it very hurriedly yesterday.

**Comment by Deltatiger** [comment]
@octalmage  @DaAwesomeP  I gave it a quick test. I found some doubts with what do you mean by being held down. 
Actual Keyboard behavior implies that when I press and hold a key, that key gets typed as many times as possible.
RobotJS keyToggle does work on keys like shift. I tried the following code.
```javascript
robotjs.keyToggle('shift', 'down');
robotjs.keyTap('a');
robotjs.keyToggle('shift', 'up');
robotjs.keyTap('a');
```
And i got the expected result of ```Aa```.
This just leads me to question how the actual key down and key up modifiers work. I will look into this today and see what I can find.
As far as I can tell this may not be a bug.

**Comment by DaAwesomeP** [comment]
@Deltatiger I see. They're simply modifiers and not physical presses. I think that you should add this note to the API section.

Maybe there should be another function that does rapid presses. I did this in my code using a simply while loop:
```javascript
var shouldBeHeldDown = true; // Key will be pressed infinitely so long as this variable is true

async.whilst(function () {
  if (shouldBeHeldDown) { return true; }
  else { return false; }
},
function (callback) {
  robot.keyTap('a');
  callback();
},
function (err) {
  // There's no point of a callback here, so this can be blank
});
```

**Comment by octalmage** [comment]
If I remember correctly holding a key down with code doesn't cause multiple presses on Windows, this only happenes when you press a physical key.

**Comment by DaAwesomeP** [comment]
@octalmage Well, it worked for me! In my original code I did [have a delay/debounce](https://github.com/DaAwesomeP/firmata-hid/blob/master/lib/firmata.js#L78) to make it go a little slower, but it worked well enough.

**Comment by Deltatiger** [comment]
@DaAwesomeP  It will be better if such functionality be implemented by the developer using the library.  If you want the multiple key presses then some other functionality of KeyToggle may break ( like those for the modifiers ).
@octalmage  As suggested by @DaAwesomeP I think a note should be added to the API mentioning the working of the KeyToggle API.

**Comment by DaAwesomeP** [comment]
Since this isn't really a bug, I'll close this.
