### ISSUE TITLE
ETA for Screenshot / getPixel(s) ?

### ISSUE THREAD

**Issue by schoening** [octalmage/robotjs#138]
I was taken a look at the src files and they do seem pretty straight forward. Kudos to the writers! Unfortunately I don't know any C or C++, really frustrating to sort of understand the code but being unable to contribute :P

Any idea when there will be a function that returns a bitmap or something like a typed array that can be manipulated in JavaScript?

Not talking about the fancy stuff, like finding images on the screen, just the basic screenshot.

---------------------

Just for fun I tried making a little function that creates a typed array that can be used for an image with the current version.
It took almost 14 minutes to create a picture of my 1366 x 768 screen :D

```javascript
robot = require("robotjs");



var WIDTH = robot.getScreenSize().width;
var HEIGHT = robot.getScreenSize().height;

console.time("perf");
create_Screen_Shot(WIDTH, HEIGHT);

console.timeEnd("perf");



function create_Screen_Shot ( width, height ) {

	var buffer = new Uint8ClampedArray(width * height * 4);

	console.log( width, height );

	var hex = "";
	var rgb = "";

	for ( var i = 0, il = width; i < il; i += 1 ) {
		for ( var j = 0, jl = height; j < jl; j += 1 ) {

			hex = robot.getPixelColor( i, j );
			rgb = hexToRgb(hex);

			position = (i * width + j) * 4;

			buffer[ position ]     = rgb.r;
      buffer[ position + 1 ] = rgb.g;
      buffer[ position + 2 ] = rgb.b;
      buffer[ position + 3 ] = 255;

		}
	}

};

// http://stackoverflow.com/a/5624139/1502407
function hexToRgb(hex) {
    var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16)
    } : null;
}
```

**Comment by schoening** [comment]
Duplcate. trying to delete this one.

**Comment by octalmage** [comment]
There isn't a way to delete issues, so closing it is fine!

**Comment by octalmage** [comment]
You can preview and use the screen capture code on Mac, I'm struggling to get it to work on Windows though. 

http://blog.robotjs.io/post/130642552013/i-spent-a-few-hours-yesterday-and-today-working-on

Things have also been really crazy at work, it might be a while till I can finish this unfortunately.

**Comment by schoening** [comment]
No problem mate :)

I am dual booting Linux mint and Windows 10.
Curious why you replied to this post, since its the duplicate of the one where the content is :p 

I got lots of stressful stuff my self at the moment so don't worry, just wanted to check :)

**Comment by octalmage** [comment]
Lol I didn't see your other issue till just now.
