### ISSUE TITLE
F9 apparently F19

### ISSUE THREAD

**Issue by ligustah** [octalmage/robotjs#141]
Hi,

I've been playing around with robotjs a bit and have been impressed by it so far. I'm trying to have it press certain key combinations to manipulate another program that is listening for global hotkeys.

Now I started experimenting with mapping actions to F9 and F10, but couldn't get it to work for whatever reasons, so I installed a program that would display keys pressed on screen ( http://superuser.com/questions/104421/windows-utility-to-render-which-key-i-am-pressing-on-screen ). While all F keys seem to work normally, F9 seems to trigger F19 on my Windows 10 system. I haven't had a chance to look at the code just yet, but maybe someone knows the problem or could try to reproduce it.

The F-keys seem to be acting awkward in general, though I'm going to investigate further on that one and will open separate issues if I find anything specific.

Thanks for the great library :+1:

**Comment by ligustah** [comment]
See #142

**Comment by octalmage** [comment]
Fix published to npm in RobotJS v0.3.7.

**Comment by ligustah** [comment]
Awesome, thanks!

I'll probably get some time during the next days to find out more about the other issue.

**Comment by octalmage** [comment]
Cool sounds good!
