### ISSUE TITLE
Check if target window is active?

### ISSUE THREAD

**Issue by zweicoder** [octalmage/robotjs#145]
In AutoHotkey we could check if certain windows or processes are active before activating certain hotkeys. Is it doable with `robotjs`?

**Comment by Deltatiger** [comment]
@zweicoder as of now we do not have such a feature. This is something that has not come up for implementation so I think this may take more time before it is implemented. 
Useful feature though. I should start exploring AHK

**Comment by octalmage** [comment]
I would like to implement window management because it doesn't exist for Node.js. I even started on it in the window branch, but it's currently not a priority. I might look into it after the screen capture code is finished.

**Comment by octalmage** [comment]
@zweicoder I created active-window, which solves this issue: 

https://github.com/octalmage/active-window

I personally didn't end up using it, but others are! Check it out!

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
