### ISSUE TITLE
add a way to specify the X11 display in Linux

### ISSUE THREAD

**Issue by illegalprime** [octalmage/robotjs#153]
When running a process using this as a service I get a segfault from node.js like so:
```
[michael] [test_robotjs] $ node index.js      
Could not open main display
zsh: segmentation fault (core dumped)  node index.js
```

`index.js` is just trying to do anything with `robot.js`:
```javascript
var robotjs = require("robotjs");
robotjs.mouseClick();
```

The workaround is easy (run with `DISPLAY=:0` or similar), but I would rather not have to configure this module through environment variables.

**Comment by octalmage** [comment]
See #34 and let me know if that works for you!

**Comment by illegalprime** [comment]
Will test it out later today, sorry for the delay.

**Comment by octalmage** [comment]
No worries! You're doing me a favor!
