### ISSUE TITLE
keytap does not work on browser

### ISSUE THREAD

**Issue by faytom** [octalmage/robotjs#156]
I try to write a piece of code which shows the key tap in browser, however it always appears in the terminal. Anyone can help me with it? Thx alot.

**Comment by faytom** [comment]
I realized i placed the keyTap function in a serialEvent listener, by calling keyTap within this serialEvent listener it won't execute the code successfully and eventually leads to segmentation fault: 11.

**Comment by octalmage** [comment]
I'm not sure I understand. Could you provide some code where keyTap isn't working? It shouldn't be possible to cause a segmentation fault with keyTap. 

Which OS and Node.js version are you using?

**Comment by octalmage** [comment]
Also I'm not familiar with serialEvent, where does this come from?

Thanks!

**Comment by faytom** [comment]
just realized that i was putting a "1" as the argument for keyTap and it wasn't supported. stupid mistake.
