### ISSUE TITLE
keyToggle not keeping the hold

### ISSUE THREAD

**Issue by nroadley** [octalmage/robotjs#158]
First off, great library! I loved this for JAVA a lot, and you can do some nifty things.

However, I seem to have a bug where the keyToggle doesn't keep the button hold. I used a test similar to this code, where I simply wanted the key to be held down for 5 second. (Would expect the cursor to scroll up the page in my text document.)

```
var robot = require("robotjs");

robot.keyToggle("up","down");
robot.setKeyboardDelay(5000);
robot.keyToggle("up","up");

```

Is it a known issue or me doing something wrong?

**Comment by octalmage** [comment]
Hey @nroadley! 

Try setting the keyboard delay first! The sleep is at the end of the function. In the above code the first keyToggle would sleep for the default 10ms, the up event would fire then it would sleep for 5 second.

**Comment by nroadley** [comment]
Doesn't seem to work either for me. It sends the first press but never holds the input. But the same code works perfectly with the mouse toggle, which is a mystery for me.

**Comment by octalmage** [comment]
Hmm which OS are you using? It's probably holding the key down, but not pressing it repeatedly. Depending on the OS, holding down the key virtually won't scroll like your expecting.

**Comment by nroadley** [comment]
OSX so I was confused with the behaviour from what I was used to in Windows. Sorry!

The input is working as expected inside the software I wanted to use. Thank you.

**Comment by octalmage** [comment]
No worries! I went through the same exact thing before. Let me know if you run into anything else!

**Comment by akanshSirohi** [comment]
Same thing again happening in windows 10, key toggle not keeping hold on key, its just press once and then it automatically release it.
