### ISSUE TITLE
moveMouse / dragMouse in games

### ISSUE THREAD

**Issue by nroadley** [octalmage/robotjs#159]
I ran into an other issue, that again might be OS specific. I am using a Potentiometer that is mapped to my screen width, which I would like to use as a controller for my game. But whenever the mouse input has to be used in a game, it doesn't detect the movement of the cursor.

Button presses works perfectly. And I tried with dragMouse too. 

Anyone got this to work?

**Comment by nroadley** [comment]
I found [this](https://autohotkey.com/board/topic/65492-fps-game-mouse-movement-via-keyboard/l) thread on autohotkey. Do we have the possibility of relative mouse movement etc. too? 

Hope to find a solution to this, as it will be so great for DIY controller projects!

**Comment by octalmage** [comment]
Many games try to prevent automation which is probably what you're running into. This is mainly an issue on Windows. 

Which OS and game are you using?

**Comment by nroadley** [comment]
OS X and have mainly been testing with Portal, Minecraft and some browser game. None seemed to respond, but when you moved the real mouse, it picked up the coordinate to some extend.

I think you are right, but I am not giving up yet :)

**Comment by Kerndog73** [comment]
@nroadley I'm making a controller as well. It would be great to get this to work

**Comment by octalmage** [comment]
@nroadley cool I'll see what I can figure out with Minecraft this weekend. I'm convinced I can get this working, I think it's very important. It just might take me some time.

**Comment by nroadley** [comment]
Sounds great @octalmage . I am also looking into some lower level ways of doing it. Let me know what you find!

**Comment by octalmage** [comment]
I made some progress on this today. You can test the code here: 

https://github.com/octalmage/robotjs/pull/177

I don't think it's perfect, but it's a step in the right direction.

**Comment by zedd3v** [comment]
Will this be pushed to main? I cannot get it to work on windows. my mouse is locked while in game
