### ISSUE TITLE
[multi-monitor] getPixelColor with a negative x or y throws an error

### ISSUE THREAD

**Issue by btjones** [octalmage/robotjs#160]
When `getPixelColor` is called with a negative x or y coordinate an error is thrown. This happen when using multiple monitors and going above or to the left of the main monitor (I've only test on OSX 10.11.2).

This is very similar to https://github.com/octalmage/robotjs/issues/88

```
Process:               Electron [3957]
Path:                  /Users/USER/*/Electron.app/Contents/MacOS/Electron
Identifier:            com.github.electron
Version:               0.36.5 (0.36.5)
Code Type:             X86-64 (Native)
Parent Process:        node [3956]
Responsible:           Terminal [281]
User ID:               501

Date/Time:             2016-02-04 11:02:13.187 -0500
OS Version:            Mac OS X 10.11.2 (15C50)
Report Version:        11
Anonymous UUID:        FDAB5D50-7C11-4DD7-4BA7-5F8B08177F60


Time Awake Since Boot: 5700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 0000000105903000-0000000105904000 [    4K] r-x/rwx SM=COW  /Users/USER/*/Electron.app/Contents/MacOS/Electron

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation        0x00007fff96978329 CFDataGetBytePtr + 25
1   robotjs.node                    0x000000010e6866fd copyMMBitmapFromDisplayInRect + 403 (screengrab.c:61)
2   robotjs.node                    0x000000010e684dc1 getPixelColor(Nan::FunctionCallbackInfo<v8::Value> const&) + 146 (robotjs.cc:605)
3   robotjs.node                    0x000000010e68584a Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) + 131 (nan_callbacks_12_inl.h:175)
…
```

**Comment by Deltatiger** [comment]
@btjones How are your multiple monitors setup ? The Co-ordinate system depends on how your main monitor is setup. The main Monitor's lower left corner is (0, 0) with the X and Y axes increasing to the right and top sides respectively. 

Could you please check this information and post your monitor config ?

**Comment by octalmage** [comment]
I don't think this is going to work until we add direct multi monitor support. Each API probably has a different method of dealing with extra displays.

**Comment by btjones** [comment]
I hook up an external monitor to my laptop and then alter the arrangement in System Preferences > Displays. So it's not always perfectly lined up at the bottom or the top. Sometimes the main display is on the left, sometimes the right, and they could even be on top of each other.

Bottom line, can't depend on all monitors to be aligned at the bottom with the main display on the left. Depending on the setup there could be negative coordinates which I believe it causing this error.

**Comment by octalmage** [comment]
@btjones For sure, we just don't have multi-monitor support yet. It's on the roadmap!

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.

**Comment by panKt** [comment]
Are there any updates on multi-monitor support?

Thanks
