### ISSUE TITLE
Press 3 keys

### ISSUE THREAD

**Issue by iamtekeste** [octalmage/robotjs#164]
Great project!
I am trying to  do `Ctrl` + `Win` + `D` (on Ubuntu this hides all the open windows and shows the desktop).
How might one go about doing that?
Thank you.

**Comment by octalmage** [comment]
Hey @iamtekeste! You can do this with keyTap or keyToggle! It actually accepts a string or array as a modifier, I still need to update the documentation. For example:

    keyTap('D', ['command', 'control']);

Let me know if this works!

**Comment by iamtekeste** [comment]
I just tried it and worked flawlessly! It minimized all the open windows and showed the desktop.
Your rock man! You should definitely mention this on the documentation. I think am gonna release this functionality as a CLI module. 
Why not right?
