### ISSUE TITLE
Mouse move when locked

### ISSUE THREAD

**Issue by Kerndog73** [octalmage/robotjs#165]
mouseMove doesn't work when the mouse is locked. I tried mouseMoveSmooth but that didn't work either.

**Comment by octalmage** [comment]
Hey @Kerndog73! What do you mean by locked?

**Comment by Kerndog73** [comment]
If you open a first person shooter game. The mouse stays in the centre of the screen and is invisible but the moving the mouse changes the view. This state is called "locked".

I'm making a wireless game controller that turns any phone or tablet into a wireless game controller that can be used to control a laptop.

I want to move the mouse while its in this locked state

**Comment by octalmage** [comment]
If you get and print the mouse position, what is it? Does it change or is it fixed?

**Comment by Kerndog73** [comment]
After calling moveMouse the mouse is in a new position but the game doesn't react

**Comment by sushruth** [comment]
Maybe you need the PointerLock API? I think this could be incorporated into RobotJS API. Could help to have this. :+1:  for that feature request

**Comment by octalmage** [comment]
@sushruth I don't think that will help here. The Pointer Lock API is for the browser, RobotJS is on the "server" or desktop. But thanks!

**Comment by octalmage** [comment]
I'm going to close this in favor of #159. I was able to replicate and started to work on this but I don't have a resolution yet. I'll update the other ticket with more information!

**Comment by Venryx** [comment]
> I don't think that will help here. The Pointer Lock API is for the browser, RobotJS is on the "server" or desktop. But thanks!

There is, however, an equivalent for desktop -- at least on Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/ms648383(v=vs.85).aspx
