### ISSUE TITLE
colorAt() Asssertion failed

### ISSUE THREAD

**Issue by Paic** [octalmage/robotjs#166]
Hi!

I was trying the new colorAt() feature, but almost instantly this error message appeared.

![robotjs error](https://cloud.githubusercontent.com/assets/940586/13227460/157e311a-d997-11e5-8569-2f1403bee8aa.png)

Could it be from my Node version or is it a problem in the code ?

**Comment by octalmage** [comment]
Could you shared the code you used? It could be either. Also your Node.js version would be helpful! 

Thanks!

**Comment by octalmage** [comment]
From what I can see, it looks like you tried to get a point in the bitmap that was out of bounds. Are you using a multi-monitor setup?

**Comment by Paic** [comment]
I used a simple function to grab to color where the pointer is :

```
var robot = require('robotjs')

robot.setMouseDelay(1);

setInterval(function() {
	var image = robot.screen.capture();
	var mouse = robot.getMousePos();
	var color = image.colorAt(mouse.x, mouse.y)
	console.log("#" + color + "at x:" + mouse.x + " y:" + mouse.y);
}, 100);
```

I have a multi-monitor setup, with the second one being on the left and (0, 0) is the top left corner of the main one. If I move the mouse on the second one, the error occur (which is normal since there is no multi-monitor support), but it also occur when I move it to the right, so still on the main monitor (when x > ~1050).

I tested it on my laptop (so 1 monitor), and the same append. When x was superior to a certain value, the error occur.

Node version on main computer : 5.6.0 (Windows 7)
Node version on laptop : 5.7.0 (OS X Yosemite)

**Comment by octalmage** [comment]
@Paic I just updated the colorAt code, could you let me know if this helps! I believe it should resolve this issue. 

There was a bug with grabbing the parameters, and the x was being grabbed as the y. So sorry for all of the troubles!

**Comment by Paic** [comment]
I've only tested it on my main computer atm but it works great !
Thanks for the good work !

**Comment by octalmage** [comment]
Awesome! Sorry it took so long to get this resolved. Let me know if you need anything else!
