### ISSUE TITLE
Module Mismatch expected 14 got 46

### ISSUE THREAD

**Issue by happilymarrieddad** [octalmage/robotjs#168]
Hey, I'm using robotjs on a Windows 2008 Server to automate something. It is working on the staging server but when I move it over to the production server I get this error.. I'm pretty sure I did everything else the same... please help!! Thanks!!

node 0.12.7
robotjs

**Comment by octalmage** [comment]
@happilymarrieddad this usually means that you have to recompile RobotJS. You can do this by going into the robotjs directory inside node_modules and running `node-gyp rebuild`. It seems like the staging server and the production server might have different Node.js versions.

**Comment by octalmage** [comment]
@happilymarrieddad were you able to get this resolved?

**Comment by octalmage** [comment]
I'm going to close this, please let me know if you're still having issues.

**Comment by happilymarrieddad** [comment]
This is fixed thanks!
