### ISSUE TITLE
Expose key names to JS

### ISSUE THREAD

**Issue by adjohnson916** [octalmage/robotjs#169]
Are the key names (e.g. "backspace") exposed to JS? It'd be useful.

**Comment by octalmage** [comment]
Yes they are! Check keyTap and keyToggle: 

https://github.com/octalmage/robotjs/wiki/Syntax#keytapkey-modifier

**Comment by adjohnson916** [comment]
@octalmage I'm looking for a actual list or map of the supported key names that can be passed to those functions.

**Comment by octalmage** [comment]
Oh, do you mean a way to pull the list of supported keys using JavaScript?

**Comment by adjohnson916** [comment]
@octalmage Exactly.
