### ISSUE TITLE
Subscribe to mouse events

### ISSUE THREAD

**Issue by Cardinal90** [octalmage/robotjs#172]
Is it possible to add a functionality to subscribe to mousedown/mouseup/mousemove? I want a control in my electron app to work on mousemove while the left button is pressed regardless of cursor position on the screen. While i could repeatedly query cursor position in electron, i still have no way of knowing that mouseup happened outside of my app.

**Comment by octalmage** [comment]
This is something I'd like to do, but it's not currently on our roadmap. There's some discussion about platform hooks here:

https://github.com/octalmage/robotjs/issues/55

**Comment by Cardinal90** [comment]
Just by chance I found these two libraries: https://github.com/kapetan/win-mouse, https://github.com/kapetan/osx-mouse, maybe you will find them interesting. Not for linux though.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
