### ISSUE TITLE
Read and Write to clipboard

### ISSUE THREAD

**Issue by meeple142** [octalmage/robotjs#173]
I like to do text manipulation with AHK. The easiest way to do it is by highlighting text and then running the script that copies the selection, then reads the clipboard then edit the text and then write back to the clipboard then paste the edited text. It is not 100% reliable (there are some timing issues), but it works. 
Also reading text from screen/clipboard could be used to make a decision based on current conditions. 
(ex. get val of text here, if text === 'Mission is Go' Then release the Kraken)

If this could be added to the road map that would be awesome! I know that the clipboard is most likely not easy to get at with cross platform in mind. But who knows maybe there's a python lib out there for that.

What do you all think? Is clipboard access a good idea? Or is there a better more reliable method to edit/analyze typed text.

**Comment by octalmage** [comment]
Both NW.js and Electron provide cross platform access to the clipboard, have you tried them? I've used their clipboard functionality a few times and it works well.

**Comment by meeple142** [comment]
I have used nwjs but didnt realize that it can do clipboard functions. If the functionality is out there then no reason to reinvent it! Thank you for letting me know.

**Comment by meeple142** [comment]
I have used nwjs but didnt realize that it can do clipboard functions. If the functionality is out there then no reason to reinvent it! Thank you for letting me know.

**Comment by octalmage** [comment]
Of course! Let me know if you have any issues selecting text. That's not something I've used RobotJS for before!
