### ISSUE TITLE
Faster moveMouseSmooth

### ISSUE THREAD

**Issue by fritx** [octalmage/robotjs#174]
I've tried the [moveMouseSmooth](https://github.com/octalmage/robotjs/wiki/Syntax#movemousesmoothx-y) api, and it's quite awesome!
But it's a little bit slow to me, that while [remote controlling](https://github.com/maxogden/screencat), it takes more time to finish work.

So I think maybe it's possible for users to config the milliseconds to `wait`? maybe always 1 ms is okay?
Thanks! :sweat_smile: 

https://github.com/octalmage/robotjs/commit/38c17004c676307c1b2c318fe5a4c71115cbe78f#commitcomment-16814517

**Comment by ryanhuellen** [comment]
Any updates? Still would like to see a feature that allows you to control smoothness speed.
