### ISSUE TITLE
Using robotJS with NWJS.io on Win32 and some minor bugs?

### ISSUE THREAD

**Issue by cryptedco** [octalmage/robotjs#175]
Hi folks, I have successfully installed robotJS on Mac and use it with our Browser tool: https://www.youtube.com/watch?v=2z3riIYny1Y&feature=youtu.be

Pretty good. Some things are not working:

mouseToggle("down") and then moving the mouse does not highlight the text under the mouse pointer. Should it do that?

And: I can not get it to run with both the Win64 AND Win32 release of NWJS - it complains that a dynamic library problem exists and does not load. Is robotJS tested in Windows10 in general? Just wondering, if I need to dig deeper or if the NWJS version is the problem....

Thanks,
Ralf

**Comment by fritx** [comment]
@cryptedco browser-automation tool, awesome thing! it's one of my recent plan, too!
is it open-sourced on github?

**Comment by octalmage** [comment]
Your browser automation tool looks great! For selecting text, could you try the dragMouse function? It accepts x, y, and button (defaults left). 

For the 64bit/32bit issue, I believe this has to do with the compiler installed. I'd have to look into it though. Different architectures need different compilers. I use Windows XP, 8 and 10 for testing. 

Let me know if this helps!

**Comment by cryptedco** [comment]
Thanks a lot for the answer, Jason! I am afraid that did not work either:

> robot.dragMouse(x,y,"left");

moved the mouse like toggle+move, but nothing is highlighted... I am on El Capitan OS X 64bit.... For the Windows question - I will try to confirm the 64bit in the whole value chain, from Win10 up to NWJS and the Visual Studio Installation (used the community release here)... somewhere is a Win32 hidden!

@fritx thanks! Not yet on GitHub, but I have done nothing to obfuscate the code and by the nature of NWJS.io, it is included in the download => on Mac it is in the PersonaTool.app/Contents/Resources/app.nw directory... I am planning to go fully GPL with it, because we earn money with the online services anyhow and not with the program. Wanna help :-)?

**Comment by fritx** [comment]
@cryptedco yeah, it's cool! I think I'm glad to help.
I've had lots of interest in NW.js & Electron.
In company, my team is building apps with NW, and I do personal works with both NW & Electron ;)
- This is a WIP prj using electron to test websites (high inspired by nightmare) https://github.com/fritx/nixe
- And this is a tool to automated-test NW desktop app! But not yet ready :\ https://github.com/fritx/nw-auto
I'm also fresh to automated-testing, but very interested in it. You know, in our country such things are not very widely-used yet.

**Comment by cryptedco** [comment]
Alright, I am giving up for now... need to get a clean VM to test it again! I tried to go 100% 32 and then 100% 64 bit and install it... failed in both scenarios with a DLL problem...

**Comment by cryptedco** [comment]
Just to complete the infos: it does work without NWJS... if I just start a test with "node robotest.js" the script executes fine... just NOT in NWJS. I have compiled it with node 5.9.0 and it always goes down with the DLL problem. I guess the two programs just do not work together yet...

![screenshot 2016-03-31 15 44 37](https://cloud.githubusercontent.com/assets/326428/14177633/85193f1e-f757-11e5-90c7-590e147d34b2.png)

Anyone here, who runs robotjs successfully with NWJS 13.x?

**Comment by octalmage** [comment]
I use RobotJS with NW.js 0.13 on Mac, but I know people have done it on Windows. Are you using nw-gyp? That's usually the issue.

**Comment by cryptedco** [comment]
Hi Jason, good point! Thanks for the hint... yes on Mac it is absolutely no problem... I just did "npm install robotjs" and the code worked right away... I will look into the compiler setting with nw-gyp again and let you know...

**Comment by cryptedco** [comment]
Alright, the nw-gyp seems to be the problem, but now I can not install the required VCbuild.exe because the links to Microsoft do not work to get the recommended SDK... exhausting... any pointers on better howtos, maybe?

**Comment by cryptedco** [comment]
Ending today on nw-gyp with: 
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location
 of the component to the system path if it is installed elsewhere.  [C:\Datavault\nwjs-sdk-v0.13.3-pre-win-x64\app.nw\node_modules\robotjs\build\binding.sln]

**Comment by octalmage** [comment]
Try some of the recommendations here: 

https://github.com/nodejs/node-gyp#installation

Sorry you're having such a hard time! This is another reason we need node-pre-gyp.

**Comment by cryptedco** [comment]
Jason, I finally got it to work :-) :facepunch:  the key was within the nw-gyp process as you suspected and I was just too stupid (unexperienced?) to read closely:

> In Linux and OSX you can just load the native module directly. In windows you’ll need to replace the file
%APPDATA%\npm\node_modules\node-gyp\src\win_delay_load_hook.c with the one at https://github.com/nwjs/nw.js/blob/nw13/tools/win_delay_load_hook.c

http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/

Thanks a lot! It is not your setup, it is the NWJS setup. It is really new with the Chrome App setup and I am not really good at coding! Thanks for your help! Awesome product in JS!

**Comment by octalmage** [comment]
Awesome! I'm so glad you figured it out. I've never seen that before, so I'm sure that will be handy in the future. I'm going to mark this as resolved! Let me know if you need anything else.

**Comment by cryptedco** [comment]
Should have closed it myself, thanks for the help... Still got the dragMouse / toggleMouse thing pending, but I will continue to test! I have to work on my credits page to say thanks to all the people helping on GitHub!
