### ISSUE TITLE
Huge ask: Get position of text on-screen?

### ISSUE THREAD

**Issue by HopefulLlama** [octalmage/robotjs#176]
In my head, after 30 seconds of thinking, something like 

robot.getPosOfText("Submit new issue");

would mean that RobotJS could go to the submit issue button directly, rather than going to a hardcoded X and Y position. 
Would also make it more flexible in the sense of different screen sizes, window location, etc.

**Comment by octalmage** [comment]
This is something that is coming with the bitmap module. You won't be able to find text, but you'll be able to find an image on the screen. So you could take a screenshot of the button and save it, then RobotJS can find and click it.

**Comment by BlazingFire007** [comment]
Any progress on this?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
