### ISSUE TITLE
Additional Function Keys

### ISSUE THREAD

**Issue by henryzhangsta** [octalmage/robotjs#178]
I was wondering if it would be possible to get the F13-F24 keys for the keyTap and keyToggle functions? These are useful since they are rarely ever mapped by any program and would make it so the automation doesn't conflict with any global hotkey listeners for sure.

**Comment by octalmage** [comment]
This shouldn't be an issue at all! I'll look into it.

**Comment by chaosprinz** [comment]
Experimentet with a local clone, where i got F13 working for Windows. Will bring in F13-F24 for all 3 Systems, commit it and send a pull-request tomorrow. Its bedtime now ^^

**Comment by MaxLyons** [comment]
Does this work now?

**Comment by octalmage** [comment]
This hasn't been implemented yet.
