### ISSUE TITLE
Numpad 0-9

### ISSUE THREAD

**Issue by dbkynd** [octalmage/robotjs#182]
I didn't see mention in the documentation or issues, and was unable to find anything with a quick glance at the source. Are the numpad keys supported in 'keyToggle'?

**Comment by Const4ntFlux** [comment]
I'm interested to know this as well.

**Comment by octalmage** [comment]
I'm very sorry for the delay, I'll look into this now!

**Comment by octalmage** [comment]
Alright, I've added some code to a new branch called numpad. Could you let me know if this works for you? 

https://github.com/octalmage/robotjs/tree/numpad

**Comment by Const4ntFlux** [comment]
Looking forward to testing @dbkynd s commit with this and #196 change!

**Comment by dbkynd** [comment]
Thanks! I've been busy as of late, but I'll try and test this weekend! Much appreciated.
