### ISSUE TITLE
Fix compile time warnings.

### ISSUE THREAD

**Issue by Deltatiger** [octalmage/robotjs#183]
Current we are getting loads of compile time warnings for windows. Mainly these are type conversions from size_t to int or to double. I think it will be better if we fix those stuff. Looks a whole lot better with a clean compile.

**Comment by octalmage** [comment]
@Deltatiger agreed! Those warnings always bothered me, but I was only able to clean them up for Mac. I'll take a look at the Linux warnings like [this](https://travis-ci.org/octalmage/robotjs/jobs/123772820#L297), or [this](https://travis-ci.org/octalmage/robotjs/jobs/123772820#L297).

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
