### ISSUE TITLE
Fix screen capture on Mac. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#188]
There something wrong with screen.capture on Mac for larger screens, the image comes out distorted. I'm looking into it now.

**Comment by DKfraDK** [comment]
Any news on this fix? :)
I'm using robotjs to create an Ambilight clone, however when using the following code, I don't seem to grab the correct pixels
`  var img = robot.screen.capture(width-zoneSize, zoneSize, zoneSize, height-zoneSize);
`
height = screen height (1440)
width = screen width (2560)
zoneSize = 100

Am I correct in assuming that even though I don't grab from y=0, I should still iterate from 0 when running through the pixels with img.colorAt(x,y)?

**Comment by octalmage** [comment]
You should try the code found here: #191

It will work much better, but the captured image is twice as large. So you'll need to take that into consideration. You can use bitmap.save to see what I mean.

**Comment by ibrahimyaacob92** [comment]
im still facing this issue

![image](https://github.com/octalmage/robotjs/assets/58116068/ebe0a4a0-9258-4eaa-9110-509809de7966)
