### ISSUE TITLE
Is this feasible with robotjs?

### ISSUE THREAD

**Issue by Industrial** [octalmage/robotjs#192]
Hi!

I've always been using AutoHotKey on windows for macros for games, and I'd like to do the same kind of thing on linux.

What I'd like to do is;

When a button gets pressed (e.g. Q), send a sequence of keys every x msec.
When the button gets pressed again, stop sending.

The logic for this is quite simple; just a toggle. I'm not sure on the keypress part :-)

**Comment by octalmage** [comment]
Hi @Industrial, this is possible with a combination of RobotJS and Electron or NW.js. With RobotJS you can send the key sequence, Electron/NW.js have global hotkey support. Look at the RobotJS wiki for the keyTap syntax. 

Let me know if you have any questions!

**Comment by Industrial** [comment]
Cool, thanks!
