### ISSUE TITLE
Importing two libraries that depend on robotjs

### ISSUE THREAD

**Issue by dasilvacontin** [octalmage/robotjs#193]
Hi!

I'm getting the following when I import both `electron` and `ludumpad-mapper` – both depend on `robotjs`. Any clue on how to solve it? Thanks!

<img width="532" alt="screenshot 2016-05-17 16 18 16" src="https://cloud.githubusercontent.com/assets/1260830/15325580/2db65e14-1c4b-11e6-9468-f5e503f2297f.png">

**Comment by dasilvacontin** [comment]
Worth noting that I'm using Node v5.10.1.

**Comment by dasilvacontin** [comment]
Fixed by installing and using Node v6. Any clue on why? They worked separately. At least `ludumpad-mapper`. Maybe `electron` is somehow and for some reason require usage of Node v6, or `electron-prebuilt` is built with Node v6...

**Comment by octalmage** [comment]
Hmm that's odd. Which version of RobotJS? RobotJS is compatible with all recent versions of Node, and only ludumpad-mapper requires RobotJS.

**Comment by dasilvacontin** [comment]
I see, sorry for the wrong assumption. I guess electron-prebuilt comes with Node v6 and ludumpad-mapper's RobotJS had been built using my machine's Node, which was v5. And that's why it was throwing the mismatch error.

**Comment by octalmage** [comment]
That sounds reasonable! electron-rebuild could have also resolved it. Let me know if you need anything else!

**Comment by dasilvacontin** [comment]
I actually tried using `electron-rebuild`, but it didn't work. Maybe I did something wrong – might try again for the sake of curiosity.
