### ISSUE TITLE
Support for virtual game controllers

### ISSUE THREAD

**Issue by dasilvacontin** [octalmage/robotjs#195]
Would you like to have this feature in this library, or would you rather have some other library that offers cross-platform support for virtual game controllers in Node.js?

**Comment by octalmage** [comment]
What is the feature? I've seen a number of virtual game controllers created using RobotJS.

**Comment by dasilvacontin** [comment]
@octalmage Virtual game controller as in the OS thinks an actual game controller is connected. Similar to what is done in https://github.com/miroof/node-virtual-gamepads. But cross-platform.

If such thing has been done, any links?

**Comment by octalmage** [comment]
Gotcha, I thought you meant controlling a game using a virtual controller, not emulating an actual hardware controller. I think this library is better for the former, the latter maybe not. Is this for games that cannot be controlled with a mouse/keyboard?

**Comment by dasilvacontin** [comment]
Yes, for games that are already set up to be played with controllers, or that only support multiple players via multiple controllers. Specially the latter.

I see you've checked [LudumPad](https://github.com/dasilvacontin/ludumpad). This feature would be useful to fake multiple hardware controllers using multiple mobile devices running LudumPad.

It's not a blocker for me, more like a nice have that I would like to have working someday. :)

**Comment by octalmage** [comment]
Hmm that's interesting. I guess it depends on how difficult it is to implement for Windows and Mac. It seems like it may require special drivers which I wouldn't nessesarily be interested in maintaining. Have you looked into it at all?

**Comment by dasilvacontin** [comment]
Yes, I've looked a bit into it. I was just wondering if you had also thought about having this feature, or were 'open' to host it at RobotJS.

But I guess most RobotJS users will not care about this feature, and its uses cases are not many (so I imagine it will have few actual users), so maybe it would be a better idea to have it as a separate library.

**Comment by knubie** [comment]
A library [vJoy](http://vjoystick.sourceforge.net/site/) or [vXboxInterface](https://github.com/shauleiz/vXboxInterface) might work for this one Windows. Unfortunately I haven't found anything for OSX yet.

**Comment by octalmage** [comment]
I'm going to close this for now, I'd be interested in solving this problem, but most likely in another module. Thanks for the suggestion!

**Comment by dasilvacontin** [comment]
No worries! Let me know if you start working on this problem, I'll be happy to help.
