### ISSUE TITLE
keyToggle/mouseToggle for an unspecified amount of time?

### ISSUE THREAD

**Issue by knubie** [octalmage/robotjs#197]
Is it possible for robot.js to `keyToggle` or `mouseToggle` 'down' indefinitely until the `keyToggle` or `mouseToggle` up is called? At the moment it seems to automatically toggle 'up' after the specified amount of time in `setKeyboardDelay` and `setMouseDelay`.

My particular use case is that I have a function that gets called every ~10ms which receives gamepad input and maps them to keyboard/mouse events. It looks something like this:

```js
var mouseDown = false;

function gamepadEvent(gamepadData) {
  if (gamepadData.buttonPressed === 16 && !mouseDown) {
    robot.mouseToggle('down');
    mouseDown = true;
  } else if (gamepadData.buttonPressed !== 16 && mouseDown) {
    robot.mouseToggle('up');
    mouseDown = false;
  }
}
```

My issue is that I need the `setMouseDelay` at 1ms in order to accurately map mouse movements with minimal lag, however the result is that the `mouseToggle('down')` only lasts for 1ms, instead of staying down until the `mouseToggle('up')` is called.

**Comment by octalmage** [comment]
Hmm which OS are you using? Toggling a key or mouse button should hold it down until you up it or the real key is pressed. I confirmed this works as expected on Mac using the on screen keyboard.

**Comment by octalmage** [comment]
I also just tested the same using mouseToggle: 

```
var robot = require('robotjs');

robot.setMouseDelay(1);
setTimeout(function()
{
	robot.mouseToggle('down');

	setTimeout(function()
	{
		robot.mouseToggle('up');
	}, 5000);

}, 5000);
```

Here's the result: 

![](https://cloudup.com/cs4rg1WW44G+)

**Comment by knubie** [comment]
Ok, I just tested this again and you're right, it does to hold down for both. I think I was thrown off because I wasn't able to select text with the mouse, and with the keyboard the key repeat wasn't activating (i.e. holding down 'w' didn't produce wwwwwww etc.). Are these just limitations of the way the keypresses are being produced?

**Comment by octalmage** [comment]
Exactly! You can use dragMouse to hold the mouse and down move it, it's a weird Mac OS limitation. Same with holding buttons down, it doesn't type the key multiple times.

**Comment by knubie** [comment]
Got it! Thanks 👍
