### ISSUE TITLE
Building a Makefile

### ISSUE THREAD

**Issue by daniel-lucio** [octalmage/robotjs#201]
Hi,

I am making a Makefile for linux. Almost everything is working, but I am stuck here:

robotjs.cc:2:17: erreur fatale : nan.h : Aucun fichier ou dossier de ce type

What package/library provides nan.h ?

**Comment by octalmage** [comment]
https://github.com/nodejs/nan

Curious, why are you making a makefile? Gyp generates one automatically.

**Comment by daniel-lucio** [comment]
Can you share it? My gyp is not withing here 
Le 25 mai 2016 1:12 PM, Jason Stallings <notifications@github.com> a écrit :https://github.com/nodejs/nan

Curious, why are you making a makefile? Gyp generates one automatically.

**Comment by octalmage** [comment]
Here you go: 

https://cloudup.com/chb3oFoXWWf.zip

That is what was generated, but it's probably Mac specific. I don't think it's going to be much help. 

Are you having issues with node-gyp?

**Comment by daniel-lucio** [comment]
yes node-gyp is not running here, and I am packaging as an RPM. So the node packaging engine won't apply here.

**Comment by octalmage** [comment]
Gotcha, try running `node-gyp configure` on Linux, then checking the build directory for the makefile.

**Comment by octalmage** [comment]
Were you able to get this resolved?

**Comment by daniel-lucio** [comment]
On dimanche 12 juin 2016 15:28:04 EDT Jason Stallings wrote:
> Were you able to get this resolved?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/octalmage/robotjs/issues/201#issuecomment-225464334

No yet, be patient

**Comment by octalmage** [comment]
I'm going to close this, if you still need help please let me know!
