### ISSUE TITLE
keyTap only works in debug mode

### ISSUE THREAD

**Issue by escapedcanadian** [octalmage/robotjs#202]
I'm using node v5.11.1, socket.io 1.4.6 and robotjs 0.4.2.  My code is very simple ...

```
var robot = require("robotjs");

function pausePlayer(){
	robot.keyTap('z','alt');
}
```
However, the pausePlayer() function is called by a handler on socket.io.

`	socket.on('pause player', function(data){
		pausePlayer();
	});`

 If I run the program in a debugger, with a breakpoint on the keyTap() line, it works fine and has the expected results.  But if I run it real-time, it doesn't seem to do anything.

Using setKeyboardDelay() with a larger number seemed in incur a delay, but the key-press still didn't have any effect.

Not sure how to debug this one further. Your help would be appreciated.

**Comment by escapedcanadian** [comment]
With more investigation, this may have something to do with Google Chrome consuming all Global Hotkeys while it has the focus.  Jumping to the debugger took focus away from Chrome.  I had tried many combinations of keys with modifiers, so I had assumed I would have hit an unused combination sometime, but it seems Chrome consumes them all.

**Comment by octalmage** [comment]
Interesting, I'm glad you figured it out! Let me know if you need anything.
