### ISSUE TITLE
Npm ignore test files

### ISSUE THREAD

**Issue by lawnzapper** [octalmage/robotjs#204]
I'm working on an electron app and noticed that my packaged app size could be smaller if you could add .npmignore to the repository to remove test files as test.raw (20mb). Obviously I'm removing myself manually before packaging. Anyway thank you for RobotJs, it's great!

**Comment by octalmage** [comment]
Oops! Thanks for letting me know, I'll get it fixed.

**Comment by octalmage** [comment]
Fixed in RobotJS v0.4.4 which has been published to npm! Thanks again!
