### ISSUE TITLE
moveMouseSmooth visibly slower on Windows 10 than on Mac

### ISSUE THREAD

**Issue by alexmirea** [octalmage/robotjs#207]
Hello,

I am using RobotJS and when using moveMouseSmooth it performs a lot slower on Windows 10 Enterprise 64bit than it does on Mac El Capitan 10.11.

The test I did was
```
var Robot = require("robotjs");
Robot.moveMouse(0,0);
console.time("Move mouse");
Robot.moveMouseSmooth(300, 300);
console.timeEnd("Move mouse");
```

On Windows I always get results like `Move mouse: 4680ms`
On Mac I always get results like `770ms`
Does anyone have an insight into this? 
I just ran it multiple times and sometimes I get ~2000ms than back to ~4000 ms
One note would be that I am using Bootcamp for running my Windows instance.
I asked a colleague to make the test as well and he gets ~700ms on a Windows machine.

**Comment by octalmage** [comment]
Hi there! I'll respond to both of your issues later today. Sorry for the delay.

**Comment by octalmage** [comment]
moveMouseSmooth has a bit of randomness built in, It's meant to simulate a human. Macs tend to have a much higher resolution which would mean the mouse has further to move. 

I plan on creating a new function that allows you to specify the delay between the moves, #174 tracks this request. 

Could this explain what you're seeing?

**Comment by alexmirea** [comment]
@octalmage thanks!
Well I tried at more people with Windows machine, and they get results closer to Mac. I think it might have something to do with Bootcamp, maybe related to drivers...I am not sure.

On the other hand new function with specifying the delay between moves is something I am waiting for as well :+1:

**Comment by octalmage** [comment]
Awesome! I'll get it added in the next release.

**Comment by octalmage** [comment]
I'm going to close this in favor of #174.
