### ISSUE TITLE
Shift dragging

### ISSUE THREAD

**Issue by alexmirea** [octalmage/robotjs#208]
I am working on a test that requires holding SHIFT down and dragging with the Mouse.
What is the correct way of doing that with RobotJS? 
I saw that keyToggle doesn't allow modifiers.
I did something like `Robot.keyToggle(String.fromCharCode(16), 'down', 'shift')` and then  `Robot.keyToggle(String.fromCharCode(16), 'up'`
and it seems to work on Mac. (16 being the event keyCode for `shift`)
 On Windows I get a very undefined behaviour, the `Shift` key stays pressed sometimes.

I tried on Windows `Robot.keyToggle('shift', 'down')` and this seems to work, but doesn't on Mac.

**Comment by octalmage** [comment]
Hi @alexmirea,

Holding a key down with keyToggle should work. For dragging the mouse you'll need to use dragMouse. It accepts the same arguments as moveMouse. Could you try this?

**Comment by octalmage** [comment]
I just played with this, and the second you move the mouse the shift key is lifted. It looks like this is a known issue: 

http://stackoverflow.com/questions/17773225/cgeventpost-hold-a-key-shift

I'll see what I can find.

**Comment by octalmage** [comment]
Looks like there's a possible solution here: 

http://stackoverflow.com/questions/2008126/cgeventpost-possible-bug-when-simulating-keyboard-events/8202467#8202467

Mac has been the most quirky OS for RobotJS. Apparently I need to tell the mouse move that shift is being held down.

**Comment by alexmirea** [comment]
@octalmage so doing `Robot.keyToggle('shift', 'down')` on Mac as well should work? I didn't know `dragMouse` exists I can't find it in the [API](https://github.com/octalmage/robotjs/wiki/Syntax). I did it with a `mouseToggle` and `mouseMove`.

Regarding the issue you have found, if the shift key is lifted ... then why is it working for me when I am doing `Robot.keyToggle(String.fromCharCode(16), 'down', 'shift')` instead of  `Robot.keyToggle('shift', 'down')`  and moving with `mouseToggle` and `mouseMove`. Are they doing through different Mac APIs?

**Comment by octalmage** [comment]
The solution is to hold shift down as a modifier instead of a button when dragging the mouse, so that would explain why it works!

**Comment by octalmage** [comment]
They are using different code, on Mac modifiers and keys are separate, it really makes no sense. If you want to press ctrl+a, you hold down ctrl and press a. Not on Mac! You need to press a with shift as a modifier.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
