### ISSUE TITLE
[Use case] webbymouse

### ISSUE THREAD

**Issue by gasolin** [octalmage/robotjs#21]
Hi, FYI I've made a Desktop app (via node webkit) which use robotjs to control desktop mouse. 
It bundle with express server so user can open a mobile browser and the mobile device turn into touchpad immediately. 

https://github.com/gasolin/webbymouse

**Comment by octalmage** [comment]
Looks awesome! I'll make a wiki page for apps using RobotJS when I get home.

**Comment by octalmage** [comment]
Alright you can add your app to this list! 

https://github.com/octalmage/robotjs/wiki/Projects-using-RobotJS

Please follow this format: 

https://github.com/nwjs/nw.js/wiki/List-of-apps-and-companies-using-nw.js

Let me know when it's added!

**Comment by octalmage** [comment]
I added WebbyMouse for you! 

https://github.com/octalmage/robotjs/wiki/Projects-using-RobotJS

**Comment by gasolin** [comment]
thanks!
