### ISSUE TITLE
Get rid of dragMouse. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#211]
Instead of making developers tell RobotJS when they want to drag the mouse, just track when the mouse button is toggled down.

**Comment by rayfoss** [comment]
That would open the door for dragMouseSmooth without a new api

```
const closer = (a,b) => ( a > b ? a-1 : a+1 )
async function dragMouseSmooth (ox,oy,last) {
  if (last && last.x === ox && last.y === oy) { return }
  const p = last ? last : robot.getMousePos();
  const r = { x: closer(p.x, ox), y: closer(p.y, oy) }
  robot.dragMouse(r.x, r.y)
  dragMouseSmooth(ox, oy, r)
}
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
