### ISSUE TITLE
Global onMouseClick event

### ISSUE THREAD

**Issue by sklink** [octalmage/robotjs#213]
Getting global mouse position is great. Is it possible to also know when the mouse is clicked without the `robotjs` app having focus?

**Comment by sklink** [comment]
I was able to get global mouse click listener in electron using this: https://www.npmjs.com/package/gkm

Listeners may be out of the scope of this project so feel free to close this if you think that's appropriate.

**Comment by octalmage** [comment]
They are out of scope for now, but I'm glad you found a solution! Let me know if you need anything else.

**Comment by colorao** [comment]
Im quite late on this thread, but in 2022 ain't no possibility to get system mouse clicks?
