### ISSUE TITLE
Install fails on OSX

### ISSUE THREAD

**Issue by ldorigo** [octalmage/robotjs#215]
[npm-debug.log.zip](https://github.com/octalmage/robotjs/files/314770/npm-debug.log.zip)

**Comment by octalmage** [comment]
It looks like the call to spawn prebuild failed. Could you try clearing the npm cache then reinstalling? You can clear the cache with: 

```
npm cache clean
```

Thanks!

**Comment by octalmage** [comment]
I'm going to close this issue, if you still need help please let me know!
