### ISSUE TITLE
Can't build on win8

### ISSUE THREAD

**Issue by raelgor** [octalmage/robotjs#22]
Did I forget to do something or is this a version mismatch?

![image](https://cloud.githubusercontent.com/assets/3382344/7182941/19d25636-e45d-11e4-97cf-69398be30e8c.png)

**Comment by RangerMauve** [comment]
AFAIK this library doesn't support windows.

**Comment by raelgor** [comment]
Oh, sorry, didn't realize. Would love to see it on windows though.

**Comment by octalmage** [comment]
The code technically supports Windows, I'm just having a hard time getting the node-gyp build flags right. It's in the works though! #2

Star the project to get notified of updates!

**Comment by octalmage** [comment]
I'm honestly stuck, I'm going to reach out to the node-gyp team today.

**Comment by raelgor** [comment]
Starred it! Good luck with that... I wish I could help but this stuff is beyond me :/

**Comment by octalmage** [comment]
Ha thanks! Apparently it's beyond me too. :p

**Comment by zz85** [comment]
i think the reason is that robotjs doesn't support windows currently https://github.com/octalmage/robotjs it's a pity though...
