### ISSUE TITLE
robot.keyTap('lights_mon_down',['alt','shift']) doesn't work

### ISSUE THREAD

**Issue by amaramth** [octalmage/robotjs#221]
`robot.keyTap('lights_mon_down',['alt','shift'])` doesn't work: On OSX, ⌥⇧FnF1 lowers the brightness by a quarter of a notch, but afaict there's no way to do that with this library.

I'm currently using `osascript -e 'tell app "system events"' -e 'key code 107 using {option down, shift down}' -e 'end tell'` as a workaround.

**Comment by octalmage** [comment]
Interesting, I didn't know this hotkey existed. The logic for these keys is different, and it currently doesn't support modifiers. I'll need to look into it.

**Comment by alice0meta** [comment]
I figured. Would just calling osascript in those cases be fine? The only downside is that it costs 80ms.

I'd offer a patch but I don't know much C

**Comment by octalmage** [comment]
I'd like to keep this library native, but a separate library that just provides this functionality could be cool as a polyfill though!

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
