### ISSUE TITLE
replacement for ahk: hotkeys and hotstrings

### ISSUE THREAD

**Issue by matthewmorrone1** [octalmage/robotjs#223]
are there any plans to implement functionality that can listen for/override/remap keyboard and mouse input? autohotkey is great but it's super messy; I'd love to be able replace a good deal of its functionality with robotjs.

**Comment by octalmage** [comment]
This is something I'd like to do, but it's not going to happen anytime soon. It's just a different animal and I want to get the stuff RobotJS currently does down first. See: 

https://github.com/octalmage/robotjs#does-robotjs-support-global-hotkeys
#55
