### ISSUE TITLE
How to upload the file in Mac OS

### ISSUE THREAD

**Issue by vivek31** [octalmage/robotjs#226]
I am using Mac OS and wanted to use RobotJS for uploading spreadsheet but need help in order to perform the same.

Could you please share steps for it ?

For Windows I found below steps:

browseBtn.click().then(function(){
	  browser.driver.sleep(3000);
	  robot.setKeyboardDelay(100);
	  robot.typeStringDelayed("\\", 40);
	  robot.typeStringDelayed(filePath, 100);
	  robot.keyTap("enter");
	  browser.driver.sleep(3000);
  });

**Comment by vivek31** [comment]
Do we have any update on this ticket ?

**Comment by octalmage** [comment]
I'm not sure what you're looking for! Is uploading on Mac not working?

**Comment by octalmage** [comment]
Take a look at #170 and see if the solution there helps. If not please let me know!

**Comment by laddu1986** [comment]
I am in need of code using robotjs for uploading an image in some form in **Mac OS**

Only in Mac since a piece of code is already available for windows in the same thread
