### ISSUE TITLE
Control keyboard on iOS/Android

### ISSUE THREAD

**Issue by dicristomanuel** [octalmage/robotjs#227]
Hey there, I was wondering if there is any plan to make this library available for mobile development as well or if someone here knows about a library that could help injecting text on iOS/Android like robotjs does. Thank you!

**Comment by octalmage** [comment]
Hi @dicristomanuel, 

Unfortunately I don't have any plans to port this to iOS/Android, and I don't know if it would be possible (especially on iOS). I'm also not familiar with any library that does this. 

Sorry I couldn't help!
