### ISSUE TITLE
Versioning or not found error with electron-prebuilt on ElementaryOS

### ISSUE THREAD

**Issue by prestonkyles** [octalmage/robotjs#228]
## Expected Behavior
I'm using the latest version of electron-prebuild (1.3.3) to create a global shortcut, or hotkey, that prints out the cursor location. Also, I'm running the latest version of Node (6.4.0) and NPM (3.10.3).

Code trying to execute:
```
const {app, globalShortcut} = require('electron');
const robot = require('robotjs');

app.on('ready', () => {
  const ret = globalShortcut.register('CommandOrControl+X', () => {
    console.log('ayy lmao the shortcut was pressed');
    console.log(robot.getMousePos());
  });

  if(!ret) {
    console.log('lmao your computer sux');
  }
});

app.on('will-quit', () => {
  globalShortcut.unregister('CommandOrControl+X');
  globalShortcut.unregisterAll();
});
```

## Current Behavior
What I currently get is a version error:

```
App threw an error during load
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/project/path/node_modules/robotjs/index.js:1:94)
```

I'll try building from source with NPM:
```npm --build-from-source --save-dev robotjs```
but then the module won't be found.

I've tried using electron-rebuild but that didn't seem to help.

## Possible Solution
I think the problem is with using native modules with electron-prebuilt (http://electron.atom.io/docs/tutorial/using-native-node-modules/). I've tried different ways in rebuilding the source but haven't been able to get a working version of robotjs.

## Steps to Reproduce (for bugs)
1. Be on ElementaryOS
2. Use latest versions of Node, NPM, and electron-prebuild.
3. Install RobotJS with a project that was initiated with NPM
        ```npm init```
        ```npm install --save-dev robotjs```
4. Use Babel and Gulp to run ES6 code
5. Get an error when running with ```electron .``` after comiling

## Context
I'm working on a small electron app that allows you to control the mouse cursor from your keyboard and this module enabled me to work with the mouse on all platforms. A lot better than me writing it in C/C++ and having to work on multiple versions.

## Your Environment
* RobotJS version: 0.4.4
* Electron: 1.3.3
* Node.js version: 6.4.0
* npm version: 3.10.3
* Operating System: ElementaryOS

**Comment by Furqankhanzada** [comment]
+1

**Comment by Furqankhanzada** [comment]
@prestonkyles  i solved it :)

go to ```node_modules/robotjs```
and run 
 ```sudo HOME=~/.electron-gyp node-gyp rebuild --target=1.3.4 --arch=x64 --dist-url=https://atom.io/download/atom-shell```

**Comment by octalmage** [comment]
This is a problem with NW.js and Electron. They use special versions of Nodejs so native modules need to be compiled. There's docs on this here: 

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
