### ISSUE TITLE
keyTap('x', 'command') will cause segmentation fault on OSX El Captain 10.11.6

### ISSUE THREAD

**Issue by JackTheHigher** [octalmage/robotjs#229]
* RobotJS version:0.4.4
* Node.js version:4.4.5
* npm version:3.10.5
* Operating System: OSX El Captain 10.11.6

**Comment by octalmage** [comment]
Hi @JackTheHigher, this doesn't cause I segmentation fault on my machine, I'm using the same version of OS X. Here's the code I tried: 

```
var robot = require('robotjs');
robot.keyTap('x', 'command');
```

**Comment by JackTheHigher** [comment]
Thanks very much for your reply, but on my machine, it occurs frequently lately, and I can't even run npm test, because of the segmentation fault.

**Comment by JackTheHigher** [comment]
About several hours ago, everything went all right, but now, even this little piece of code goes wrong on my machine, it's really weird.

**Comment by JackTheHigher** [comment]
here is my code:
var robot = require('robotjs');
robot.keyTap('d', 'command');
and the attachment shows my result:

**Comment by JackTheHigher** [comment]
![image](https://cloud.githubusercontent.com/assets/10335088/17897201/e3f5d6a0-6985-11e6-9576-6d00dcd31917.png)

**Comment by JackTheHigher** [comment]
sorry to interrupt, there may be something wrong with my node environment, I'll go check further.

**Comment by xudaolong** [comment]
@JackTheHigher hey, my problem same with you, can you tell me how to deal with it.

**Comment by maniolias** [comment]
@xudaolong 
Try to : 
1. Uninstall the module robotjs
2. Install node-gyp globally
3. Reinstall robotjs in your project.

This solution worked for me.
