### ISSUE TITLE
how to perform mouse right click

### ISSUE THREAD

**Issue by milannjovanovski** [octalmage/robotjs#232]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* RobotJS version:
* Node.js version:
* npm version:
* Operating System:

**Comment by 1j01** [comment]
```js
var robot = require("robotjs");

robot.mouseClick("right");
```

[`mouseClick` is documented here](https://github.com/octalmage/robotjs/wiki/Syntax#mouseclickbutton-double). It might be unclear since it doesn't explicitly show the values as strings.

**Comment by octalmage** [comment]
I'm going to mark this as closed, if you still need help please let us know.
