### ISSUE TITLE
Bug under Ubuntu on MacBook

### ISSUE THREAD

**Issue by hadrien-toma** [octalmage/robotjs#235]
Hi,

First of all, this is my environment :
- Hardware : **MacBook**
- Keyboard : **AZERTY**
- Operating system : **Ubuntu 14.04.5 LTS**
- Kernel : Linux 3.19.0-32-generic
- Distribution / Desktop: Linux Mint 17.3 Rosa / KDE [with **keyboard layout French (Macintosh)**]

It seems that there are several bugs, here is the code used in my tests :
`var robot = require("robotjs")`
`var tested_string = "A"`
`robot.typeString(tested_string)`

It outputs me (correctly) :
`A`

**Now, the left column will be the keys I tested, the right one will contain the result given by the previous test code :**
`Value | Result` Note
`"A" | A`All letters and numbers are correct
`"&" | &` 
`"é" | ^@^@` 
`'"' | ^@` 
`"'" | "`The prompt is not release, I had to kill the process
`"(" | (`
`"{" | (`
`"[" | (`
`"§" | ^@^@`
`"è" | ^@^@`
`"!" | !`
`"ç" | ^@^@`
`"à" | ^@^@`
`")" | )`
`"}" | )`
`"]" | )`
`"°" | ^@^@`
`"-" | -`
`"_" | -`
`"@" | @` 
`"#" | @`With a line break
`"<" | <`
`">" | <`With a line break
`"," | ,`
`"?" | ,`With a line break
`";" | ;`
`"." | ;`With a line break
`":" | :`
`"/" | :`With a line break
`"=" | =`
`"+" | =`With a line break
`"$" | $`
`"*" | $`With a line break
`"ù" | ^@^@`
`"%" | ù`
`"£" | ^@^@`
`"€" | ^@^@^@`
`"/" | ^@^@`
`"|" | l`
`"~" | n`

**And finally some strings (like "`" and "^") throw this error :**
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  132 (XTEST)
  Minor opcode of failed request:  2 (X_XTestFakeInput)
  Value in failed request:  0x0
  Serial number of failed request:  14
  Current serial number in output stream:  16
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  132 (XTEST)
  Minor opcode of failed request:  2 (X_XTestFakeInput)
  Value in failed request:  0x0
  Serial number of failed request:  15
  Current serial number in output stream:  18

**An idea of what is going on?**

**Comment by octalmage** [comment]
It seems like it could be a unicode issue. I haven't looked into this yet but I imagine we have the keyboard type hardcoded somewhere and it's causing this. It could be related to #16.

**Comment by hadrien-toma** [comment]
I also think that it is related to #16, I'll take a look to keypress.c, it was good of you to quote that, thank you.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
