### ISSUE TITLE
Document building process for Electron/NW.js

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#236]

**Comment by octalmage** [comment]
I think it would be best to create a wiki page with the instructions,  then link to it from the readme.

**Comment by zeke** [comment]
There is a wiki page already: https://github.com/octalmage/robotjs/wiki/Electron

I wondered if any of the discoveries in https://github.com/octalmage/robotjs/issues/190#issuecomment-248398055 merited updating that page.

**Comment by octalmage** [comment]
@zeke ha I totally forgot about that! I added a link to the readme. 

Thanks!
