### ISSUE TITLE
follow w3c specifications？

### ISSUE THREAD

**Issue by xudafeng** [octalmage/robotjs#237]
like webdriver or other desktop automation spec?

**Comment by 1j01** [comment]
RobotJS isn't a web browser, so I don't think the WebDriver spec would apply directly, but you should be able to use [`selenium-webdriver`](https://www.npmjs.com/package/selenium-webdriver) in conjunction with `robotjs`.

**Comment by xudafeng** [comment]
@1j01 wrap `robotjs` like a driver to support cross end automation.

https://github.com/macacajs

**Comment by 1j01** [comment]
By cross-end automation do you mean having code that could run both with RobotJS and a web browser? Or just a familiar API between code that does those separate things? What's the goal?

**Comment by xudafeng** [comment]
driver UI system by w3c webdriver api

**Comment by 1j01** [comment]
That doesn't clarify anything for me. It would help to know what you're trying to do, spefically, if anything.
For instance if you just want to use RobotJS remotely, there are modules that will let you do that.

**Comment by xudafeng** [comment]
@1j01 Thx

**Comment by octalmage** [comment]
That would be interesting. It would be pretty easy to create a wrapper project, syntax is being discussed here: #4.

**Comment by daluu** [comment]
Well, if not part of the core project, one could spin off a 3rd party project that wraps RobotJS around the WebDriver API. For ideas on that, to reduce work, one could base the wrapper skeleton around either the Appium project (currently node.js based, and follows WebDriver API to certain extent), or around any of the node.js WebDriver implementations - just take out the internal plumbing for what the UI automation does behind the scenes (for browser/mobile) and replace with code that invokes RobotJS.

See https://github.com/daluu/autoitdriverserver or https://github.com/daluu/autopydriverserver as examples, which use the old Appium python implementation as the skeleton.

**Comment by daluu** [comment]
> For instance if you just want to use RobotJS remotely, there are modules that will let you do that.

@1j01 for clarification for readers to minimize searching, what modules exactly are we talking about here? Pointing out links to the details would be helpful.

**Comment by 1j01** [comment]
@daluu [Generic RPC modules](https://www.npmjs.com/search?q=keywords:rpc).
I would only recommend this if you can fully guarantee commands are coming from a trusted source, e.g. with an HTTPS/SSH connection, to a trusted system... if that's enough! idk, I've never done this, and haven't thought it thru thoroughly. But I would say you can assume access to robot.js means full access to the system. So it's dangerous.

**Comment by daluu** [comment]
Thanks for the link. Indeed, the access issue would apply to any desktop GUI automation tool, it's up to the user to decide how they want to deploy.

Alternative options also could be to restrict access to the host running robot.js to only certain IP ranges, remote hosts, etc. including use of VPN, it at least limits the scope of access.
