### ISSUE TITLE
Electron: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Fing001** [octalmage/robotjs#239]
Error Infomation:
ELECTRON_ASAR.js:168  Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\?\E:\node_modules\robotjs\build\Release\robotjs.node
## Your Environment
- RobotJS version: new version
- Node.js version: 4.1.2
- npm version: 2.14.4
- Operating System: windows 8.1 x64
- Python: 2.7.12
- Electron: 1.4.1

**Comment by octalmage** [comment]
Hi @Fing001! 

Native modules need to be rebuild for Electron. They use a special version of Node. You can read more about this here: 

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

This article should help you get it setup: https://github.com/octalmage/robotjs/wiki/Electron

Please let me know if you need anything else!

**Comment by Fing001** [comment]
Still can't get it done. very much want to try, but this stops me.
------------------------------------------------------------------------------------------------------------
E:\>npm rebuild --runtime=electron --target=1.4.1 --disturl=https://atom.io/down
load/atom-shell --abi=48

> electron-prebuilt@0.36.12 postinstall E:\node_modules\electron-rebuild\node_mo
dules\electron-prebuilt
> node install.js


> nslog@3.0.0 install E:\node_modules\electron-rebuild\node_modules\nslog
> node-gyp rebuild


E:\node_modules\electron-rebuild\node_modules\nslog>if not defined npm_config_no
de_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:907:11)
gyp ERR! stack     at TCP.onread (net.js:557:26)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\node_modules\electron-rebuild\node_modules\nslog
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "rebuild" "--runtime=electron" "--target=1.4.1" "--disturl=https://atom.io
/download/atom-shell" "--abi=48"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\npm-debug.log

**Comment by Fing001** [comment]
I follow this page to do, but still can't get it done,

E:\node_modules\robotjs>node-gyp rebuild --runtime=electron --target=1.4.1 --dis
turl=https://atom.io/download/atom-shell --abi=48
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.0 | win32 | x64
gyp http GET https://atom.io/download/atom-shell/v1.4.1/iojs-v1.4.1.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v1.4.1/iojs-v1.4.1.tar.gz
gyp http GET https://atom.io/download/atom-shell/v1.4.1/SHASUMS256.txt
gyp http GET https://atom.io/download/atom-shell/v1.4.1/win-x64/iojs.lib
gyp http GET https://atom.io/download/atom-shell/v1.4.1/win-x86/iojs.lib
gyp http 200 https://atom.io/download/atom-shell/v1.4.1/SHASUMS256.txt
gyp http 200 https://atom.io/download/atom-shell/v1.4.1/win-x64/iojs.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at createHangUpError (_http_client.js:213:15)
gyp ERR! stack     at Socket.socketOnEnd (_http_client.js:305:23)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at Socket.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:921:12)
gyp ERR! stack     at nextTickCallbackWith2Args (node.js:442:9)
gyp ERR! stack     at process._tickCallback (node.js:356:17)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "D:\\nodejs\\node.exe" "C:\\Users\\MaiBenBen1\\AppData\\Roaming
\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--runtime=electron"
"--target=1.4.1" "--disturl=https://atom.io/download/atom-shell" "--abi=48"
gyp ERR! cwd E:\node_modules\robotjs
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by Fing001** [comment]
Now I get another problem, very sad, still not working

E:\node_modules\robotjs>node-gyp rebuild --runtime=electron --target=1.4.1 --dis
turl=https://atom.io/download/atom-shell --abi=48
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.0 | win32 | x64
gyp info spawn D:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\MaiBenBen1\\AppData\\Roaming\\npm\\node_module
s\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\node_modules\\robotjs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\MaiBenBen1\\AppData\\Roaming\\npm\\node_module
s\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\MaiBenBen1\\.node-gyp\\iojs-1.4.1\\common.gypi
',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\MaiBenBen1\\.node-gyp\\iojs-1.
4.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\MaiBenBen1\\AppData\\Roaming\\n
pm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\node_modules\\robotjs',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\node_modules\\robotjs\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  robotjs.cc
  win_delay_load_hook.cc
e:\node_modules\robotjs\src\os.h(26): warning C4005: 'STRICT': macro redefiniti
on (compiling source file ..\src\robotjs.cc) [E:\node_modules\robotjs\build\rob
otjs.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h(23): note:
   see previous definition of 'STRICT' (compiling source file ..\src\robotjs.cc
  )
..\src\robotjs.cc(598): warning C4267: 'argument': conversion from 'size_t' to
'const unsigned int', possible loss of data [E:\node_modules\robotjs\build\robo
tjs.vcxproj]
..\src\robotjs.cc(713): warning C4267: 'initializing': conversion from 'size_t'
 to 'uint32_t', possible loss of data [E:\node_modules\robotjs\build\robotjs.vc
xproj]
e:\node_modules\robotjs\node_modules\nan\nan_new.h(208): warning C4244: 'argume
nt': conversion from 'std::size_t' to 'double', possible loss of data (compilin
g source file ..\src\robotjs.cc) [E:\node_modules\robotjs\build\robotjs.vcxproj
]
  ..\src\robotjs.cc(674): note: see reference to function template instantiatio
  n 'v8::Local<v8::Number> Nan::New<v8::Number,std::size_t>(std::A0)' being com
  piled
          with
          [
              A0=std::size_t
          ]
  deadbeef_rand.c
  mouse.c
  keypress.c
  keycode.c
  screen.c
  screengrab.c
  snprintf.c
  MMBitmap.c
..\src\deadbeef_rand.c(26): warning C4267: 'return': conversion from 'size_t' t
o 'uint32_t', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxp
roj]
..\src\mouse.c(114): warning C4267: '=': conversion from 'size_t' to 'LONG', po
ssible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(115): warning C4267: '=': conversion from 'size_t' to 'LONG', po
ssible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(345): warning C4244: '+=': conversion from 'double' to 'std::siz
e_t', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj]
..\src\mouse.c(346): warning C4244: '+=': conversion from 'double' to 'std::siz
e_t', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj]
..\src\screengrab.c(130): warning C4267: 'function': conversion from 'size_t' t
o 'int', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj]
..\src\screengrab.c(131): warning C4267: 'function': conversion from 'size_t' t
o 'int', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj]
..\src\snprintf.c(965): warning C4267: '=': conversion from 'size_t' to 'int',
possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj]
..\src\snprintf.c(911): warning C4267: 'initializing': conversion from 'size_t'
 to 'int', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj
]
..\src\snprintf.c(939): warning C4267: 'initializing': conversion from 'size_t'
 to 'int', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj
]
..\src\snprintf.c(956): warning C4267: 'initializing': conversion from 'size_t'
 to 'int', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj
]
..\src\snprintf.c(976): warning C4267: 'initializing': conversion from 'size_t'
 to 'int', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj
]
..\src\snprintf.c(988): warning C4267: 'initializing': conversion from 'size_t'
 to 'int', possible loss of data [E:\node_modules\robotjs\build\robotjs.vcxproj
]
C:\Users\MaiBenBen1\.node-gyp\iojs-1.4.1\Release\iojs.lib : fatal error LNK1106
: invalid file or disk full: cannot seek to 0xF2ADE [E:\node_modules\robotjs\bu
ild\robotjs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\MaiBenBen1\AppData\Roaming\n
pm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "D:\\nodejs\\node.exe" "C:\\Users\\MaiBenBen1\\AppData\\Roaming
\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--runtime=electron"
"--target=1.4.1" "--disturl=https://atom.io/download/atom-shell" "--abi=48"
gyp ERR! cwd E:\node_modules\robotjs
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by Deltatiger** [comment]
E:\Workspace\RobotJS\electron-test>node-gyp rebuild --runtime=electron --target=
1.4.0 --disturl=https://atom.io/download/atom-shell --abi=48 --arch=x64

This seems to be working good for me. Compilation shows no errors. 
I am still working on getting it to work with Electron ( no idea how to do it yet. )

**Comment by octalmage** [comment]
I noticed this error: 

```
C:\Users\MaiBenBen1.node-gyp\iojs-1.4.1\Release\iojs.lib : fatal error LNK1106
: invalid file or disk full: cannot seek to 0xF2ADE [E:\node_modules\robotjs\bu
ild\robotjs.vcxproj]
```

Is it possible that your disk is full?

**Comment by NeekSandhu** [comment]
For anyone else having this issue, try  `electron-rebuild`, it takes care of everything for you.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
