### ISSUE TITLE
Can any body send me a copy with electron I can use directly because I can't rebuild because of gfw

### ISSUE THREAD

**Issue by Fing001** [octalmage/robotjs#240]
Because of the government firewall, I can't download certain files needed to rebuild electron. Can any friend send me a copy of already rebuild electron with robotjs can use directly.
I'm using windows 8.1 x64 
my email is : fingfine@foxmail.com

**Comment by octalmage** [comment]
Hi @Fing001, 

Sorry for the delay. Can you download the binary from the releases page? 

https://github.com/octalmage/robotjs/releases/tag/v0.4.4

If not, I can send you an email!

**Comment by jkkongkong** [comment]
Hi @octalmage 
I am a new for robotjs I want to know how to use the binary from the releases page to rebuild electron 
 Can you tell me

**Comment by octalmage** [comment]
You shouldn't have to use the binaries directly, they get installed when installing with NPM. Just: 

```
npm install robotjs
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
