### ISSUE TITLE
Installation bug in Windows 7 sp1 x64, nodejs 7.0.0

### ISSUE THREAD

**Issue by MarkKharkov** [octalmage/robotjs#245]
E:\proj>npm install
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g

> robotjs@0.4.5 install E:\proj\node_modules\robotjs
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v7.0.0 arch=x64 platfor
m=win32)
prebuild WARN install got an error, rolling back install
prebuild ERR! configure error
prebuild ERR! stack Error: read ECONNRESET
prebuild ERR! stack     at exports._errnoException (util.js:1026:11)
prebuild ERR! stack     at TLSWrap.onread (net.js:572:26)
prebuild ERR! not ok
prebuild ERR! build Error: read ECONNRESET
prebuild ERR! build     at exports._errnoException (util.js:1026:11)
prebuild ERR! build     at TLSWrap.onread (net.js:572:26)

## Steps to Reproduce (for bugs)

1. install windows 7 x64
2. install nodejs 7.0.0
3. install Python 2.7
4. try to install robotjs

## Your Environment

* RobotJS version:
* Node.js version:
* npm version:
* Operating System:

**Comment by Deltatiger** [comment]
Seems the binaries for the latest node version are missing. For me since I had the required building tools the files were built and it works.
Should be simple fix by adding the required binaries in the prebuilt.

**Comment by Deltatiger** [comment]
@MarkKharkov The new release of Node goes to abi version 51. The prebuilts only exist till abi version 48. This should be a easy fix. 
@octalmage Could you push the required binaries ?

**Comment by octalmage** [comment]
Yeah I'll get it done!

**Comment by octalmage** [comment]
Prebuild should fall back to building, there are instructions for that here:

https://robotjs.io/docs/building

This should work in the meantime.

**Comment by Deltatiger** [comment]
@octalmage it does. And it compiles good. I think he does not have the required tools to build it. But the error log looks like some kind of connection issue.

**Comment by MarkKharkov** [comment]
"Seems the binaries for the latest node version are missing" - yes, as I understand, prebuild binaries for node 7.0.0 (51) and Win32 are missing.
"Should be simple fix by adding the required binaries in the prebuilt." - yes, I think so.
And yes, on my virtual machine (Win 7 x64) Visual Studio or something else compiler not installed.

**Comment by MarkKharkov** [comment]
"@octalmage But the error log looks like some kind of connection issue." - No, all other packets from package.json three times installed correctly. Exception - robotjs.

**Comment by modulexcite** [comment]
Thank you for an excellent project.
I have a similar issue with the same environment, any update on this?

**Comment by mystrdat** [comment]
Same issue here.

**Comment by octalmage** [comment]
This should be resolved by v0.4.6, please let me know if you still encounter this and we can reopen the issue.
