### ISSUE TITLE
Erro Npm install

### ISSUE THREAD

**Issue by kelvinoenning** [octalmage/robotjs#247]
Error Npm:

> robotjs@0.4.5 install /home/icelizk/Kelvin/node/bot/node_modules/robotjs
> prebuild --install

/usr/bin/env: «node»: Ficheiro ou directoria inexistente
npm WARN bot@1.0.0 No description
npm WARN bot@1.0.0 No repository field.
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "robotjs"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! robotjs@0.4.5 install: `prebuild --install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the robotjs@0.4.5 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/icelizk/Kelvin/node/bot/npm-debug.log

**Comment by Deltatiger** [comment]
@kelvinoenning Could you provide your Node version as well as the OS you are using ?

**Comment by kelvinoenning** [comment]
NodeJs version 4.2.6.
SO: Elementary OS.

In Ubuntu 16.04 version appears to be running normally.
What is the problem?

**Comment by Deltatiger** [comment]
@kelvinoenning Can you check if the node executable is in the PATH ? Also would be helpful if you post your /home/icelizk/Kelvin/node/bot/npm-debug.log

Something Similar : https://github.com/plaidchat/plaidchat/issues/135

**Comment by bernatcanal** [comment]
Installing the nodejs-legacy package fixed it for me:

```
sudo apt-get install nodejs-legacy
npm install robotjs
```

**Comment by octalmage** [comment]
This should be resolved by v0.4.6, please let me know if you still encounter this and we can reopen the issue.
