### ISSUE TITLE
horizontal robot.scrollMouse

### ISSUE THREAD

**Issue by drachehavoc** [octalmage/robotjs#248]
## Expected Behavior
I suggest that the mouseScroll should accept the right and left (horizontal) directions, just as the touchpad does

## Current Behavior
Currently the mouseScroll only accepts the up and down (vertical) directions.

## Possible Solution
...

## Steps to Reproduce (for bugs)
Is not a bug, it's a new feature

## Context
In some situations and screens you need to scroll right and left

## Your Environment

* RobotJS version:
* Node.js version: v6.9.1
* npm version:  3.10.9
* Operating System: Win 10

**Comment by aj-ptw** [comment]
was this closed with `0.4.6`?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
