### ISSUE TITLE
Crash in keycode.c createStringForKey

### ISSUE THREAD

**Issue by CoreyDotCom** [octalmage/robotjs#249]
OSX Sierra, crash occurs in createStringForKey in the following code if the input settings are set to Hirigana... (enable menu icon with System Preferences > Language & Region, then choose Hiragana via the US flag in upper right menu applet):

createStringForKey
![image](https://cloud.githubusercontent.com/assets/701828/20398697/648d7556-acbc-11e6-901d-ea5c8fc68f40.png)

The crashing code in question:

```
        TISInputSourceRef currentKeyboard = TISCopyCurrentKeyboardInputSource();
        CFDataRef layoutData =
                TISGetInputSourceProperty(currentKeyboard,
                                          kTISPropertyUnicodeKeyLayoutData);
        const UCKeyboardLayout *keyboardLayout =
                (const UCKeyboardLayout *)CFDataGetBytePtr(layoutData);
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
