### ISSUE TITLE
Get Screen Dimensions

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [octalmage/robotjs#25]
Having screen dimensions would be great for calculating where on the screen the mouse is or should be.

This could be returned as a new call in `screen` or returned with the object from `getMousePos()` so you would have `x`, `y`, `width`, and `height` parameters.

Another possibility is passing into `getMousePos({percent:true})` and have it return 2 percentages rather than a fixed location `{
  x: 50.44,
  y: 22.34
}`
.

**Comment by octalmage** [comment]
I think I'll create a new method for getting the screen size so it's not slowed down by getting the mouse position. The internal C function `getMainDisplaySize()` does what you want, it will be very easy to expose it to Node.js (with a new name). 

I'll try to get this added tonight!

**Comment by octalmage** [comment]
Sorry, thought I replied to this. I added `getScreenSize`:

```JavaScript
var robot = require("robotjs");

var screen = robot.getScreenSize();

console.log(screen.width + "x" + screen.height);
```
I released RobotJS v0.1.2 with this function, update and let me know how it works!

**Comment by ThisIsJohnBrown** [comment]
Perfect! Thank you, @octalmage!

**Comment by octalmage** [comment]
![](http://media1.giphy.com/media/Vmunw0k7q12Ks/giphy.gif)

**Comment by ozkr0124** [comment]
Good day.

the function to obtain the screen size in macOS does not operate, the result it shows is 0 in width as in height

`var robot = require("robotjs");

// Speed up the mouse.
robot.setMouseDelay(10);

var twoPI = Math.PI * 2.0;
var screenSize = robot.getScreenSize();
console.log(screenSize);
var height = 768;
var width = 1366;

for (var x = 0; x < width; x++) {
    y = height * Math.sin((twoPI * x) / width) + height;
    robot.moveMouse(x, y);
}`

**Comment by data987** [comment]
I've got the same issue! Does somebody know how to solve this?

**Comment by selimgr** [comment]
Same issue... any fixes?

**Comment by stephanbogner** [comment]
If I use NVM to switch to Node `v10.23.1` it works. (I use MacOS Catalina 10.15.7)
So apparently there was a change in NodeJS itself that broke `robot.getScreenSize()` and thus also mouse clicks? 🤔 

**Note:** I didn't investigate at which version it started to break, v10.23.1 was just the one I already had in NVM.
