### ISSUE TITLE
Drag not working on Mac

### ISSUE THREAD

**Issue by AnjaP7** [octalmage/robotjs#250]
I tried to drag in a window to scroll it. But it doesn't seem to do anything.

  robot.mouseToggle('down', 'left');
  robot.dragMouse(100, 100);
  robot.mouseToggle('up', 'left');

## Your Environment
* RobotJS version: 0.4.5
* Operating System: MAC OS

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
