### ISSUE TITLE
Node-gyp rebuild error

### ISSUE THREAD

**Issue by GlennHulscher** [octalmage/robotjs#251]
It should use npm install.
## Steps to Reproduce (for bugs)

1. windows 7 x64
2. node.js V6.9.1 LTS
3. "nmp install" in folder

## Your Environment

* RobotJS version: Just clicked download as zip
* Node.js version: v6.9.1 LTS and v7.0.0 used
* npm version: v3.10.8
* Operating System: windows 7 x64
[npm-debug - Copy.txt](https://github.com/octalmage/robotjs/files/611206/npm-debug.-.Copy.txt)

**Comment by Cyriaqu3** [comment]
Do you have the [required dependencies](https://www.npmjs.com/package/robotjs#building) installed ?

**Comment by octalmage** [comment]
This should be resolved by v0.4.6, please let me know if you still encounter this and we can reopen the issue.
