### ISSUE TITLE
scrollMouseSmooth?

### ISSUE THREAD

**Issue by LeandroFavero** [octalmage/robotjs#254]
## Expected Behavior
I was expecting a very smooth scroll using:
robot.scrollMouse(1, "down");

## Current Behavior
Even just 1 it's too much. I tried float like 
robot.scrollMouse(0.1, "down");
But no success.

How can I do a smooth scroll?

**Comment by aj-ptw** [comment]
Would be very helpful!

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
