### ISSUE TITLE
Remote desktop connection mouse problem

### ISSUE THREAD

**Issue by rodrigopandini** [octalmage/robotjs#258]
Hi @octalmage, thank you for provide the library. Great work!

**TLTR**: When I "focus out" from remote desktop connection window, the server loses the mouse. So, robot.js can not move the mouse in the server.

It's not a robotjs problem, but is when I'm trying to use it on the Windows Server.
I have a web-server running on Windows Server, that receives http requests and based on the data passed, it moves the mouse in the server.
My problem is how to test it using the same computer.
I use a Remote Desktop Conection to access the server and start the web-server project and then I make a request using the browser from my home computer to the web-server to move the mouse in it. 
When using locally in the Server, everything is ok. So, it's not a code problem.

* RobotJS version: 0.4.5
* Node.js version: 7.4.0
* npm version: 4.0.5
* Operating System: Windows Server 2012

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.

**Comment by sebastiaorealino** [comment]
I have same problem here. :/

**Comment by yuvi00001** [comment]
I have the same issue but with keyboard commands like "ctrl+q".
