### ISSUE TITLE
Mouse don't move to extended desktop

### ISSUE THREAD

**Issue by rodrigopandini** [octalmage/robotjs#259]
Mouse don't move to extended desktop on Windows.
It stops in limits of the first screen and don't continue to move over the extended dektop.

Windows: 7, 64bits.
Node: 7
Robot.js: lasted

**Comment by octalmage** [comment]
Multi-monitor support isn't implemented yet, follow #160 for updated.  https://github.com/octalmage/robotjs#faq.
