### ISSUE TITLE
Get cursor icon as bitmap, with ability to save it or get pixels from it.

### ISSUE THREAD

**Issue by casonclagg** [octalmage/robotjs#260]
## Expected Behavior
Get cursor icon as bitmap, with ability to save it or get pixels from it.

## Possible Solution
In Windows w/ C# you can use the following from user32.dll to get the cursor and then draw it to a bitmap

 [DllImport("user32.dll")]
 private static extern bool GetCursorInfo(out CursorInfo pci);

 [DllImport("user32.dll")]
 private static extern bool DrawIcon(IntPtr hDC, int X, int Y, IntPtr hIcon);

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
