### ISSUE TITLE
Robotjs under PM2

### ISSUE THREAD

**Issue by abusedmedia** [octalmage/robotjs#262]
## Expected Behavior
Basic examples should work as specified. I don't know whether it's because Robotjs or PM2 issue. 

## Current Behavior
By running Robotjs under PM2 looks fine (no errors) but the examples don't performe as expected. As an example, trying to log ```getMousePos()``` under PM2 gives ```{ x: 0, y: 0 }``` no matter the real mouse position (running the same with node works as expected). 

## Steps to Reproduce (for bugs)
Just run the official given example under ```pm2 start index.js``` instead using node.

## Your Environment
* RobotJS version: 0.4.5
* Node.js version: 4.1.0
* npm version: 2.14.3
* Operating System: Mac OS X 10.10.5

**Comment by abusedmedia** [comment]
Running a ```robotjs``` script with ```forever``` actually works therefore I'm closing this issue since it might be more related to something about how ```pm2``` handle the child processes.

**Comment by scaret** [comment]
+1
calling moveMouse will move to (0,0)
