### ISSUE TITLE
Feat. Request: getKeys()

### ISSUE THREAD

**Issue by abusedmedia** [octalmage/robotjs#263]
Hi there

Any chances to have something like getMousePos() but for keyboard events. 
Getting the dispatched key or even only the trigger event could be very useful.

Thanks and keep this sw up!

**Comment by xywang68** [comment]
Second this feature request. It would be helpful to get a key's toggle state such as up or down.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.

**Comment by saint739** [comment]
If it possible, add this feature.

**Comment by dhruvramani** [comment]
Yes please. Are there any alternatives to this? Anyone up to forking & modifying the robot.js code w/ me to accomplish this?

@saint739 @abusedmedia @xywang68
