### ISSUE TITLE
Install not working on Windows 10

### ISSUE THREAD

**Issue by ItsNovaHere** [octalmage/robotjs#264]
I went to install robotjs using `npm install robotjs` and it doesn't work.

## Current Behavior

Gives me this : ` robotjs@0.4.5 install C:\Users\Nova\AppData\Roaming\npm\node_modules\robotjs prebuild --install prebuild WARN install No prebuilt binaries found (target=v7.4.0 arch=x64 platform=win32) Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch. C:\Users\Nova\AppData\Roaming\npm\node_modules\robotjs\build\robotjs.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. prebuild ERR! build error prebuild ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1 prebuild ERR! stack     at ChildProcess.onExit (C:\Users\Nova\AppData\Roaming\npm\node_modules\robotjs\node_modules\node-gyp\lib\build.js:276:23) prebuild ERR! stack     at emitTwo (events.js:106:13) prebuild ERR! stack     at ChildProcess.emit (events.js:191:7) prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) prebuild ERR! not ok prebuild ERR! build Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1 prebuild ERR! build     at ChildProcess.onExit (C:\Users\Nova\AppData\Roaming\npm\node_modules\robotjs\node_modules\node-gyp\lib\build.js:276:23) prebuild ERR! build     at emitTwo (events.js:106:13) prebuild ERR! build     at ChildProcess.emit (events.js:191:7) prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\Nova\AppData\Roaming\npm\node_modules\robotjs\node_modules\mkdirp\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\Nova\AppData\Roaming\npm\node_modules\robotjs\node_modules\mkdirp\node_modules' npm WARN   errno: -4048, npm WARN   code: 'EPERM', npm WARN   syscall: 'scandir', npm WARN   path: 'C:\\Users\\Nova\\AppData\\Roaming\\npm\\node_modules\\robotjs\\node_modules\\mkdirp\\node_modules' } npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "robotjs"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! robotjs@0.4.5 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the robotjs@0.4.5 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above. `
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I am trying to install robotjs

## Your Environment

* RobotJS version: N/A
* Node.js version: 7.5.0
* npm version: 4.1.2
* Operating System: Windows 10 64-Bit

**Comment by Deltatiger** [comment]
Missing Prebuilts for Node 7 and up.
Check #253 for updates.

**Comment by octalmage** [comment]
This should be resolved by v0.4.6, please let me know if you still encounter this and we can reopen the issue.
