### ISSUE TITLE
Error: The specified procedure could not be found

### ISSUE THREAD

**Issue by Akronae** [octalmage/robotjs#265]
Hi, i'm trying to make my cursor move with:
`require('robotjs').moveMouse(100, 300);`
And electron throw me an error ! :(

## Expected Behavior
My cursor to move

## Current Behavior
Electron throw me an error

## Steps to Reproduce (for bugs)

1. write `require('robotjs').moveMouse(100, 300);`
2. rebuild
3.  electron ./
4. Enjoy !

## Error
![image](https://cloud.githubusercontent.com/assets/17302866/22743899/e7aaf3d2-ee1b-11e6-902b-a0865aefd21e.png)

## Context
I searched for the same issue, but without result.. :|

## Your Environment

* RobotJS version: lastest
* Node.js version: 7.4.0
* npm version: 4.0.5
* Operating System: Windows 10

**Comment by octalmage** [comment]
This should be resolved by v0.4.6, please let me know if you still encounter this and we can reopen the issue.

**Comment by ThePhantomGamer** [comment]
Hi, i am also having this issue as well, using latest RobotJS version. How can I fix this?
