### ISSUE TITLE
Global hotkeys in other programs don't detect robot.js keypresses when not focused

### ISSUE THREAD

**Issue by Skhmt** [octalmage/robotjs#270]
## Expected Behavior
If OBS Studio or other programs should detect robot.js key presses, even when the window isn't focused.

## Current Behavior
OBS does not detect robot.js key presses when OBS isn't focused.

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
1. Set an OBS global hotkey detect to something
2. Run robot.js, press that hotkey combination via robot.js while node or something is focused

## Context
I'm trying to make a webserver that lets you remote control programs with global hotkeys via that site. Basically you'd load the server on your computer, which is running robot.js and express. Someone logs into the website and taps a http get request or something, which triggers robot.js on the server to press a hotkey combination. Basically it's a hotkey passthrough.

## Your Environment

* RobotJS version: Latest as of this date
* Node.js version: NW.js 0.20.2, combined robot.js for it with nw-gyp. It works in every other way.
* npm version:
* Operating System: Win 10 x64

**Comment by mzmiric5** [comment]
Which version of OBS are you using? I just tested with 0.18 on Win 10 x64, and haven't had this issue

**Comment by Skhmt** [comment]
OBS 0.18 on Win 10 x64. Still doesn't work.

Note, it works if OBS is focused, but not if it isn't focused.

**Comment by mzmiric5** [comment]
Hmm, yeah same OBS version, Win 10 x64, global hotkeys work fine both when OBS window is focused and not focused.

**Comment by Skhmt** [comment]
Hm. What hotkeys did you set and what behavior are you testing?

**Comment by Skhmt** [comment]
Hm. What hotkeys did you set and what behavior are you testing? 

Also to alleviate possible confusion, using my keyboard does trigger OBS global hotkeys when it's not focused, but using robotjs to tap those same keys does not when OBS isn't focused.

**Comment by mzmiric5** [comment]
So I tried a number of different hotkeys, the ones I just tested now to confirm:
1) Ctrl + 1 and Ctrl + 2 to switch to scene 1 and switch to scene 2
2) Alt + 1 and Alt + 2
3) Shift + Ctrl + 1 and Shift + Ctrl + 2

All 3 worked just fine both with focus and without focus on the OBS window (I focused my app that I'm using to control OBS, I focused my browser, powershell, etc...).

Interestingly enough, I'm having a fairly similar problem to yours when trying to achieve the same functionality with OBS on OSX.

**Comment by Skhmt** [comment]
I was trying numpad_x and control, alt, and control + alt. I'll try normal numbers when I get home later today.

**Comment by Skhmt** [comment]
Nope, still doesn't work when OBS isn't focused.

**Comment by mzmiric5** [comment]
Interesting... I got all of the above working. How are you actually sending these keys? keyTap/keyToggle with modifiers or each key separately? also what is your keyboard delay setting?

**Comment by Skhmt** [comment]
robot.keyTap('1', ['alt', ...])

Is keyboard delay something that has to be set?

**Comment by mzmiric5** [comment]
Well it is set to 10ms by default, and I've found it that OBS has issues with this. I just run `robot.setKeyboardDelay(50)` and that gives me the best results

I've had varying results keyTap, so if the delay doesn't fix it, try something like
```javascript
robot.keyToggle('1','down',['alt',...]):
robot.keyToggle('1','up',['alt',...]);
```

I've also seen others send modifiers as individual keys using toggle, but I prefer using the modifiers. However give that a try if nothing else works out.

**Comment by Skhmt** [comment]
Changing the keyboard delay lets it work sometimes. It's very inconsistent now. Using keytoggle didn't seem to change anything

**Comment by aycgit** [comment]
problem still persists, keytoggle also does not seem to work anymore.

**Comment by mpopp** [comment]
Problem is still present. Tried `robot.keyTap('1', 'control').`
It worked once, when I also set a keyboard delay of 500 ms.. but then on the next script run it didn't anymore.

However, what I found to work consistently right now under Windows is:

```
robot.setKeyboardDelay(50);
robot.keyToggle('1', 'down');
robot.keyToggle('control', 'down');
robot.keyToggle('1', 'up');
robot.keyToggle('control', 'up');
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
