### ISSUE TITLE
Automating a telnet application - Question

### ISSUE THREAD

**Issue by shibukraj** [octalmage/robotjs#274]
First of all thanks for such a great library and we are getting used to the multiple benefits of it. We are trying to automate a Terminal Application which is accessed via Telnet / ssh. Wondering whether any one has any examples of doing the same. The telnet server is created using telnet2 npm and the Terminal UI is build using blessed.js framework.

Thanks

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
