### ISSUE TITLE
moveMouse does not work in virtualbox

### ISSUE THREAD

**Issue by purely-smile** [octalmage/robotjs#278]
when I use robotJs in  win7 system with virtualbox.  I find that the moveMouse dose not move in fact. 
But when I log the position get the value I set.

## Expected Behavior
I want use It move somewhere I want and click something.

## Current Behavior
But It dose not work

## Possible Solution
my real system is ubnutu 16.04, and it work fine.
same issues for win10 also with virtualbox;

I think It is about virtualbox environment and can not find any issues about virtualbox and the right solution.
## Steps to Reproduce (for bugs)
```js
const robot = require("robotjs");
robot.moveMouse(80, 230);
robot.mouseClick();
console.log(robot.getMousePos());  // {x:80,y:230}
```

## Your Environment

* RobotJS version:0.4.7
* Node.js version:6.10.1
* npm version:3.10.10
* Operating System:win 7

**Comment by Camron** [comment]
Does getPixelColor work for you? It appears to be failing for me on Virtualbox along with the same moveMouse problem you have.

**Comment by purely-smile** [comment]
@Camron  getPixelColor method work fine for me .

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
