### ISSUE TITLE
Building for Electron on Linux

### ISSUE THREAD

**Issue by LoganArnett** [octalmage/robotjs#279]
I am currently trying to include Robotjs in an electron app and have been successful getting it to work with my dev environment on Mac. However when I package my app for Linux I get the following error:

`Cannot Open robotjs.node ... Error: robotjs.node cannot open shared object file: No such file or directory`

Not sure if this is a robotjs, electron, or webpack issue

## Expected Behavior
Builds and runs like it does in development on Mac

## Current Behavior
Fails

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 7.7.1
* npm version: 4.1.2
* Operating System: MacOS Sierra 10.12 (Packaging for Ubuntu 16.04)

**Comment by LoganArnett** [comment]
I have now confirmed that I can build and run the app with robotjs on mac with electron but still having the above error on linux

**Comment by octalmage** [comment]
Hi Logan, we only have prebuilt binaries up for 64bit versions of Linux. If you're using a 32bit OS, you'll need to build RobotJS manually. The instructions for this can be found here: 

https://github.com/octalmage/robotjs#building

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
