### ISSUE TITLE
How to capture keyboard events?

### ISSUE THREAD

**Issue by bjrmatos** [octalmage/robotjs#28]
Hello, It is possible to receive the key that was pressed when typing? something like onkeypress event in the browser.

My use case would be implement a keylogger :)

**Comment by octalmage** [comment]
Unfortunately this is not possibly with RobotJS currently, RobotJS is for sending events! 

![](http://media4.giphy.com/media/kS2qLKwGk3MXe/giphy.gif)

**Comment by DirkHeinke** [comment]
This would also allow to build a tool for expanding text snippets, which currently e.g. [autokey](https://code.google.com/p/autokey/) can do. 

Is a event/keyboard capturing planned for later or is it out of the scope of this project?

**Comment by octalmage** [comment]
See #55, I don't think I want to include this in RobotJS but I am interested in developing it since Node.js is missing a good solution.

**Comment by DirkHeinke** [comment]
Alright, sorry, I have somehow overseen that discussion. More modules makes sense to me. Good luck with it :)

**Comment by octalmage** [comment]
No worries! At least you found this one. :p

Thanks!
