### ISSUE TITLE
Requested coordinates are outside the main screen's dimensions

### ISSUE THREAD

**Issue by jam3sn** [octalmage/robotjs#280]
## Expected Behavior

`var mouse = robot.getMousePos();
        var color = '#'+robot.getPixelColor(mouse.x, mouse.y);`

Should return the color at the mouse position.

## Current Behavior

Returns the following error when clicking on the secondary monitor
`Uncaught Error: Requested coordinates are outside the main screen's dimensions.`

## Possible Solution

Not too sure, I see you have fixed other multi-screen issues, this too would be highly beneficial if fixed as I'd like to use this as a color picker on my app.

## Steps to Reproduce (for bugs)

1. Use `var mouse = robot.getMousePos();
        var color = '#'+robot.getPixelColor(mouse.x, mouse.y);`
2. Trigger it on a secondary screen

## Context

I've built a color palette tool and wish add a color picker to it, your library allows me to easily achieve this!
https://github.com/jam3sn/ClickPalette

## Your Environment

* RobotJS version: 0.4.7
* Node.js version:  6.9.2
* npm version: 3.10.9
* Operating System: Windows 10

**Comment by jareddgotte** [comment]
This is an old issue, but it was the first one I found as I was searching for a solution to the same problem. Refer to issue #88 for any updates.

**Comment by Louis-7** [comment]
The link http://clickpalette.com/ is NSFW. Please remove it.

**Comment by jam3sn** [comment]
@Louis-7 This is an old issue, opened over 2 years ago. Since then I've discontinued ClickPalette, therefore the domain has expired and so I'm no longer in ownership of it. I've removed the link above and will be closing the issue.

**Comment by Louis-7** [comment]
Thanks.

**Comment by jonschlinkert** [comment]
I'm still experiencing this issue. I'm not sure why it was closed since it wasn't resolved.

**Comment by Louis-7** [comment]
@jonschlinkert have you been checked this link -> https://github.com/octalmage/robotjs/issues/88?

**Comment by brandonros** [comment]
I have this error on single monitor (MacBook Pro).

![image](https://user-images.githubusercontent.com/8949910/74304775-feae7500-4d2b-11ea-9aa1-1b28bfc110a5.png)
