### ISSUE TITLE
KeyTap/KeyToggle/typeString doesn't work

### ISSUE THREAD

**Issue by IlyaKronos** [octalmage/robotjs#281]
## Expected Behavior
robot.typeString("Hello World!") doing only " !"
Letters doesn't pressed
The same situation with robot.keyTap(), robot.keyToggle(). Only symbols/numbers/system keys (shift, control, enter) works

## Environment

* RobotJS version: latest
* Node.js version: 6.10.1
* Operating System: Windows

**Comment by xzebra** [comment]
Same thing happening in windows (and sometimes it doesn't even type the "!").

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
