### ISSUE TITLE
How to execute code synchronously?

### ISSUE THREAD

**Issue by Hum4n01d** [octalmage/robotjs#282]
How can I execute a series of commands knowing that they’ll run in order and not until the previous ends?

**Comment by SidneyNemzer** [comment]
All the functions in RobotJS appear to be synchronous, assuming the documentation is up to date.

Is there something in-particular you wanted to make synchronous?

**Comment by Hum4n01d** [comment]
Well I want to run x command and wait for it to finish before running y command

**Comment by SidneyNemzer** [comment]
If you post some code, I can help you refactor it.

I'm not really sure how this relates to RobotJS though, since it looks like all the RobotJS functions are synchronous

**Comment by Hum4n01d** [comment]
Here is my code: 

```
const robot = require('robotjs')

const screen = robot.getScreenSize()

const DIMENSIONS = {
  width: screen.width-1,
  height: screen.height-1
}

const CONTROLS_HEIGHT = 88
const CONTROLS_TOP = DIMENSIONS.height - CONTROLS_HEIGHT

// Switch apps to Spotify with CMD-TAB
robot.keyTap('tab', 'command')
robot.keyTap('enter')

// Move to spot on album art
robot.moveMouse(10, CONTROLS_TOP-1)
robot.mouseClick('right')```

The right click never happens

**Comment by SidneyNemzer** [comment]
Looks like that should work. So it's time to do some debugging.

You could try adding a delay to the mouse click:

```
robot.moveMouse(10, CONTROLS_TOP - 1)

setTimeout(function () {
  robot.mouseClick('right')
}, 1000)
```

You could also add a debug message:

```
robot.moveMouse(10, CONTROLS_TOP - 1)

var mousePosition = robot.getMousePos();
console.log("Mouse is at x:" + mousePosition.x + " y:" + mousePosition.y);

robot.mouseClick('right')
```
