### ISSUE TITLE
how to save the bitmap (capture.screen) to an image

### ISSUE THREAD

**Issue by jkkongkong** [octalmage/robotjs#283]
I use robotjs to capture screen  it returns a bitmap object ,I want to know how to save it as an image so that I can show it in html,I am a new   showing me a example is better thanks in advanced

**Comment by developer239** [comment]
#222

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
