### ISSUE TITLE
typeString on Linux types "1" for "!"

### ISSUE THREAD

**Issue by grassick** [octalmage/robotjs#284]
## Expected Behavior
I expected typeString to type "!", not "1"

## Current Behavior
typeString("hello!") types "hello1" in Ubuntu 16

## Steps to Reproduce (for bugs)
1. `robot.typeString("hello!")`
2. See what is typed

## Context
Trying to use for a voice dictation system using Google Cloud Speech

## Your Environment
* RobotJS version: 0.4.7
* Node.js version: 6.10.1
* npm version: 3.10.10
* Operating System: Linux Mint 18

**Comment by marcopin** [comment]
Same behavior for latin keyboard where "@" is typed using "Alt-Gr + 2". No modifier for "Alt-Gr"

**Comment by xywang68** [comment]
I have seen similar issue. Workaround is typeStringDelayed(string, cpm) where cpm is set to 2400.

**Comment by xywang68** [comment]
Have seen the same issue. shifted char are not shifted in typeString() call.
https://github.com/octalmage/robotjs/issues/345

**Comment by UrielCh** [comment]
for arobase '@' not working for me on linux.
* Xvnc4 X11 server.
* RobotJS version: 0.5.1
* nodejs v8.12.0
* Operating System:  Ubuntu 18.04.1 LTS

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
