### ISSUE TITLE
typeString and keyTap write semicolon(;) for colon(:) on Ubuntu(vbox)

### ISSUE THREAD

**Issue by EdSaleh** [octalmage/robotjs#285]
typeString and keyTap write semicolon(;) for colon(:) on Ubuntu(vbox)

**Comment by srokatonie** [comment]
Same here on Raspberry Pi 3 (Raspbian Jessie)

**Comment by DanielJPetersen** [comment]
Same here on Linux Mint 18.2 (not running in a virtual machine)

**Comment by redparagon** [comment]
Same issue

**Comment by aas395** [comment]
Same issue on Ubuntu 16.04 LTS, works as intended on my Mac. I need this for a product demo in a few days -- is there anything I can do to help resolve this more quickly?

**Comment by arrraichu** [comment]
Very late here, but I ran into this issue recently and solved it with the following snippet of code:

```javascript
const MATCH_REGEX = /[~!@#\$%\^&*()_+{}|:"<>?]/;
let str = 'test string ~!@#$%^&*()_+{}:"<>?';

// minimize delay between robot keyboard calls
robot.setKeyboardDelay(1);

while (str) {
   let match = str.match(MATCH_REGEX);

   if (match) {
      robot.typeString(str.substr(0, match['index']));
      robot.keyTap(match[0], ['shift']);
      str = str.substr(match['index']+1);
   }
   else {
      robot.typeString(str);
      str = null;
   }
}

```

Not a perfect or even a great solution, but this will do for now...

**Comment by zoutepopcorn** [comment]
When I write the output of the vars:
https://github.com/octalmage/robotjs/blob/e99b961a1f20c32dc8d1b6e7647f90d555422426/src/keypress.c#L243

Output logging from 
```
String: Test@2test
c: T, 84, 0x24  >> n: 36 
c: e, 101, 0x35  >> n: 53 
c: s, 115, 0x43  >> n: 67 
c: t, 116, 0x44  >> n: 68 
c: @, 64, 0x10  >> n: 16 
c: 2, 50, 0x2  >> n: 2 
c: t, 116, 0x44  >> n: 68 
c: e, 101, 0x35  >> n: 53 
c: s, 115, 0x43  >> n: 67 
c: t, 116, 0x44  >> n: 68 
```

Now it will call ```toggleUniKey()```
https://github.com/octalmage/robotjs/blob/e99b961a1f20c32dc8d1b6e7647f90d555422426/src/keypress.c#L234

When we call: ```toggleKey(c, down, true)``` all special chars like '@' will be there.. So we have to filter the special chars and set the boolean from toggleKey

**Comment by reactor01** [comment]
> Very late here, but I ran into this issue recently and solved it with the following snippet of code:
> 
> ```js
> const MATCH_REGEX = /[~!@#\$%\^&*()_+{}|:"<>?]/;
> let str = 'test string ~!@#$%^&*()_+{}:"<>?';
> 
> // minimize delay between robot keyboard calls
> robot.setKeyboardDelay(1);
> 
> while (str) {
>    let match = str.match(MATCH_REGEX);
> 
>    if (match) {
>       robot.typeString(str.substr(0, match['index']));
>       robot.keyTap(match[0], ['shift']);
>       str = str.substr(match['index']+1);
>    }
>    else {
>       robot.typeString(str);
>       str = null;
>    }
> }
> ```
> 
> Not a perfect or even a great solution, but this will do for now...

Thanks for the code for me is working great just put typeStringDelayed because my ubuntu missed the chars

**Comment by oktapodia** [comment]
Thank you, looks like it has been solved :)
