### ISSUE TITLE
setting timeout after keytap causes cmd+o to trigger

### ISSUE THREAD

**Issue by fabulousduck** [octalmage/robotjs#287]
## Expected Behavior

when i use keytap, and after that i set a timeout, the timeout should not affect the functionalities of robotjs

## Current Behavior

when i use keytap, it takes time for the command to fully execute, therefore i use a `setTimeout` to wait for x amount of seconds for it to finish. after that, i execute `robot.typeString`.
but before it does that it for some reason also emulates command+o.

## Steps to Reproduce (for bugs)

1.open a browser and focus it
2.have robotjs open the Javascript console (command+f1) for me.
3.set a timeout of 2000ms
4.execute `robot.typeString` when the timeout is over
5. i expected the typestring to be executed in the console
6. instead it first executes `command+o` and then proceeds to interpret the typeStrings string as literal key input

## Context

i am trying to build a scraper for a website that blocks data through requests, so i have to open a browser, then open the console and insert a script that sends the scraped data back to my endpoint.

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: v4.4.7
* npm version: 3.10.6
* Operating System: MAC OSX SIERRA 10.12.4

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
