### ISSUE TITLE
Socket with robots and electronjs

### ISSUE THREAD

**Issue by iswami28** [octalmage/robotjs#288]
I want build an application that capture realtime mouse click and keyboard keypress from admin application​ and  emit data to node.js server (Google cloud server for handling traffic) than node.js server broadcast that whole data to clients to automate client's mouse and keyboard.

My expectations is electron app is run on background on both client and admin And sands mouse and keyboard data real tine.
I am new to this platform please tell me this is possible with this.
* RobotJS 
* Node.js 
* Electronjs
*Express
* Operating System:win server2016

Thank you

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.

**Comment by Fashad-Ahmed** [comment]
I have the same query, kindly reopen or @iswami28 can you please share what you have done back then(insights).
