### ISSUE TITLE
Calling scrollMouse in electron main thread causes thread to hang

### ISSUE THREAD

**Issue by andrewjaykeller** [octalmage/robotjs#289]
## Expected Behavior
Expect to be able to asynchronously call `scrollMouse` and continue to parse the serial port in the same thread.

## Current Behavior
Calling `scrollMouse` causes the main program to temporarily halt and therefore stops the serial port from being read and therefore results in a fatal loss of information. 

## Possible Solution
Web workers? Move to another thread? 
Another thought is that i am totally missing something here, because [the source code](https://github.com/octalmage/robotjs/blob/master/src/mouse.h#L93) says to use `void scrollMouse(int x, int y);` but this results in an error and the only call that works is `robot.scrollMouse(int magnitude, string direction)`.

## Steps to Reproduce (for bugs)
1. Parse 66bytes of information from the serial port every 8ms
2. Randomly call `scrollMouse`
`robot.scrollMouse(10, 'down')`
(i'm thinking i may be able to write a script to mimic this but havent figured out how to yet.)

## Context
Data coming in over the serial port eventually leads to a particular call using this library. However if the serial port goes down because i am calling this library, well... that's a breaking effect in the app :( 

## Your Environment
* RobotJS version: `0.4.5`
* Node.js version: `6.9.5`
* Electron version: `1.4.16`
* npm version: `3.10.10`
* Operating System: Mac `10.12.3`

**Comment by aj-ptw** [comment]
Typescript is wrong https://github.com/octalmage/robotjs/blob/master/index.d.ts#L26

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
