### ISSUE TITLE
Async getPixelColor

### ISSUE THREAD

**Issue by drtkn** [octalmage/robotjs#299]
Is there a way to asynchronously get values of the pixel color vs. polling for the pixel color?

From the examples below:
```// Get pixel color in hex format.
var hex = robot.getPixelColor(mouse.x, mouse.y);
```

Thank you.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
