### ISSUE TITLE
On Keyboard Event typeString there is no option for backspace and enter events.

### ISSUE THREAD

**Issue by plasmashadow** [octalmage/robotjs#3]
it would be better if you have keyboard enter and backspace events

**Comment by octalmage** [comment]
I personally imagined those keys would be accessible using keyTap, typeString is meant for words. 

What did you have in mind?

**Comment by octalmage** [comment]
keyTap now accepts backspace and enter, like: 

```JavaScript
var robot = require("robotjs");

robot.keyTap("up");
robot.keyTap("backspace");
```

**Comment by plasmashadow** [comment]
adding backspace is nice...same way i believe there should be an option for enter .correct me if i am wrong.

**Comment by octalmage** [comment]
You're correct and I did add enter also! I'll get the wiki updated.
