### ISSUE TITLE
Electron build failed in Linux (robotjs 0.4.7 failed in travis)

### ISSUE THREAD

**Issue by fyhao** [octalmage/robotjs#300]
## Expected Behavior
Successfully built Electron

## Current Behavior
Travis build failed as:
Travis error: https://travis-ci.org/fyhao/electron-wf/jobs/239000922
`
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory `/home/travis/build/fyhao/electron-wf/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v8.0.0/bin/node" "/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/fyhao/electron-wf/node_modules/robotjs
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp0m ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-06-03T04_40_58_770Z-debug.log
The command "eval npm install  " failed 3 times.
The command "npm install " failed and exited with 1 during .
Your build has been stopped.
`

## Possible Solution
NA

## Steps to Reproduce (for bugs)

1. Clone https://github.com/fyhao/electron-wf 
2. Build via Travis

## Context
Trying to build my Electron apps, it still worked last weeks in Travis and Appveyor, it started to fail building Electron apparently loading robotjs and got error.

## Your Environment
* RobotJS version: 0.4.7
* Node.js version: 8.0.0
* npm version: 5.0.0
* Operating System:Linux Version
3.13.0-29-generic

Reference links:
Issue created in Electron: https://github.com/electron/electron/issues/9658
Travis logs: https://travis-ci.org/fyhao/electron-wf/jobs/239000922

**Comment by GayatriL** [comment]
Hi fyhao,

Please follow these steps to run your Electron app with RobotJS on Linux.
1) Install following on your machine 
	⁃	NPM version 3.10.10
	⁃	Nodejs version 6.11.0
	⁃	Python version 2.7

(2) Create .npmrc file in your app's folder ( which contains package.json ). Its not visible on linux machine as it starts with ‘.’.
.npmrc file should contains these settings:
	•	runtime = electron
	•	target = 1.6.1
	•	arch = x64
	•	target_arch = x64
	•	disturl = https://atom.io/download/electron
	•	build_from_source = true

(3) Follow these steps to run code on your machine 
	⁃	Goto folder app folder which contains package.json.
	⁃	Run command ’npm install’
	⁃	Run command ’npm start’

(3) Follow these steps to get executable on your machine
	⁃	Install Electron packager using: npm install electron-packager -g
	⁃	Run packaging command: electron-packager . --overwrite --platform=linux --arch=x64 --icon=assets/icons/png/1024x1024.png --prune=true --out=release-builds

(5) Links for reference
	•	https://stackoverflow.com/questions/9023672/how-do-i-resolve-cannot-find-module-error-using-node-js 
	•	https://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron 
	•	https://www.christianengvall.se/electron-packager-tutorial/ 
	•	https://github.com/nodejs/node-gyp

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
