### ISSUE TITLE
scrollMouse X and Y inverted in documentation

### ISSUE THREAD

**Issue by Malpp** [octalmage/robotjs#303]
When I call:
`robot.scrollMove(0,50)`

It will not scroll up and down

## Expected Behavior

According to the [documentation](http://robotjs.io/docs/syntax#scrollmousex-y), the second parameter should be for 

> direction of the scroll up and down

## Current Behavior

The scroll directions are inverted in the function documentation

## Possible Solution

Fix the documentation to show the proper scroll ways.

## Context

I was trying to make the page scroll down, but it wasn't scrolling. So I tried the example in the documentation and figured that the documentation is inverted.

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: v6.11.0
* npm version: 3.10.10
* Operating System: Windows 7 Pro

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.

**Comment by danielehrhardt** [comment]
Same Issue here. Only for Windows 10.
