### ISSUE TITLE
moveMouse don't work on Fedora 25

### ISSUE THREAD

**Issue by AlexeySemigradsky** [octalmage/robotjs#304]
I just run demo (sine.js) and cursor doesn't move. 

## Your Environment

* RobotJS version: ^0.4.7
* Node.js version: v6.11.0
* npm version: 3.10.10
* Operating System: Fedora 25 (linux)

**Comment by aleki** [comment]
PS Fedora 25 is running under wayland by default, but xorg session works fine.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
