### ISSUE TITLE
N-API support for Node.js 8

### ISSUE THREAD

**Issue by vshymanskyy** [octalmage/robotjs#308]
Are there any plans to support N-API? I think it can drastically simplify binary packages deployment and management ;)

**Comment by vshymanskyy** [comment]
https://medium.com/the-node-js-collection/n-api-next-generation-node-js-apis-for-native-modules-169af5235b06

**Comment by Adoroam** [comment]
I would like to second this. I think it would solve a lot of open issues and allow people to use the most current version of node.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
