### ISSUE TITLE
How to open a desktop application by application name as a parameter.

### ISSUE THREAD

**Issue by akshatksingh** [octalmage/robotjs#309]
I want to open a desktop application lets assume Notepad. I dont have the process id. How do i open the Application by application name?

**Comment by Tymski** [comment]
You can use child_process node module for that.
const { exec } = require('child_process');
exec('start notepad');

**Comment by afilp** [comment]
What if the application is already open?
How can we get the focus there?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
