### ISSUE TITLE
Can't use a function of robotjs

### ISSUE THREAD

**Issue by TheRolfFR** [octalmage/robotjs#310]
I saw in the source in robotjs.cc the function CheckMouseButton that can check mouse buttons

## Expected Behavior
I need this function to know if a button is pressed in the OS window for my Electron app.

## Current Behavior
The result is that it gives me an error, he can't even load robotjs :
`App threw an error during load
Error: Cannot find module './build/Release/robotjs.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\florence\AppData\Roaming\npm\n
ode_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:3
5:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\florence\node_modules\robotjs\index.js:1:170
)
    at Object.<anonymous> (C:\Users\florence\node_modules\robotjs\index.js:38:3)

    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)`

Can you help me to solve these problems ?
Is this function available in the module or is it an internal function ?

## Possible Solution
Can we export this function or create another to know the button pressed

## Your Environment
* RobotJS version: 0.4.7
* Node.js version: 6.10.3
* npm version: 3.10.10
* Operating System: Windows 7 SP1

**Comment by Wizek** [comment]
I'm also having the problem with `Cannot find module './build/Release/robotjs.node'`

Any news on this @TheRolfFR or @octalmage?

- `node --version`: v10.15.3
- `npm --version`: 6.11.1
- robotjs version: 0.5.1

**Comment by Wizek** [comment]
Update: I seem to have had success with 

```
npm install -g windows-build-tools
cd .\node_modules\robotjs\
node-gyp rebuild
```

I will now check to see if it was indeed fully successful.

**Comment by oktapodia** [comment]
Thank you for your comment, looks like it has been solved :)

**Comment by gtp-m3** [comment]
it is not working for lunix

error
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for windows-build-tools@5.2.2: wanted {"os":"win32"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lenovo/.npm/_logs/2021-04-06T09_49_28_538Z-debug.log
help plz
