### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by nuongwx** [octalmage/robotjs#311]
seems the link https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-win32-ia32.tar.gz is doesn't work anymore, any fixes or new upgade ??

This is what happend whenever i try to install it using npm install robotjs : (i think my python is ok)
C:\WINDOWS\system32>npm install robotjs

> robotjs@0.4.7 install C:\WINDOWS\system32\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.0
prebuild-install info looking for local prebuild @ prebuilds\robotjs-v0.4.7-node-v57-win32-ia32.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\monde\AppData\Roaming\npm-cache\_prebuilds\https-github.com-octalmage-robotjs-releases-download-v0.4.7-robotjs-v0.4.7-node-v57-win32-ia32.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-win32-ia32.tar.gz
prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-win32-ia32.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.1.4 runtime=node arch=ia32 platform=win32)

C:\WINDOWS\system32\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\monde\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\robotjs
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\monde\AppData\Roaming\npm-cache\_logs\2017-07-16T09_01_39_565Z-debug.log

**Comment by majoressense** [comment]
same problem

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
