### ISSUE TITLE
The Example High-Res Screen Detection Code Does Not Work

### ISSUE THREAD

**Issue by Mega-Mewthree** [octalmage/robotjs#312]
## Expected Behavior
On my high-res screen laptop, the code should return 2. (My laptop is 3200 x 1800, and robot.getScreenSize() returns 1600 x 900.)

## Current Behavior
It returns 1 instead.

## Steps to Reproduce (for bugs)

1. Go on a Windows 8 computer with a high-res display. (The screen resolution is 2 times robot.getScreenSize().)
2. Run the example in http://robotjs.io/docs/syntax#screencapturex-y-width-height.

## Context
This issue causes all my robot.getPixelColor(x, y) calls to be at (x/2) and (y/2). I cannot fix this by multiplying the arguments by 2 since it results in "Error: Requested coordinates are outside the main screen's dimensions."

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 7.10.0
* npm version: 4.2.0
* Operating System: Windows 8 x64
* Screen Resolution: 3200 x 1800

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
