### ISSUE TITLE
getPixelColor(x, y) always returns 000000 on Linux VM

### ISSUE THREAD

**Issue by MichielP1807** [octalmage/robotjs#313]
The function getPixelColor(x, y) always returns 000000 on my Linux VM, similar to the bug fixed in #43 for windows.
## Expected Behavior

getPixelColor(x, y) should be returning the actual color of the screen, even when in a VM.

## Current Behavior

Currently getPixelColor(x, y) is returning 000000 in my Linux VM

## Possible Solution

Perhaps something similar as the solution from #43, I'm not entirely sure how this stuff works. 

## Steps to Reproduce (for bugs)

1. console.log(robot.getPixelColor(x, y)) will always log 000000 in my Linux VM

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: v7.10.0
* npm version: 5.3.0
* Operating System: Linux Mint 18.2 in VirtualBox 5.1.12

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
