### ISSUE TITLE
azerty not handled

### ISSUE THREAD

**Issue by rom1504** [octalmage/robotjs#314]
## Expected Behavior

robot.typeString("localhost")
should write localhost

## Current Behavior

it writes locqlhost

## Possible Solution

is the keyboard layout correctly handled ?

## Steps to Reproduce (for bugs)

1. set your keyboard layout to azerty
2. run robot.typeString("localhost")
3. read locqlhost

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 8.1.2
* npm version: 5.0.3
* Operating System: ubuntu 16.04

**Comment by rom1504** [comment]
For some unknown reason, if I do 
```js
robot.keyToggle("backspace","down");
robot.keyToggle("backspace","up");
```
before the typeString, then it works as expected.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
