### ISSUE TITLE
robotjs on ssh X forwarding

### ISSUE THREAD

**Issue by rom1504** [octalmage/robotjs#315]
using robotjs on ssh X forwarding doesn't seem to work

## Expected Behavior

robot.moveMouse(50,50) should move the mouse

## Current Behavior

robot.moveMouse(50,50) doesn't move the mouse

## Possible Solution

There's no "root display" or screen in this mode, is it handled correctly by https://github.com/octalmage/robotjs/blob/master/src/xdisplay.c#L10 ?

## Steps to Reproduce (for bugs)

1. run some app in ssh forwarding (ssh -X someapp)
2. node someRobotjsScript.js using for example ssh -X konsole
3. robotjs doesn't seem to work

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 8.1.2
* npm version: 5.0.3
* Operating System: ubuntu 16.04

**Comment by tms1337** [comment]
Try setting DISPLAY env var.

First step: check the value of DISPLAY at the computer you're sshing **into**. You can do this by issuing command
`echo $DISPLAY`

Second step: You should get something like DISPLAY=:0 or such as an output of the previous step. Now just set DISPLAY env var for the computer you're sshing **from** by issuing 
`export DISPLAY=:0` (or whatever value you got)

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
