### ISSUE TITLE
Using electron-builder and robotjs for windows ia32 fails

### ISSUE THREAD

**Issue by GuskiS** [octalmage/robotjs#317]
## Expected Behavior
Trying to build electron app but it fails for windows ia32

## Current Behavior
It returns this error: https://gist.github.com/GuskiS/ec93e2bb8bb16bc94599939e068388b3

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 7.9.0
* npm version: 4.2.0
* Electron version: 1.7.5
* Operating System: Ubuntu 16.04

**Comment by blackwire** [comment]
It won't build for windows on ubuntu without wine as far as I know. And even with wine installed you would need to rebuild robotjs with "npm rebuild --runtime=electron --target=1.7.5 --disturl=https://atom.io/download/atom-shell --abi=51" in your case to ensure the right behavior during build. Hopefully some of this helps. If not or you've already done all this ~ sorry about that. I was just running into issues with building on MacOS and found this information out so I thought it might be useful.

**Comment by blackwire** [comment]
After running into this same issue when trying to compile on windows I found this:
npm install --global windows-build-tools

This toolset allowed me to compile without issues. Hopefully it helps you.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
