### ISSUE TITLE
scrollMouse does not work

### ISSUE THREAD

**Issue by GuskiS** [octalmage/robotjs#318]
scrollMouse doesn't seem to be working when `y` is specified
## Expected Behavior

I would expect it to scroll focused window vertically.
## Current Behavior

On Ubuntu 16.04 it crashes:
```
/path/node_modules/electron/dist/electron .: symbol lookup error:
/path/node_modules/robotjs/build/Release/robotjs.node: undefined symbol: YTestFakeButtonEvent
error Command failed with exit code 127.
error Command failed with exit code 1.
```
On Windows 10 nothing happen.

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 7.9.0
* npm version: 4.2.0
* Operating System: ubuntu and windows

**Comment by GuskiS** [comment]
Updated description - crash happens only when `y` is specified:
`robot.scrollMouse(10, 0)` - works
`robot.scrollMouse(0, 10)` - crash
`robot.scrollMouse(10, 10)` - crash

**Comment by roy2651** [comment]
@GuskiS you can try this code：
var robot = require("robotjs");

setTimeout(function()
{
    robot.scrollMouse(-14,'down');
}, 2000);

**Comment by GuskiS** [comment]
@roy2651 I found this PR - https://github.com/octalmage/robotjs/pull/306
That should fix the issue, I think.

**Comment by scottrippey** [comment]
@roy2651 I tried that code (after all, the `index.d.ts` labels the params as `magnitude` and `direction`) -- however, that didn't work.  Looking at `mouse.c`, it's pretty obvious the args are `x` and `y`.
I manually applied the changes in #306, and that _did_ work!  So hopefully we can get that merged soon.

**Comment by SamuraiJack** [comment]
Bump

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.

**Comment by danielehrhardt** [comment]
Same Issue here. Only for Windows 10.

**Comment by akanshSirohi** [comment]
Same Mouse Scroll Issue With Windows 10.

**Comment by akanshSirohi** [comment]
I found the partial solution for this and I posted it here #663
