### ISSUE TITLE
Electron (Atom-shell) compatibility break

### ISSUE THREAD

**Issue by hugohil** [octalmage/robotjs#32]
Hi :)

I want to use your library with [`electron`](http://electron.atom.io) but I can't get it to work. All I get when I launch my program is:
```
[3412:0627/165819:INFO:CONSOLE(98)] "Uncaught Error: Module version mismatch. Expected 44, got 14.
Error: Module version mismatch. Expected 44, got 14.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/perso/Sources/js/hugo/soixantesouris/node_modules/robotjs/index.js:1:80)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)", source: /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js (98)
```

I'm running this on Mac OS 10.10.3, with node `0.12.4`. I tested the lib with a simple script (i.e not with `electron`) and it worked perfectly. I also tried to build [screencat](https://github.com/maxogden/screencat) (a program which uses `electron` along with `robotjs`) on my computer and I get the same error, so it seems that it is related with `electron` itself.

Do you have any idea ? @maxogden maybe ?

**Comment by hugohil** [comment]
I just tested with `nvm` and with `0.10.39`, as well as with `0.10.31`, I get a different error:
```Error: Module did not self-register.```

**Comment by Nedomas** [comment]
It's because electron does not use standard node. Check out how you can rebuild the modules http://electron.atom.io/docs/v0.28.0/tutorial/using-native-node-modules/

I am having a similar problem with ``robotjs``. It is working perfectly when I run it with ``electron app_dir``, but when I package it and run as an app, ``robotjs`` just does not execute commands anymore. No errors, nothing. Where should I debug?

**Comment by Nedomas** [comment]
@hugohil any luck figuring it out? :)

**Comment by octalmage** [comment]
Hey sorry guys! I've been busy with work, and focusing on the RobotJS Windows build. I'm an nw.js guy also, so I may not get to this for a while.

**Comment by octalmage** [comment]
So I did some work on ScreenCat and RobotJS worked fine! I used the `apm install` method. 

@hugohil what command are you using to build/install?

**Comment by hugohil** [comment]
I'm really sorry I didn't reply, I was busy at the time and this got out of my mind after :/

I just tested and thanks to your fix, it now works perfectly ! :+1:
Also, thank @Nedomas for your suggestions about rebuilding modules.

I'll soon test the packaging issue and close the issue if it worked :)

**Comment by octalmage** [comment]
Awesome! Sounds good!

**Comment by ewnd9** [comment]
I've got this error on `./node_modules/.bin/electron-rebuild`

```
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
```

Anyone encountered something similar? (Ubuntu 14.04, node v0.10.37)

**Comment by octalmage** [comment]
I'm going to close this, if anyone still needs help please open a new issue!
