### ISSUE TITLE
Special characters with keyboard

### ISSUE THREAD

**Issue by ReneDyhr** [octalmage/robotjs#320]
I'm about to create a custom keyboard for my Electron app and I have looked all over Google to find something I can use in NodeJS to simulate a keyboard. So far this module is the best, but it doesn't support special characters like Æ Ø Å.
Can I somehow write these or can they get supported?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
