### ISSUE TITLE
Not print ?, < , *, ^ or another symbol in Linux Mint and Windows 7

### ISSUE THREAD

**Issue by Britskiy** [octalmage/robotjs#324]
Hello, I'm trying to emulate printing characters and I can't get its right. Instead "?" I get "</" .
What am I doing wrong?

```
 robot.setKeyboardDelay((10,20));
 robot.typeStringDelayed("Are you here?",randomInteger(200,500));
 robot.keyTap("enter");
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
