### ISSUE TITLE
moveMouseSmooth not working? 

### ISSUE THREAD

**Issue by kauegimenes** [octalmage/robotjs#325]
OS: Windows 10

moveMouseSmooth does not move the mouse. Only moveMouse

**Comment by UrielCh** [comment]
for me (Windows 10 (64bit), with nodejs 8.X), it's work fine.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
