### ISSUE TITLE
Feature request: utf-8 support

### ISSUE THREAD

**Issue by Tymski** [octalmage/robotjs#326]
Supporting utf-8 characters

## Expected Behavior
I was hoping to be able to robot.typeString("zażółć gęślą jaźń") for example.

## Current Behavior
Symbols are omitted or passed as different symbols.

## Workaround I found
I create child_process that runs an AutoHotKey script that sends the string. It works but I hate autohotkey's syntax xD

**Comment by zz85** [comment]
have you tried the patch in https://github.com/octalmage/robotjs/pull/276 ?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
