### ISSUE TITLE
build robotjs on Electron@1.7.5 is fail 

### ISSUE THREAD

**Issue by roy2651** [octalmage/robotjs#327]
## Your Environment

* RobotJS version:0.4.7
* Node.js version:6.10.0
* npm version:3.10.10
* Operating System:win7

**Comment by Klemen1337** [comment]
Use node v8.0.0 it worked for me

**Comment by roy2651** [comment]
@Klemen1337  ok I'm going to build now ,thank you

**Comment by roy2651** [comment]
@Klemen1337 my node version is 8.0.0 I use npm install but it doesn't work I find the version is not support. is your os is windows ,in windows it doesn't work .but in my mac ,it is ok. please help me

**Comment by Slapbox** [comment]
@roy2651 can you expand on your issue? Screenshot perhaps?

**Comment by roy2651** [comment]
@Slapbox heyman，I had resolve this problem。 I think this maybe my vc++ is broken . I install vs2015 and I build robotjs is ok. and I use node version 7.9.0  and npm run "npm rebuild --runtime=electron --target=1.7.5 --disturl=https://atom.io/download/atom-shell --abi=51"

**Comment by Slapbox** [comment]
@roy2651 Thanks for weighing in. I am considering using this package but was worried about the issue you were having. That makes me worry less.
