### ISSUE TITLE
shortcuts not working in mac os sierra using keyTap with modifier neither using keyToggle

### ISSUE THREAD

**Issue by kumarbhushan** [octalmage/robotjs#328]
var robot = require("robotjs");

robot.keyTap('tab','control');  //just firing tab 
//also tried 

robot.keyToggle('control','down');  
robot.keyTap('tab');                                
robot.keyToggle('control','up');    //same just firing tab 

//tried all key shortcut combinations 
//os mac os sierra 10.12.6

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
