### ISSUE TITLE
Feature requests.

### ISSUE THREAD

**Issue by metheyes** [octalmage/robotjs#329]
getPosByColor - finding the position of a hex color. (possibly an array if more than one is found)
getAppScreen - getting relative mouse coords for an program running, and make it so you can move/click within.
mouseClickHidden - clicking on a location without actually moving the mouse.

Not sure how active this library is but this would help me a ton!

**Comment by Abromide** [comment]
A quick work around I have found for getting the position by color is to take a bitmap and iterate through it looking for those pixels. Store the pixel position by finding the spot the pixel is in for the bitmap array. 
So if you have a 100x100 image and your pixel is number 2430 in the array, you know the position of the pixel is at (30, 24). Not very difficult to write a dynamic formula for different sized bitmaps.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
