### ISSUE TITLE
Create an ARM binary

### ISSUE THREAD

**Issue by ghost** [octalmage/robotjs#330]
## Expected Behavior
A binary downloaded for the ARM architecture

## Current Behavior
I have to build the package myself (on Raspberry Pi)

## Steps to Reproduce (for bugs)
1. `npm install robotjs` on an ARM machine

## Context
I'm trying to make it easier for other ARM users to use this package

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 8.4.0
* npm version: 5.3.0
* Operating System: Ubuntu MATE 16.04.3 LTS
  Processor: armv7

**Comment by brutalcrozt** [comment]
how to make binary for ARM architecture?

**Comment by yamboy1** [comment]
The same way that you would on a x86 computer, just on an ARM Device, such as the raspberry pi. If you want, I can build them and send them to you for each release

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
