### ISSUE TITLE
Cyrillic string (typeString)

### ISSUE THREAD

**Issue by jorenvandeweyer** [octalmage/robotjs#331]
When using `robot.typeString("б");` where `б` is a Cyrillic letter, it wil print `￐ﾱ`

Issue is on OSX

If there is a solution/fix I'd love to hear it,

Thanks in advance

**Comment by yalexx** [comment]
Hello i was wondering the same. Can the robotjs support other than English characters. German ? Like German ä, ö, ü and if yes how ?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
