### ISSUE TITLE
Do you think about hiddening mouse  in the future ?

### ISSUE THREAD

**Issue by wangjunwangjunwang** [octalmage/robotjs#332]
I want to hide the mouse in the Windows system on Electron App.
so ,I use 'moveMouse(the width of the screen,the height of the screen)' for now.
I think , do you think about hiddening mouse  in the future ?
thanks!

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
