### ISSUE TITLE
Keytap not sending properly to app

### ISSUE THREAD

**Issue by FinlayDaG33k** [octalmage/robotjs#334]
Hii there,

I'm trying to make a little script so that I can control my game over Telegram (sounds derpy, and it kinda is, but it's fun).
However, something odd is happening:
the script sends the keytaps to every program, except for the program I want it to.

so for example:
I focus on notepad and call `robot.keyTap("a")`.
The program registers it perfectly fine.
I focus on Firefox and call `robot.keyTap("a")`.
The program registers it perfectly fine.
I focus on VisualBoy Advance and call `robot.keyTap("a")`.
The program doesn't register it until I spam it 50 times or so.

Am I hitting some kind of limitation?

**Comment by FinlayDaG33k** [comment]
After a little bit of trial & error, I figured out that I need to increase the time a keyTap is "tapped".
So for example.
Instead of:
immediately pressing, then releasing
it should do:
press, wait a few ms, release

Is there a way I can do this with this library? (if not, might be a good idea to add?)

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
