### ISSUE TITLE
Electron and MacOS: robot-js sometimes stops to generate events

### ISSUE THREAD

**Issue by sobolevn** [octalmage/robotjs#336]
We are using `robot-js` in our `electron` app. And it works fine!
But sometimes (we can not say anything more specific) it just stops to generate `keyTap` events.

We have tried to install a keylogger to monitor keypress events. When everything working fine, there are keypresses in keylogger. But, when this error occurs there are no keypresses in keylogger.

## Expected Behavior
Consistently generate `keyTap` events.

## Current Behavior
Sometimes `keyTap` events do not fire.

## Steps to Reproduce (for bugs)
There are currently no steps to reproduce this issue. I can provide a source code which references this issue. It simplified for clarity. 

```javascript
'use strict'

const {
  app, Tray, Menu, globalShortcut
} = require('electron')

const robot = require('robotjs')

// Keep this reference global:
let mainWindow, appTray // eslint-disable-line no-unused-vars

function createMainWindow () {
  mainWindow = new BrowserWindow({
    show: false,
    title: 'Stack',
    minWidth: 750,
    width: 785,
    height: 500,
    frame: false,
    titleBarStyle: 'hidden'
  })

  // Icons:
  const normalIcon = path.join(pathToApp, 'build/IconTemplate.png')
  const pressedIcon = path.join(pathToApp, 'build/IconTemplate-pressed.png')

  let url = isDevelopment
    ? 'http://localhost:9080' : `file://${__dirname}/index.html`

  mainWindow.loadURL(url)

  appTray = new Tray('someIconPath.png')
  appTray.setPressedImage(pressedIcon)

  const contextMenu = Menu.buildFromTemplate(trayMenu)

  appTray.setToolTip('Our app')
  appTray.setContextMenu(contextMenu)

  // Register shortcuts
  globalShortcut.register('CommandOrControl+E', () => {
    robot.keyTap('v', 'command')
  })
}

app.on('ready', () => {
  createMainWindow()
})

app.on('before-quit', () => {
  globalShortcut.unregisterAll()
})

```

## Context

We need to paste from our application (let's say it generates some kind of data into `clipboard`). 
So, we are trying to generate `cmd` + `v` user input. Which is the only way to achieve that.

## Your Environment

- MacOS High Sierra, 10.13
- Node v7.4.0
- npm 4.0.5
- electron 1.7.8
- robot-js 0.4.7

**Comment by ruettenm** [comment]
I've the same problem. Any Ideas?

**Comment by ruettenm** [comment]
I found a solution... the mainWindow is still open.

I fixed it with this workaround:
```
function waitUntilWindowIsHidden() {
    return new Promise((resolve, reject) => {
        let tries = 1
        const maxTries = 10
        const interval = setInterval(() => {
            if (!mainWindow.isVisible() || tries > maxTries) {
                tries++
                clearInterval(interval)
                if (tries > maxTries) {
                    reject('main window still open')
                } else {
                    resolve()
                }
            }
        }, 5)
    })
}

waitUntilWindowIsHidden().then(() => {
    robot.keyTap('v', 'command')
})
```

**Comment by cevaris** [comment]
omg, that worked 🤦‍♂️

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
