### ISSUE TITLE
function like AutoHotKey's WinActivate

### ISSUE THREAD

**Issue by pauloch8** [octalmage/robotjs#337]
I want to send input keys to a Window's program. Using AutoHotKey I'm activating this window and then sending kebord's inputs. I'm using the command:  `WinActivate, Program Name`
I want to substitute AHK by Robotjs. 

Witch command could I use to activate a Program in Robotjs.

Even better, is there a way to send a input to a window without Activating it to foreground?

**Comment by octalmage** [comment]
Currently there isn't a way to activate a window with RobotJS, and there probably won't be for a while. We're working on the core functionality at the moment. See #161 for updates. Sorry! 

There also isn't a way that I know of to send input to a Window that isn't active with RobotJS.
