### ISSUE TITLE
http://robotjs.io/ expired

### ISSUE THREAD

**Issue by SamuraiJack** [octalmage/robotjs#341]
The domain of the website has expired.

**Comment by noizwaves** [comment]
Until this is resolved, I've found https://web.archive.org/web/20171024232804/http://robotjs.io/ to be helpful.

**Comment by octalmage** [comment]
Thanks for the heads up! I'm renewing it now.

**Comment by octalmage** [comment]
And it's back! Sorry about that. The content is hosted in GitHub if the site is every down again: 

https://github.com/octalmage/robotjs.io
