### ISSUE TITLE
getPixelColor segfault

### ISSUE THREAD

**Issue by syzer** [octalmage/robotjs#343]
## Current Behavior

```js
#!/usr/bin/env node
const robot = require('robotjs')

// Get mouse position.
const mouse = robot.getMousePos()

// Get pixel color in hex format.
console.log(mouse)
const hex = robot.getPixelColor(mouse.x, mouse.y)
```

if you have 3 monitors
{ x: 5825, y: -145 }
and x > 6000
it `Segmentation fault: 11`

## Your Environment

* RobotJS version:
```bash
"robotjs": "^0.3.7"
```
* Node.js version:
nvm use 8.9
Now using node v8.9.0 (npm v5.5.1)
* npm version:
* Operating System:
macOs

**Comment by syzer** [comment]
might be related to #88

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
