### ISSUE TITLE
is current version of robotjs  compatibility with Node version v0.12.2?

### ISSUE THREAD

**Issue by AMuniraju** [octalmage/robotjs#344]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* RobotJS version:
* Node.js version:
* npm version:
* Operating System:

**Comment by quinton-ashley** [comment]
Why in the world would you be using 0.12.2 of node?  LTS is 8.9.3 !

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
