### ISSUE TITLE
Special chars/Shift key not working

### ISSUE THREAD

**Issue by tms1337** [octalmage/robotjs#345]
As the title says special chars, i.e. '@' cant be typed using typeString or typeStringDelayed method. For the case of '@' with US keyboard, '2' is typed. This leads me to conclude that shift key is not working somehow.

I use Ubuntu 16.04, more specifically this AMI from AWS EC2 https://aws.amazon.com/marketplace/pp/B01MEG2PVE?ref=cns_srchrow

node version is v8.9.1
robotjs version as per package.son is    {... "robotjs": "^0.4.7", ...}

I know there are earlier versions of the same issue, but they seem to be resolved by some pull requests. I would like to make one if you can point me to the part of the code that needs to be edited.

**Comment by tms1337** [comment]
I used tapKey workaound with shift modifier, but I will still leave the issue open so it can be investigated

**Comment by SamuraiJack** [comment]
Same here. Looks like a lot of characters can not be used in "typeString" method.

**Comment by Chinafreak** [comment]
Not even äöüß is working. Best solution would be if the keyTap/keyToggle would accept keycode/rawcode (like from iohook) too. So you can just enter integer keycode in keyTap instead string which its limited.

As example, if you want to enter "E", which code for "E" is 69, so you enter it "robot.keyTap(69);" This allow us more chars support.

More information about virtual key:
https://msdn.microsoft.com/de-de/library/windows/desktop/dd375731(v=vs.85).aspx

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
