### ISSUE TITLE
Not compatible with Node 8.9.1?

### ISSUE THREAD

**Issue by SamuraiJack** [octalmage/robotjs#346]
After NodeJS upgrade from 6.10 to 8.9 I have this error. Removing the "node_modules/robotjs" folder and installing again did not help. Is Node 8 not supported currently?

```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/nickolay/workspace/Bryntum/siesta/node_modules/robotjs/build/Release/robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nickolay/workspace/Bryntum/siesta/node_modules/robotjs/index.js:1:77)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Comment by jareddgotte** [comment]
I've got it working on 9.3.0 so perhaps something else is going on? The error seems to imply that you need a different version of **robotjs** installed. Are your **package.json** dependencies properly configured? If so and you don't find your system's combination in [this list of binaries](https://github.com/octalmage/robotjs/releases/tag/v0.4.7), then you may need to [build your own](https://github.com/octalmage/robotjs#building). By the way, before you run `node-gyp rebuild`, be sure you have the latest git repo files cloned/downloaded into your **./node_modules/robotjs** folder. Also if you can't get `node-gyp rebuild` to work, you may want to refer to the [node-gyp readme](https://github.com/nodejs/node-gyp#installation), as well.

**Comment by SamuraiJack** [comment]
So you've just made a normal "npm install robotjs" on node 9.3.0 and it worked?

I might give a try to rebuild, mostly because of #347 (which is quite critical imo)

**Comment by jareddgotte** [comment]
I built a **robotjs** module (using the latest committed source from the master branch) for my particular machine, yes. I'm not sure if it would solve the issue you mentioned in #347, though.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
