### ISSUE TITLE
CapsLock key support

### ISSUE THREAD

**Issue by poojas2288** [octalmage/robotjs#349]
Unable to find capslock key in the syntax details and documentation ?
Is it supported ?
if not then is there any plan to include that ?
## Expected Behavior
Capslock key should work : 
robot.keyTap('capslock');

## Current Behavior
Capslock key not working

## Steps to Reproduce (for bugs)
Try : robot.keyTap('capslock');

## Context
I'm trying to render capslock key event from my electron app

## Your Environment

**RobotJS version: 0.4.7
Node.js version: 4.5.0
npm version: 2.15.9
electron version: 1.7.3
Operating System: Win 7**

**Comment by poojas2288** [comment]
Is there any update on this ?

**Comment by poojas2288** [comment]
@octalmage  Is there any plan to support CapsLock key in future ?
I haven't received any comments on my issue above..

**Comment by AlexRAV** [comment]
Hi poojas2288. How temporary solve problem, i just add `{ "capslock",       K_CAPSLOCK }`, to KeyNames array in file node_modules/robotjs/src/robotjs.cc 
After that, you can use capslock like other keyboard triggers: `robotjs.keyTap('capslock');`

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
