### ISSUE TITLE
Support typing of Unicode Characters for Win/Mac (similar to keyTap)

### ISSUE THREAD

**Issue by MariaDima** [octalmage/robotjs#351]
It would be helpful if unicode characters were supported for the keyTap method (windows & MAC).
Windows support for typeString() is also an asset.

**Comment by MariaDima** [comment]
Proposal included in https://github.com/octalmage/robotjs/pull/357.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
