### ISSUE TITLE
Align typeStringDelayed() functionality to typeString()

### ISSUE THREAD

**Issue by MariaDima** [octalmage/robotjs#353]
It would be good if typeString() and typeStringDelayed() could be aligned to support the same functionality (unicode characters).

**Comment by MariaDima** [comment]
Proposal included in https://github.com/octalmage/robotjs/pull/357.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
