### ISSUE TITLE
install fail on ubuntu 14.04 

### ISSUE THREAD

**Issue by piyushpatil027** [octalmage/robotjs#36]
Hi,

Hope you are doing great.You have developed great package.I am using ubuntu 14.04.
I configure your package but when i  run command ( node-gyp build ) it is giving  error.

make: Entering directory `/home/piyush/app/Nodejs_Application/robotjs/build'
  CC(target) Release/obj.target/robotjs/src/mouse.o
../src/mouse.c:12:35: fatal error: X11/extensions/XTest.h: No such file or directory
  #include <X11/extensions/XTest.h>
                                   ^
compilation terminated.
make: *** [Release/obj.target/robotjs/src/mouse.o] Error 1
make: Leaving directory `/home/piyush/app/Nodejs_Application/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-54-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /home/piyush/app/Nodejs_Application/robotjs
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v2.0.2

something like this . can you explain me what did this error come or what have i done wrong in installation?

**Comment by abhinavsingh** [comment]
Try again after

```
sudo apt-get install libxtst-dev libpng++-dev
```

**Comment by piyushpatil027** [comment]
Thanks abhinav,

It works.

**Comment by octalmage** [comment]
Great! Thanks @abhinavsingh!
