### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by ilie-stefan** [octalmage/robotjs#362]
Hi. I'm trying to make a bot who makes click events on specified locations on screen in an android emulator. on desktop the click event works, but on the emulator window, doesn't work. i've tried with 2 windows opened (explorer and emulator) and a click event on the emulator window... it doesn't make it active.. what i'm doing wrong ?

**Comment by Abromide** [comment]
Do you mind me asking which emulator you are using?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
