### ISSUE TITLE
Could we have some tags on triaged issues? or need triage issues? So its easier for contribution to roll in!

### ISSUE THREAD

**Issue by adamchenwei** [octalmage/robotjs#365]
## Expected Behavior
Adding tags for most if not all the issues, 112, sounds like lots fun here!
## Current Behavior
No tags
## Possible Solution
Adding tags, maybe contributors can help?

## Steps to Reproduce (for bugs)
Look at the issues in issues tab
## Context
Contribution

## Your Environment
Browser

# NOTE
yes, this seems a reallllllyyyyy awesome project that I would love to help contribute, but seems too many stuff to look at, and I just want to do something small at the begining

**Comment by octalmage** [comment]
The ready tag is used for tickets that have been accepted and are ready to be worked on. You can find these here: 

https://waffle.io/octalmage/robotjs

**Comment by octalmage** [comment]
I'm working on sorting through the rest of the tickets now.
