### ISSUE TITLE
Not able to control another app

### ISSUE THREAD

**Issue by samarthagarwal** [octalmage/robotjs#366]
I have a very simple script that just types a few characters after a timeout of like 5 seconds. I run the script and immediately switch to another app. The characters are always typed in the terminal. The app never receives any inputs. 

## Expected Behavior
The characters should be typed in the app if teh focus is on the app.

## Current Behavior
The characters are typed in the terminal no matter where the focus is.

Any advices or workarounds?

**Comment by octalmage** [comment]
Have you tried clicking on the new window? The window has to be in focus to receive the keystrokes.

**Comment by samarthagarwal** [comment]
Yes. I have tried that. It seems as if it is only limited to the console the script is executed in.

**Comment by autuus** [comment]
If the app is running in admin mode, windows locks up all automations, witch sucks

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
