### ISSUE TITLE
Gamepad Support for Windows, Hold Down <Key> for X amount of time, and other time based functions.

### ISSUE THREAD

**Issue by Jac0xb** [octalmage/robotjs#367]
Add support for Gamepad for Windows.
Automate holding down <Key> for X amount of time, and other time based functions.
Add Press / Release Key Toggle function.
Add callback on Release of key.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
