### ISSUE TITLE
index.js:23 Uncaught TypeError: Cannot set property 'capture' of undefined

### ISSUE THREAD

**Issue by githubaccount624** [octalmage/robotjs#368]
I just installed robotjs on Windows 10 (after struggling for a bit to get windows-build-tools) installed. Finally got robotjs installed through npm with no errors, and after I include it in my project like this:

    var robot = require("robotjs");

I get the following error at runtime after it executes that line:

https://i.imgur.com/B8pzT1e.png

I'm trying to use this with electron.

**Comment by githubaccount624** [comment]
Immediately after posting this I had a memory of something similar that happened when I first started using electron. Sure enough, it worked. Here's the solution if anyone else encounters this through Google search:

    if (typeof module === 'object') { window.module = module; module = undefined; }
    var robot = require("robotjs");
    if (window.module) { module = window.module; }

Not sure why this has to be done or if there are any better solutions, but this seems to work.

**Comment by githubaccount624** [comment]
Wait, nevermind. It's still not working.. As soon as I tried calling robot functions the error came back.

**Comment by githubaccount624** [comment]
My robotjs variable is a string for some reason:

![robotstring](https://user-images.githubusercontent.com/20170894/35772480-7b5f480a-090d-11e8-8d44-97616be0a034.png)

**Comment by octalmage** [comment]
Hi @githubaccount624. This is a new one for me, usually it's related to the binary being incorrect. Could you try these instructions? 

http://robotjs.io/docs/electron

**Comment by wuyunjiang** [comment]
How did you solve it？thanks

**Comment by wuyunjiang** [comment]
> http://robotjs.io/docs/electron

I did that , but it still didn't work

**Comment by wuyunjiang** [comment]
@octalmage Could you help me

**Comment by bymi15** [comment]
Still having this same problem, anyone got a solution?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
