### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [octalmage/robotjs#37]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "close a stream") ⇒ [newMMBitmapFromPNG](https://github.com/octalmage/robotjs/blob/d3f03d089d3d974c47ae1d4e1f7b34d4093db217/src/png_io.c#L138)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "reposition a file-position indicator") ⇒ [newMMBitmapFromBMP](https://github.com/octalmage/robotjs/blob/d3f03d089d3d974c47ae1d4e1f7b34d4093db217/src/bmp_io.c#L217)

**Comment by octalmage** [comment]
I'll look at a pull request of you want, otherwise I think it's fine.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
