### ISSUE TITLE
I hope for the binary named "robotjs-v0.5.1-node-v57-win32-x64.tar.gz"

### ISSUE THREAD

**Issue by yunxu1019** [octalmage/robotjs#377]
![image](https://user-images.githubusercontent.com/15274374/37147638-90edb792-2302-11e8-84ae-7d9dbf1869af.png)

**Comment by octalmage** [comment]
For this I need to figure out how to get AppVeyor building in 64bit mode. They have 64bit machines, but it seems like the build tools are still in 32bit. The install should still produce a binary with the correct dependencies.  See this for more information: 

https://github.com/nodejs/node-gyp#on-windows

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
