### ISSUE TITLE
How to save the image of Bitmap to disk ?

### ISSUE THREAD

**Issue by wetouns** [octalmage/robotjs#379]
when I call screen.capture() to get a Bitmap,I want to save bitmap.image to disk,what's the way to do it?

image | The raw image (buffer).

**Comment by srgraham** [comment]
Issue #13 tracks the progress on this and some comments in there have good workarounds in the meantime.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
