### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [octalmage/robotjs#38]
I would like to point out that identifiers like "[`_MMSize`](https://github.com/octalmage/robotjs/blob/d3f03d089d3d974c47ae1d4e1f7b34d4093db217/src/types.h#L9)" and "[`_MMPointArray`](https://github.com/octalmage/robotjs/blob/aad9e6db8f2d2335e331b95be2e749d85d858940/src/MMPointArray.h#L7)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by octalmage** [comment]
I think we're good, thanks though!

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
