### ISSUE TITLE
moveMouse sometimes not working correctly?

### ISSUE THREAD

**Issue by YanDevDe** [octalmage/robotjs#380]
When I change the values from getMousePos and set it again at moveMouse, then somehow the position is still not correct.
Here is my example code to reproduce:

```
var robot = require("robotjs");
robot.setMouseDelay(0);
setInterval(() => {
  var deltaX = 10;
  var deltaY = 33;
  var mouseX = robot.getMousePos().x + deltaX;
  var mouseY = robot.getMousePos().y + deltaY;
  console.log("----------PrePosition-----------");
  console.log("X: " + robot.getMousePos().x + " | Y: " + robot.getMousePos().y);
  robot.moveMouse(mouseX, mouseY);
  console.log("----------Changed-----------");
  console.log("X: " + mouseX + " | Y: " + mouseY);
  console.log("X: " + robot.getMousePos().x + " | Y: " + robot.getMousePos().y);
}, 500);
```

Log:
https://i.imgur.com/P1HdPMB.png

Here you can see that the position at "---Changed---" is not same which it should be! Even the mouse isn't at the exactly position when I set "moveMouse".
The getMousePos and/or mouse position should return exactly same position which I've set position at moveMouse.

**Comment by Chinafreak** [comment]
Okay, I found out that in some computer it works fine. So not all computer make problems.

My PC that make problem:
1x 4K TV
3x 21:9 Monitors
Windows 10

My PC that make no problem (MacBook, Windows installed, from my work):
3x 16:9
Windows 10

Not sure where this problem come from.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
