### ISSUE TITLE
Is it possible to turn the raw pixel bitmap into a PNG buffer IN MEMORY without saving it?

### ISSUE THREAD

**Issue by PixelSoftwareStudios** [octalmage/robotjs#381]
I would like to capture a portion of a screen and display it in an HTML image tag without saving it to disk just to save space. And at some point I would like to have it constantly update the image and saving it to disk would possibly create race conditions. What is a fast efficient way to take the bitmap and convert it into a usable PNG buffer?

**Comment by Deltatiger** [comment]
If you just want to display an image from bmp/png, you can simply convert it to base64 string format and then display it on the image tag.

[Check out the first answer in this question](https://stackoverflow.com/questions/19369334/is-there-a-way-to-show-bitmap-data-in-html-image-tag)

But I am not fully sure about 2 things,
* How do you provide the image. Is it through REST API or do you read from file.
* Support for base64 image conversion. I am not sure if it can be directly done with only RobotJS (Not sure).

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
