### ISSUE TITLE
MacOS screenshot fails with negative coordinates

### ISSUE THREAD

**Issue by feronetick** [octalmage/robotjs#382]
Sorry for my broken english please.

I have a three monitors. Main display is in the middle. Because of this my left monitor has negative coordinates.

## Expected Behavior
When I specify a rectangle with a negative start, the screenshot should contain an image from the left display.

## Current Behavior
```
┏ Electron -------------------

  x -4 y 279 width 144 height 372

┗ ----------------------------
┏ Electron -------------------

  Received signal 11 SEGV_MAPERR 000000000010

  ==== C stack trace ===============================

   [0x000112f20ca4]
   [0x7fff58c34f5a]
   [0x7fff58b5c384]
   [0x000113bdd20b]
   [0x000112736551]
   [0x00011280224e]
   [0x00011280176b]
   [0x24e6ff5043fd]
   [0x24e6ff5f7148]
   [0x24e6ff5bbe1c]
   [0x24e6ff5f7148]
  [end of stack trace]

┗ ----------------------------
```

## Steps
As I understand it, the start of coordinates on Mac is in the upper left corner of the main monitor. Monitors on the left and top have negative coordinates. You can try to move the monitors and make a screenshot.

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: 9.8.0
* npm version: 5.6.0
* electron version: 1.8.2
* Operating System: Mac OS High Sierra 10.13.3

**Comment by feronetick** [comment]
List of my displays from https://electronjs.org/docs/api/screen

```
 { id: 861421875,
    bounds: { x: 0, y: 0, width: 1920, height: 1080 },
    workArea: { x: 0, y: 23, width: 1920, height: 972 },
    size: { width: 1920, height: 1080 },
    workAreaSize: { width: 1920, height: 972 },
    scaleFactor: 1,
    rotation: 0,
    touchSupport: 'unknown' }
  { id: 861423413,
    bounds: { x: 1920, y: 0, width: 1920, height: 1080 },
    workArea: { x: 1920, y: 23, width: 1920, height: 1057 },
    size: { width: 1920, height: 1080 },
    workAreaSize: { width: 1920, height: 1057 },
    scaleFactor: 1,
    rotation: 0,
    touchSupport: 'unknown' }
  { id: 478197382,
    bounds: { x: -1280, y: 56, width: 1280, height: 1024 },
    workArea: { x: -1280, y: 79, width: 1280, height: 1001 },
    size: { width: 1280, height: 1024 },
    workAreaSize: { width: 1280, height: 1001 },
    scaleFactor: 1,
    rotation: 0,
    touchSupport: 'unknown' }
```

![2018-03-18 21 12 47](https://user-images.githubusercontent.com/3761183/37568309-3a84aeec-2af5-11e8-9754-ebad59f99faf.png)

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
