### ISSUE TITLE
can't use capslock

### ISSUE THREAD

**Issue by sboys3** [octalmage/robotjs#385]
## Context

There is no way to use the caps lock key

## Possible Solution

you have `K_CAPSLOCK` in keycode.h but it is not in robotjs.cc
you could add `{ "capslock",       K_CAPSLOCK },` into the KeyNames array in robotjs.cc

## Your Environment

* RobotJS version :currrent
* Node.js version: 8.10.0
* npm version: 5.6.0
* Operating System: windows

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
