### ISSUE TITLE
Error regarding NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by LeandroMedeiros** [octalmage/robotjs#387]
My app throws an unexpected error at me:

![screen shot 2018-04-06 at 14 45 46](https://user-images.githubusercontent.com/1299711/38435807-3423b4fe-39a9-11e8-861e-43ad888c63a7.png)

## Expected Behavior
Installing latest NodeJS and npm along with latest RobotJS should work.

## Current Behavior
App throws an error about NODE_MODULE_VERSION as shown in the picture above.

## Possible Solution
Reinstalling everything maybe.

## Steps to Reproduce (for bugs)
On macOS, install NodeJS and npm from the beta channel (9.11.1+5.6.0), then use $npm install robotjs . When you try running a function the app throws an error as shown in the picture above.

## Context
Nothing more relevant to add :(

## Your Environment

* RobotJS version:
0.5.1

* Node.js version:
9.11.1

* npm version:
5.6.0

* Operating System:
macOS High Sierra

**Comment by claudiobmgrtnr** [comment]
same issue here

**Comment by gio1217** [comment]
same issue :(

**Comment by gio1217** [comment]
On node with version 8.11.x it's ok

**Comment by Deltatiger** [comment]
Have you tried this [guide](http://robotjs.io/docs/electron) ?

**Comment by Deltatiger** [comment]
What version of electron are you using?

So far the issues to me seems that nodejs used to compile RobotJS was Node 9 (NODE_MODULE_VERSION 59) but electron seems to require only version 8.11.x (NODE_MODULE_VERSION 57 is upto 8.11.x).
I think this may be somehow related to the version of Electron being used.
That may also explain why it is running fine in the NodeJS version 8.11.x.

**Comment by gio1217** [comment]
that's why :) thanks for your reply

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
