### ISSUE TITLE
How to drag an Electron window?

### ISSUE THREAD

**Issue by ysuliu** [octalmage/robotjs#389]
## Expected Behavior

The Electron window could be drag to expected position

## Current Behavior

The Electron window not dragged, only mouse moved to the specified position

## Steps to Reproduce (for bugs)

1. Download the Electron demo code [here](https://github.com/electron/electron-quick-start)
2. import robotjs and insert below code to main.js under the lines for create window
`  setTimeout(() => {`
`    robot.moveMouse(10, 10);                  // 1. move mouse upon the window`
`    robot.mouseToggle("down", "left");    // 2. toggle left key, 'down'`
`    robot.dragMouse(100, 100);               // 3. drag window to (100, 100) from default (0, 0)`
`    robot.mouseToggle("up", "left");         // 4. toggle 'up'`
`  }, 3000);`
3. add 'robotjs' to package.json
4. npm install and rebuild robotjs
5. npm start

Or, unzip the attached app.zip, and do above step 4&5
[app.zip](https://github.com/octalmage/robotjs/files/1919277/app.zip)

## Context

Actually, I'm trying to develop the application for remote assistant. The mouse event will be passed to remote computer and handled by robotjs.

## Your Environment

* RobotJS version:  0.4.7
* Node.js version:  8.9.1
* npm version: 5.5.1
* Operating System: Windows10
* Electron: 1.7.11

**Comment by Deltatiger** [comment]
Did you try first clicking on the window to activate it and then hold and drag ?

robot.moveMouse(10, 10);
robot.mouseClick(); // Guessing this is where the window is
robot.mouseToggle("down", "left");
robot.dragMouse(100, 100);
robot.mouseToggle("up", "left");

This may not work but just a guess.

**Comment by ysuliu** [comment]
@Deltatiger  Thanks for comments. I tried your code, but seems no luck, the window not be dragged.

**Comment by Deltatiger** [comment]
@ysuliu Let me check it out and get back. My current laptop has some DLL initialization routine failed error so can't do it right now.

**Comment by Deltatiger** [comment]
I checked the code for sometime and I think I have narrowed down the issue. Need to confirm.
(Though I did not try for electron window, I did try for a general window for which also it failed).

Seems dragMouse also in turn is only calling moveMouse. This moveMouse needs to be told that the leftMouse has been pressed for it to actually respond like dragging I think. I am not sure how it can be achieved in the existing call.

Not going to jump to conclusions until I test it and make it work.

Will post once I get it tested or find an alternate.

**Comment by ysuliu** [comment]
@Deltatiger  Thanks a lot. "DLL initialization routine failed error " could be solved by [this guide](http://robotjs.io/docs/electron).

**Comment by Deltatiger** [comment]
@ysuliu confirmed this works. Why it works still eludes me. Need to look at the documentation for SendInput is my thought. But still this is strange.

**Comment by roy2651** [comment]
@ysuliu about drag，my code is:
robot.moveMouse(lastX,lastY) //记录鼠标down的位置
robot.mouseToggle('down')  // 触发down
robot.dragMouse(x, y)   // 拖拽到新的位置
robot.mouseToggle('up') // 触发up

I also use robotjs and webrtc datachannel for remote assistant

**Comment by ysuliu** [comment]
@roy2651   I used the same code with yours in my first demo, it was failed to drag the window, it looks like a mouse move other than mouse drag. 

Seems we are making the similar app for remote assistant, we also used webrtc as the data channel. 
Actually, the problem in my app is:
the drag is failed when we try to drag my app window. We can drag the other app's window successfully.
Means my app received the drag event from remote device for dragging itself to a new place, but the remote control will be interrupted when robot.dragMouse() execution.

So I'm trying to do some demo/testing for Electron and robotjs to find out a solution for my app.

Anyway, are you also based on Electron? Have you ever met the same/similar issue?

Thanks.

**Comment by rayfoss** [comment]
It might help to make things more human for debugging... maybe see what happens with a dragMouseSmooth https://github.com/octalmage/robotjs/issues/211#issuecomment-406682101

I don't use windows so...

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.

**Comment by dsidler88** [comment]
Holy sh** thank you, this has to be the only solution on the internet for this obscure issue.

I'm working in Protractor, and GoJS. So it's not even close to the same, but using that little stutter move, was able to latch onto an element and drag it.

**Comment by yuapple** [comment]
@ysuliu  can yu resove it
