### ISSUE TITLE
Erratic behavior with first person shooters

### ISSUE THREAD

**Issue by mstan** [octalmage/robotjs#390]
When attempting to emulate mouse movements in a first person shooter, I am getting erratic, extreme movements that aren't usable within the game within Windows.

## Expected Behavior
First Person shooters, if I understand correctly, work by setting the cursor to the center of the screen. Mouse monitoring software suggests for my 1080p monitor, this would be 960,540. Then, when the user moves their mouse, it quickly checks the delta change from 960,540, then resets to that position, moving the person in that direction.

## Current Behavior
However, when attempting to offset in any direction, I am getting undesired extreme up or down movement. (for example, if I attempt to set my movement my mouse position to 959,540--I expect to have my player's field of view to move slightly left, but not to look up or down. However, setting this position causes it to look ALL THE WAY UP and to the left (despite the fact it's still centered vertically).

## Possible Solution
This may have to do with the mouse being SET at a specific position, and not "moving" to it. 

NeatMouse, a windows based mouse emulator, binds keys to mouse movements. When using it, it gives the desired behavior. Perhaps have a generic left,right,up,down mouse movement function implemented that emulates NeatMouse's behavior (found at https://github.com/neatdecisions/neatmouse )

## Steps to Reproduce (for bugs)
Attempt any moveMouse(x,y) cooridinate while in a first person shooter to reproduce behavior.

Coincidentally, this same exact behavior occurs when attempting to control a first person shooter through Teamviewer

## Context
I am attempting to build a bot that allows others to remotely control a first person shooter via chat commands. I don't need precise movement for the character's view, but I need reasonable movement.

## Your Environment

Windows 10
npm 5.6.0
node v9.11.1

**Comment by Abromide** [comment]
Can you show us some of your code? You may want to try the following and see if it still happens
```

robot.moveMouseSmooth(959, 540)
setTimeout(() => {
    robot.moveMouse(960, 540)
}, 100)
```

**Comment by mstan** [comment]
@Abromide I have gone ahead and attempted the function you suggested, by having it move one pixel to the right for 100 milliseconds. Unfortunately, I am experiencing the same behavior. Despite the Y cooridinate not changing, it is causing it to look straight up (as if it was assigning the Y to 0 each time)

**Comment by EJTH** [comment]
Hi I had similar problems to yours. I think the problem is that your game is expecting relative movement events, but robot JS only sends absolute mouse events. Which sadly is not very well supported by most games. I have a solution here

https://github.com/octalmage/robotjs/issues/422

**Comment by svarunan** [comment]
@EJTH i tried using your #422  
`robot.moveMouseRelative(2,0);` and other multiple combo but mouse is not moving.
using windows 10, 64bit

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
