### ISSUE TITLE
Wrong keydown code produced in a browser when using typeString method

### ISSUE THREAD

**Issue by romario333** [octalmage/robotjs#391]
If you use `robot.typeString()` method to type a key and listen for this in a web application via `keydown` event, you get event object with incorrect `code`. For example for key `3` I'm getting `code=KeyA`. I have tested this on MacOS with latest Chrome, Firefox and Safari.

To reproduce go to this page, that registers `keydown` event listener: https://codepen.io/romario333/pen/vjxzaW

Then run this simple script and make sure browser has focus when `typeString()` is executed:

```javascript
robot = require("robotjs");

setTimeout(() => {
	robot.typeString("3");
}, 5000);
```

## Expected Behavior

`keydown` with `code=Digit3` is emitted in a web browser

## Current Behavior

`keydown` with `code=KeyA` is emitted in a web browser

## Context

I ran into this while trying to use https://barcodetopc.com/ with my web application. Note that barcode readers generally act as a keyboard and emit keyboard events with a value of scanned barcode.

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: v8.11.1
* Operating System: macOS High Sierra 10.13.4 (17E199)
* Browsers: Chrome 66, Firefox 59, Safari 11.1

**Comment by assadjaved** [comment]
did you find any solution to this issue?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
