### ISSUE TITLE
Remove dependency on Python

### ISSUE THREAD

**Issue by TheGreatRambler** [octalmage/robotjs#397]
I have tried looking int he source code but I don't understand why we need Python. If we can remove it, it would make code used with this module easier to transport.

**Comment by Deltatiger** [comment]
Python is required for node-gyp to work.
We do use node-pre-gyp but building binaries for all systems is tedious and we require lot of resources (VMs basically).
On Windows you do not need it if you have windows-build-tools npm package installed globally (I am yet to test this).

**Comment by octalmage** [comment]
As you can see here, we do have a large number of prebuilt binaries available that will be auto downloaded: 

https://github.com/octalmage/robotjs/releases/tag/v0.5.1

Python is only a requirement of building. 

Please let me know if you still have an issue with this!
