### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by DaRealSh0T** [octalmage/robotjs#399]
I am getting an error when I try to install robotjs.

## Expected Behavior
It should install

## Current Behavior
It doesn't install
npm ERR! path E:\projects\node_modules\.staging\bl-9c38a8f2\package.json
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall utime
npm ERR! EINVAL: invalid argument, utime 'E:\projects\node_modules\.staging\bl-9c38a8f2\package.json'

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
1. npm install robotjs

## Your Environment
* RobotJS version: none
* Node.js version:8.1.3
* npm version: 5.0.3
* Operating System: Windows 7 x64

**Comment by Tau5** [comment]
I cant install too
##
prebuild-install WARN install No prebuilt binaries found (target=10.4.0 runtime=node arch=x64 platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/tau/nodejs/twitch/node_modules/robotjs/build'
gyp ERR! System Linux 4.13.0-43-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tau/nodejs/twitch/node_modules/robotjs
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
##

**Comment by Deltatiger** [comment]
@Tau5 Can you try to get the prerequisites installed and then try again?
[Requirements](https://github.com/octalmage/robotjs#building)
