### ISSUE TITLE
Cancelling running robotjs methods

### ISSUE THREAD

**Issue by Prof-Dan** [octalmage/robotjs#40]
Is there a way of cancelling running methods such as mouseMoveSmooth() when the node program exits?

At the moment there is no way of stopping the robotjs from running and pressing buttons even if process.exit(1) is called...

**Comment by Prof-Dan** [comment]
This is related to #27 as the methods must be asynchronous for them to be able to be cancelled, so I guess this is not actually a separate issue?

**Comment by octalmage** [comment]
I haven't thought about this, you'll probably just have to wait for mouseMoveSmooth to finish before closing the app. mouseMoveSmooth calls moveMouse in a loop, so I believe it's blocking.

**Comment by octalmage** [comment]
I'm going to close this in favor of #27.
