### ISSUE TITLE
wrong mouse x , y 

### ISSUE THREAD

**Issue by parsibox** [octalmage/robotjs#400]
hi 
i use node 8 in windows 10
when i record mouse x , y it is not true
for example i click one point and get x , y with this  iohook
(  https://www.npmjs.com/package/iohook )
it say 
```
 x: 1552, y: 1077
```
but your code say
```
x:1242 y:862
```
i test with c# and c# say 
```
 x: 1552, y: 1077
```
why your package say something other?
![image](https://user-images.githubusercontent.com/12513476/41149447-d95b61c6-6b20-11e8-9fed-c53fcb3de7c3.png)

**Comment by Deltatiger** [comment]
I tried out some stuff with iohook and mouseClick from robotjs and found that the coordinates reported were the same.

![robotjs-i400-results](https://user-images.githubusercontent.com/1459811/41194587-4f9cbcde-6c3b-11e8-8e93-c289dcdb7aff.PNG)

RobotJS: 0.5.1
Node: 8.9.1 (LTS)
OS: Windows 10

**Comment by Deltatiger** [comment]
Can you provide some more information like some reproduction code snippet, robotjs version and maybe some gif reproduction or something ?

**Comment by parsibox** [comment]
this is my code
```
const ioHook = require('ioHook');//npm install iohook --save # or yarn add iohook 
var robot = require("robotjs");
ioHook.on("mouseclick",function(msg){console.log(msg);

    var mouse = robot.getMousePos();

    // Get pixel color in hex format.
    var hex = robot.getPixelColor(mouse.x, mouse.y);
    console.log("#" + hex + " at x: " + mouse.x + " ," + mouse.y);

});
ioHook.start();
```

**Comment by parsibox** [comment]
this is my robotjs version
```
robotjs@0.5.1
```

**Comment by parsibox** [comment]
this is my node version
```
v8.11.1
```

**Comment by parsibox** [comment]
this is a video from my code and runing code ( extract zip file and play video )
[ice_video_20180609-223007.zip](https://github.com/octalmage/robotjs/files/2087211/ice_video_20180609-223007.zip)

**Comment by Deltatiger** [comment]
Correct me I am wrong but are you saying that the getMousePos is returning a different location than what the **msg** value is printing?

**Comment by parsibox** [comment]
yes this is different
you can see this in my video

**Comment by parsibox** [comment]
```
PS E:\node\click-2> npm info node-gyp version
3.7.0
PS E:\node\click-2> npm info robotjs version
0.5.1
```

**Comment by Deltatiger** [comment]
I tried out the exact same code as you, but for me it works correctly.

![robotjs-i400-results 1](https://user-images.githubusercontent.com/1459811/41194852-d53f1a9a-6c3f-11e8-916c-fe293bc8bdfe.PNG)

Apart from NodeJS Version everything else is also the same. This is very odd. Let me check on some other machine with the specified NodeJS Version and get back to you.

**Comment by parsibox** [comment]
this is my os info

![image](https://user-images.githubusercontent.com/12513476/41194961-9d477994-6c39-11e8-889e-3d4729f64890.png)
![image](https://user-images.githubusercontent.com/12513476/41194962-a082b43e-6c39-11e8-9aae-051f916b2d83.png)

**Comment by parsibox** [comment]
is there any results?

**Comment by relsqui** [comment]
Is your display scaled? If so, you might be having similar issues to #403, which has a workaround posted.

**Comment by parsibox** [comment]
no

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
