### ISSUE TITLE
typeString() is slower with numbers than with alphabet.

### ISSUE THREAD

**Issue by Ldoppea** [octalmage/robotjs#401]
Hi,

On Windows : when using `robot.typeString()`, numbers are typed 100 times slower than other chars.

I did not try on other OS.

I made measurements with `robot.setKeyboardDelay(1);` but result is similar without.

## Expected Behavior
Numbers and alphabetic chars should by typed at the same speed.

## Current Behavior
Numbers are typed slower
Using code in `Steps to reproduce`, I get the following result : 
```
Type 100 numeric chars: 6795.126ms
Type 100 alphabetic chars: 64.041ms
```

## Steps to Reproduce (for bugs)
1. Execute following code
 ```
robot.setKeyboardDelay(1);
console.time('Type 100 numeric chars');
robot.typeString("0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789");
console.timeEnd('Type 100 numeric chars');
console.time('Type 100 alphabetic chars');
robot.typeString("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv");
console.timeEnd('Type 100 alphabetic chars');
```
2. read console output

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: 9.8.0
* npm version: 5.6.8
* Operating System: Windows 10

**Comment by Deltatiger** [comment]
@Ldoppea I tried out the same code snippet in my environment and there was not that much difference between both of them.

![robotjs-i401-results](https://user-images.githubusercontent.com/1459811/41194311-1b75a8ca-6c37-11e8-94ad-d87bb16dc9a5.PNG)

My environment is almost the same

RobotJS version: 0.5.1
Node.js version: **8.9.1**
npm version: 5.8.0
Operating System: Windows 10

Can you run the same script again or can you provide some more info about this?

**Comment by Ldoppea** [comment]
Hi,

I just tried in my home computer, on a new folder:
```
npm init
npm install robotjs --save
//create index.js
node index.js
```

index.js contains only the following code : 
```
var robot = require("robotjs");

robot.setKeyboardDelay(1);
console.time('Type 100 numeric chars');
robot.typeString("0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789");
console.timeEnd('Type 100 numeric chars');
console.time('Type 100 alphabetic chars');
robot.typeString("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv");
console.timeEnd('Type 100 alphabetic chars');

robot.keyTap("enter");
```

Same result as my work computer:
```
>node index.js
Type 100 numeric chars: 6764.455ms
Type 100 alphabetic chars: 96.436ms
```

RobotJS version: 0.5.1
Node.js version: 8.9.1
npm version: 5.5.1
Operating System: Windows 10 1803 (April update 17134.48)
I have VS2017 on both computer (which is used by node-gyp)
My work computer runs on HDD while my home computer runs on SSD
Both has i7 processor
Work computer has ESET Endpoint antivirus. Home computer has default windows Antivirus.

> or can you provide some more info about this?

What other info may help you?

**Comment by Deltatiger** [comment]
I tried this on a few other windows systems but I could not reproduce this issue.

Could you possible try to switch the alpha and numeric strings and see if the result is consistent?

Also if possible can you run the following code?

`
robot.setKeyboardDelay(1);
console.time('Type 100 alpha chars');
robot.typeString("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv");
console.timeEnd('Type 100 alpha chars');
console.time('Type 100 numeric chars');
robot.typeString("0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789");
console.timeEnd('Type 100 numeric chars');
console.time('Type 10 numeric chars');
robot.typeString("0123456789");
console.timeEnd('Type 10 numericchars');
`

This is to see if the time is proportional to the count or is it some kind of system wait.

**Comment by Ldoppea** [comment]
Ok, I think I just found the origin of the problem.

I'm using an Azerty keyboard and on those keyboards numbers are accessed using SHIFT modifier with numeric keys. If you don't press SHIFT, then you have special characters. This is the exact opposite of QWERTY keyboards.

Here is what I get from your code on Azerty mode :

```
Type 100 alpha chars: 123.383ms
Type 100 numeric chars: 6798.310ms
Type 10 numeric chars: 612.037ms
```

And then when I switch to Querty mode :
```
Type 100 alpha chars: 108.884ms
Type 100 numeric chars: 71.814ms
Type 10 numeric chars: 7.527ms
```

Also results are similar if you use the SHIFT modifier with a Querty keyboard:
```
console.time('Type 100 special chars');
robot.typeString("!@#$%^&*()!@#$%^&*()!@#$%^&*()!@#$%^&*()!@#$%^&*()!@#$%^&*()!@#$%^&*()!@#$%^&*()!@#$%^&*()!@#$%^&*()");
console.timeEnd('Type 100 special chars'); 
```

will produce
```
Type 100 special chars: 6575.222ms
```

**Comment by Deltatiger** [comment]
@Ldoppea Nice.

That seems to be the issue. I am guessing this is the intended behavior but I shall look at it a bit to see if there is any better way to do it.

Thanks for your help :D

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
