### ISSUE TITLE
User input overrides mousetoggle(up) on Linux

### ISSUE THREAD

**Issue by charburgx** [octalmage/robotjs#402]
## Expected Behavior
Even if the user is holding down the left mouse button, mousetoggle(up) should still change the state to being up until the user clicks their mouse again. This is how, for instance, AutoHotKey handles sending mouse input.

## Current Behavior
mousetoggle(up) will have no effect if the button is being held down by the user

## Possible Solution
Not sure if root is necessary to override what the hardware is doing? The same issue occurs when running xdotool so maybe its an issue with X11?

## Steps to Reproduce (for bugs)
```
var robot = require("robotjs");

setTimeout(function()
{
    console.log("up");
    robot.mouseToggle("up");
}, 2000);
```
Run this while holding down left mouse. The button will stay held down

## Context
Currently working on an application that needs to click on something even if the user is holding down the mouse button. The idea was to save the user's mouse location and click state, set the mouse state to up, click on the thing, and then reset the mouse. Since mousetoggle(up) doesn't override user input, this seems impossible using robotjs. 

## Your Environment
Ubuntu Budgie 17.10
Node v8.11.2
RobotJS v0.5.1
npm v5.6.0

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
