### ISSUE TITLE
Verbose output?

### ISSUE THREAD

**Issue by relsqui** [octalmage/robotjs#404]
Is there a way to get verbose logging output from robotjs? I've poked around the docs and searched but didn't find anything. If not, consider it requested. :) If it exists and I just missed it, I'd be happy to make a PR to the docs about it.

Context: The actual problem I'm trying to solve (which I might open a separate issue for, once I'm satisfied it's not my own fault) is a couple different instances of a click or a key combination not doing what I expect under certain circumstances. Right now I can't tell if the actions aren't happening when they should, or they're being sent to the OS correctly but just not having the results I want. Chatty output from robotjs would be a big help. I'm open to other debugging suggestions as well.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
