### ISSUE TITLE
keyToggle doesn't hit shift and command together

### ISSUE THREAD

**Issue by relsqui** [octalmage/robotjs#405]
## Expected Behavior
I used `keyToggle` to hold down shift and command, and used the Mac keyboard viewer to observe what keys were being pressed. The expected result was that both shift and command would be highlighted on the keyboard viewer.

## Current Behavior
Only shift was pressed:

![keytoggle-cropped](https://user-images.githubusercontent.com/1859500/42532240-12b8ba3a-843b-11e8-9e1c-d069c0861727.gif)

If I reversed it so that it was holding command-with-shift instead of shift-with-command, only command was pressed.

Notably, the equivalent on Windows (using shift and control) is working fine! I didn't make a minimal repro for it, but the real script succeeds in Windows where it fails on Mac.

## Steps to Reproduce (for bugs)
Here's the code I used to test:

```javascript
var robot = require('robotjs');

robot.keyToggle('shift', 'down', 'command');
```

## Context
The actual thing I'm trying to do is ctrl-shift-click on something, so merging #356 would be a better long-term solution for me -- but this seems like an unexpected behavior you'd probably want to know about anyway. :)

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: 9.8.0
* npm version: 5.7.1
* Operating System: macOS 10.13.4 (High Sierra)

**Comment by shubhibhatt2007** [comment]
I am rying to send a shortcut to my applicattion using robot.keyTap('<',['command','shift']), this is also not working(expected keys are not tapped). Strangely, other shortcut on my application - robot.keyTap('[',['command','shift']) seems to be workig fine.

**Comment by oktapodia** [comment]
@shubhibhatt2007 can you please open another issue with a reproducible example?
