### ISSUE TITLE
Question: Possible to simulate mouse click without moving the real mouse pointer?

### ISSUE THREAD

**Issue by ablankenship10** [octalmage/robotjs#406]
I'm working on an app that has some screenshare capabilities and we want to support separate cursors for each user. Is it possible, either currently in the node lib or within the capability of the native code if modified, to simulate a click at a specific position without moving the real local mouse pointer?

**Comment by seiyria** [comment]
Also wondering about this for a project I'm working on.

**Comment by andynguy3n** [comment]
I got the same question.

**Comment by octalmage** [comment]
Just move the mouse really quick and put it back! I used to do this, with some extra logic to hide the mouse during movement. The last piece currently isn't possible with RobotJS, so you'll have to find a way to do that yourself!
