### ISSUE TITLE
shift+command+? doesn't work

### ISSUE THREAD

**Issue by quinton-ashley** [octalmage/robotjs#408]
robot.keyTap('?', ['shift', 'command']);
doesn't work but...
robot.keyTap('l', ['shift', 'command']);
does work.
I'm trying this out with the Eclipse Java app, maybe it just doesn't register the first command for some reason

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
