### ISSUE TITLE
right/left ctrl

### ISSUE THREAD

**Issue by sam0x17** [octalmage/robotjs#409]
I need the ability to keyToggle the left and right ctrl buttons separately. Is this already a thing? I have not been able to find anything in the code, docs or online about treating ctrl as anything other than a modifier key

**Comment by Deltatiger** [comment]
Just checked the code. Seems there is no distinguishing between the left / right control keys.
Is there lot of difference between left / right modifier keys ?

It should be easy to implement if required though (at least on windows).

**Comment by sam0x17** [comment]
Yes, I have a use case (in a video game) where they are bound to different things.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
