### ISSUE TITLE
Redundant Include Guards 

### ISSUE THREAD

**Issue by Deltatiger** [octalmage/robotjs#41]
I was going through the code and found that all header files have both #ifndef and #pragma once. This seems to be redundant. There are no significant performance improvements as far as I have seen.

According to wikipedia the #pragma once is supported in most compilers. Why not just use that alone ?
Wiki article link : https://en.wikipedia.org/wiki/Pragma_once#Portability

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for {days_inactive} days.
    You may reopen this issue if it has been closed in error.
