### ISSUE TITLE
Window lock shortcut key not working

### ISSUE THREAD

**Issue by immohdali** [octalmage/robotjs#411]
robot.keyTap('delete', ['control','alt']);

OR

robot.keyTap("l",["command"]);

not working.

I am trying to lock my windows 10 via robotjs code but not working please find above code.

Please help me out from this issue

**Comment by sireaev** [comment]
Here's a workaround to lock a window screen (Windows):

`robot.keyTap("d", ["command"]);`
`robot.keyTap("r", ["command"]);`
`robot.typeString("cmd");`
`robot.setKeyboardDelay(500);`
`robot.keyTap("enter");`
`robot.typeStringDelayed("rundll32.exe user32.dll, LockWorkStation", 0.03);`
`robot.keyTap("enter");`
`process.exit(-1);`

On every tap and mouse click, time matters, have a look at it

**Comment by Deltatiger** [comment]
Seems that this is some sort of restriction on the way Win + L is interpreted.
More info can be found here : [StackOverFlowLink](https://stackoverflow.com/questions/11696253/use-sendinput-to-lock-the-computer)

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
