### ISSUE TITLE
Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by GrantGryczan** [octalmage/robotjs#414]
## Expected Behavior
I expect `npm install robotjs` to work fine without any prerequisites as is implied by the `README`.

## Current Behavior
After entering `npm install robotjs`, I get this error.
```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Grant Gryczan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Grant Gryczan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Grant Gryczan\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:184:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Grant Gryczan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Grant Gryczan\Documents\Miroware\Dynamic\node_modules\robotjs
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

## Steps to Reproduce (for bugs)
[Here's my repository](https://github.com/GrantGryczan/Dynamic), and explicit steps for setting it up are in its `README` section, though I'm not sure the repo is relevant to the error.
While in the repo's directory, I just run `npm install robotjs`.

## Context
I'm just trying to install `robotjs`.

## Your Environment
* Node.js version: 10.4.0
* npm version: 6.2.0
* Operating System: Windows 10

**Comment by leorolland** [comment]
Had the same problem, try to run in an admin command prompt
`npm install --global --production windows-build-tools`

source: https://github.com/felixrieseberg/windows-build-tools/issues/56#issuecomment-304404123

**Comment by emko** [comment]
same i am on node 10.10.0, python does exists where it says it does not and running python does work so my path is set

**Comment by realcarbonneau** [comment]
I get approximately the same problem.  The instructions do not mention any other pre-requisites other than installing NodeJS.  I Installed the latest NodeJS 10.10.0 and ran npm install robotjs and I get:

```
C:\RobotJS>npm install robotjs

> robotjs@0.5.1 install C:\RobotJS\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=9.10.1 runtime=node arch=x64 platform=win32)

C:\RobotJS\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\RobotJS\node_modules\robotjs
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\RobotJS\package.json'
npm WARN RobotJS No description
npm WARN RobotJS No repository field.
npm WARN RobotJS No README data
npm WARN RobotJS No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Real\AppData\Roaming\npm-cache\_logs\2018-09-13T15_58_34_388Z-debug.log

C:\RobotJS>
```

**Comment by realcarbonneau** [comment]
I just installed Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) and the python command environment variable is not setup automatically, but py is.  So the docs and/or scripts need to be updated I think.

**Comment by emko** [comment]
have you figured it out? it works fine on node 8 but i need it to be able to run on node 10 since Electron is using node 10 on its v3 betas

**Comment by kwiniarski97** [comment]
https://github.com/felixrieseberg/windows-build-tools/issues/56
Did you try any of those. It helped me

**Comment by quinton-ashley** [comment]
the easy way is to reinstall python

**Comment by GrantGryczan** [comment]
As is stated in the issue, I expect `npm install robotjs` to work fine without any prerequisites as is implied by the `README`. I shouldn't have to do anything for that command to work. So either the instructions in the `README` should be updated or this issue should be resolved.

**Comment by quinton-ashley** [comment]
You're right it's not specified as a requirement only a build requirement.  On macOS the python path is already set and 2.7 is part of the OS.  Windows has 2.7 of python too but path isn't set.  Reinstalling 2.7.x is the easiest way to get robotjs working on windows.  README should be changed.  Also once you get down to the build for windows section the node-gyp command doesn't work.  I had to include this file in my project top level folder.  This might only apply for building for electron though.
```
{
    'targets': [
        {
            'target_name': 'build_all',
            'type': 'none',
            'dependencies': ['node_modules/robotjs/binding.gyp:*'],
        }
    ]
}

```

**Comment by Deltatiger** [comment]
Sorry everyone.
The main problem is that we are using  a prebuild system to distribute the binaries so that no other dependency is required on the user side. Unfortunately the binaries have not been updated in a while since it is a lot of work.

The best way to make it work on the newer platforms (NodeJS Versions) is to have all the dependencies installed  and setup for it to build on your system and work.

I will check to make sure the project works with at least manual building on the latest node platform.

Do check the prerequisites part in the Building [Link](https://github.com/octalmage/robotjs#building) and see if it helps.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.

**Comment by CliffyMk** [comment]
MacOS

On Terminal type:
**which python**

npm config set python="which python"

Idea is to set the python path of npm.

**Comment by custompro12** [comment]
This is still an issue. Running:

> npm install --global --production windows-build-tools

on Windows 10 in an administrative PowerShell fixed it for me
