### ISSUE TITLE
How to install Robotjs in NWjs ?

### ISSUE THREAD

**Issue by Deathlive** [octalmage/robotjs#416]
My os Windows 10.
I install RobotJS in NWjs project.
`nmp install robotjs`
Installed Complete succes.
But when start my project, in consol log display an error.
**A dynamic link library (DLL) initialization routine failed.**

How i can fix this error?

**Comment by xywang68** [comment]
Have you tried running npm rebuild?

**Comment by Deathlive** [comment]
Can I download the rebuild version right away?
For PC Windows 10 x64.

**Comment by F145h** [comment]
how to solve this?
Error "A dynamic link library (DLL) initialization routine failed." too

after "npm rebuild" the same

**Comment by saint739** [comment]
Have any solution?
npm rebuild not solve this

**Comment by iustinpericica** [comment]
any solution?..

**Comment by saint739** [comment]
Yes, I found solution
Use older version of NWjs 0.44.6

**Comment by iustinpericica** [comment]
What nodejs version do you use?

**Comment by saint739** [comment]
v14.4.0

**Comment by saint739** [comment]
I refreshed my memory when downgrading NWJS for windows.
Why downgrade? Because in 0.43.6 application freeze in background. But in newer version of NWJS robotjs compiling, but not running, nw.exe closing after start.
Next steps for version 0.38.4
1. Install node 12.3.1
2. run npm i windows-build-tools
3. run npm i -g node-gyp
3. install python 2.7 (3 not working)
4. go to your_nwjs_project, run npm i
5. go to your_nwjs_project/node_modules/robotjs , run node-gyp rebuild
6. enjoy

**Comment by saint739** [comment]
Today I am downgrade NWJS again to 0.37.4 . 
0.38.4 have a problem with animation in my project.
For compiling robotjs for 0.37.4 you must install Node 11.14.0

**Comment by saint739** [comment]
And downgrade again to 0.29.4. Version 0.35.5 has error with update Notifications.

New receipt 

1. Install node 9.11.1 with npm 5.6.0 (if you have newer version of npm, you must manually delete npm directory in your user directory c:\Users\alexe\AppData\Roaming\npm\)
2. run npm i -g windows-build-tools (in Administrative mode)
3. run npm i -g node-gyp
4. replace C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc (see link above)
5. install python 2.7 (3 not working)
6. go to your_nwjs_project
7. remove node_modules
8. run npm i
9. go to your_nwjs_project/node_modules/robotjs , run node-gyp rebuild
