### ISSUE TITLE
Can Robotjs be implemented for TESTING React/Electron Components through keyboard automation ?

### ISSUE THREAD

**Issue by sunakshi96** [octalmage/robotjs#417]

**Comment by quinton-ashley** [comment]
robotjs is for OS level keyboard and mouse control.  You can use puppeteer for testing those components.  <https://github.com/GoogleChrome/puppeteer>

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
