### ISSUE TITLE
Windows: Use SendInput instead of mouse_event for toggleMouse

### ISSUE THREAD

**Issue by MariaDima** [octalmage/robotjs#420]
Based on Microsoft official documentation (https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-mouse_event), **mouse_event has been superseded**.

It would be good if we update to use the **SendInput** method for **toggleMouse** functionality.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
