### ISSUE TITLE
Feature Request: moveMouseRelative

### ISSUE THREAD

**Issue by EJTH** [octalmage/robotjs#422]
For some situations (Like automating/interacting with games) it is very handy to be able to set the relative movement because most games don't work that well when setting absolute positions (In windows at least).

To circumvent this limitation I have implemented my own moveMouseRelative function in robotjs and build that locally. Though my implementation only covers windows, I have found similar workarounds on the Issue tracker for OSX, don't know how this affects linux.

## Expected Behavior
Moving mouse should not cause erratic behavior in games

## Current Behavior
Absolute positioning doesn't work well with games running under windows (And according to other issues also doesn't work well with games in OSX)

## Possible Solution
1. Change moveMouse to always use relative commands (As this emulates a mouse better than absolute, which I think is intended for pen tablets etc)
2. Implement a moveMouseRelative function for those who wish to interact with applications that are dependant on relative movement.

## Steps to Reproduce (for bugs)

1. Open incompatible game (GTA5 in my case)
2. try to move the camera viewport with mouseMove commands

## Your Environment

* RobotJS version: ^0.5.1
* Node.js version: 8.12.0
* npm version: 6.4.1
* Operating System: Windows 10

**Comment by EJTH** [comment]
For those interrested here is my current implementation of relative mouse move:


```
void moveMouseRelative(MMPoint point)
{
#if defined(IS_MACOSX)
	//Osx Implementation
#elif defined(USE_X11)
         //linux implementation
#elif defined(IS_WINDOWS)
	
	INPUT mouseInput;
	mouseInput.type = INPUT_MOUSE;
	mouseInput.mi.dx = point.x;
	mouseInput.mi.dy = point.y;
	mouseInput.mi.dwFlags = MOUSEEVENTF_MOVE;
	mouseInput.mi.time = 0; //System will provide the timestamp
	mouseInput.mi.dwExtraInfo = 0;
	mouseInput.mi.mouseData = 0;
	SendInput(1, &mouseInput, sizeof(mouseInput));

#endif
}
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
