### ISSUE TITLE
scrollMouse not working

### ISSUE THREAD

**Issue by kathagcam** [octalmage/robotjs#423]
Looks like the scrollMouse does not work, or maybe i'm missing something?

## Steps to Reproduce 
const robot = require("robotjs");
  async scrolll() {
    robot.scrollMouse(0, 50);
  }

## Context
I want to scroll until the bottom of the page, but nothing happens with the code above. I have tried changing to (0, 'down') and vice-versa ('down, 0), (50,0) but no luck. Am I doing something wrong?

## Your Environment

* RobotJS version: 0.5.1
* Types/node: 7.0.12
* Node.js version: 6.10.x
* npm version: 6.4.1
* Operating System: Mac 10.13.3
* Browser: Firefox 62.0
* Resolution: 1600x1200

**Comment by EJTH** [comment]
Try using a negative value. From the documentation:

> The magnitude and direction of the scroll up and down. **Down is negative.**

**Comment by kathagcam** [comment]
@EJTH  thanks. I tried adding negative values, but no luck. (0, -50) or (0, -100) but no luck.

**Comment by kathagcam** [comment]
Found another solution

**Comment by ditrix36** [comment]
@kathagcam I have the same bug but on a windows system while trying to use it with electron what was your solution?

**Comment by Smilebags** [comment]
I'm also experiencing the same thing, Windows 10. Keen to find a solution.

**Comment by nickreyntjens** [comment]
@Smilebags I'm also experiencing the same thing, Windows 10. Keen to find a solution...

Did you find another solution. The scrolling of robotjs does not seem to work on windows.

**Comment by Smilebags** [comment]
@nickreyntjens My solution was to modify the source code and rebuild. I can't remember exactly what it was but I think there was a PR here that solved the issue but wasn't merged.

**Comment by danielehrhardt** [comment]
Same Problem here. Did someone have a Solution?

**Comment by raphaelmenges** [comment]
For anybody having the same issue: The latest release 0.6.0 from December 2019 does not include the bespoken changes. However, one can use the RobotJS module directly from GitHub as dependency in a `package.json` - which makes scrolling work for me on Windows:
```
"dependencies": {
  "robotjs": "git://github.com/octalmage/robotjs.git#8ae87a91f06f49559f0db387bc2bd1ea01419880"
}
```

**Comment by FrankSalmick** [comment]
That solved it for me too. For anyone else who wants to use this solution, since [github removed the git://](https://github.blog/2021-09-01-improving-git-protocol-security-github/) protocol you have to use https:// instead now. Like this

```
"dependencies": {
  "robotjs": "https://github.com/octalmage/robotjs.git#8ae87a91f06f49559f0db387bc2bd1ea01419880"
}
```
