### ISSUE TITLE
Not working on new macOS 10.14 Mojave

### ISSUE THREAD

**Issue by nfrasser** [octalmage/robotjs#424]
## Expected Behavior

```js
const robot = require('robotjs');
robot.keyTap('a');
// taps key 'a'
```
## Current Behavior

```js
const robot = require('robotjs');
robot.keyTap('a');
// nothing happens
```

## Possible Solution

Still investigating

## Steps to Reproduce (for bugs)
1. Use a Mac running macOS 10.14
2. Try running `robot.keyTap('a');`

## Context
We're using this in our macOS and Windows desktop application to emit keyboard macros

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: 10.11.0
* npm version: 6.4.1
* Operating System: macOS 10.14

**Comment by nfrasser** [comment]
Here's the output of `npm test`

```
> robotjs@0.5.1 test /Users/palette/Development/octalimage/robotjs
> run-script-os


> robotjs@0.5.1 test:darwin:linux /Users/palette/Development/octalimage/robotjs
> jasmine 'test/**/*.js'

Started
...FFFF.....FF......

Failures:
1) Integration/Keyboard types
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:425:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

2) Integration/Mouse clicks
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:425:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

3) Integration/Mouse scrolls vertically
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:425:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

4) Integration/Mouse scrolls horizontally
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:425:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

5) Mouse Move the mouse.
  Message:
    Expected false to be truthy.
  Stack:
    Error: Expected false to be truthy.
        at UserContext.<anonymous> (/Users/palette/Development/octalimage/robotjs/test/mouse.js:20:34)
  Message:
    Expected false to be truthy.
  Stack:
    Error: Expected false to be truthy.
        at UserContext.<anonymous> (/Users/palette/Development/octalimage/robotjs/test/mouse.js:21:34)

6) Mouse Move the mouse smoothly.
  Message:
    Expected 811 to equal 100.
  Stack:
    Error: Expected 811 to equal 100.
        at UserContext.<anonymous> (/Users/palette/Development/octalimage/robotjs/test/mouse.js:42:26)
  Message:
    Expected 707 to equal 100.
  Stack:
    Error: Expected 707 to equal 100.
        at UserContext.<anonymous> (/Users/palette/Development/octalimage/robotjs/test/mouse.js:43:26)

20 specs, 6 failures
Finished in 34.203 seconds
```

**Comment by nfrasser** [comment]
Current workaround is to downgrade Xcode 9 or Command Line tools to the 10.13 versions. Then Robot.js runs as before.

**Comment by pronebird** [comment]
On Mojave the one needs the accessibility permission to send clicks.

<img width="529" alt="screenshot 2018-10-10 at 13 16 03" src="https://user-images.githubusercontent.com/704044/46732754-ae825700-cc8e-11e8-9b97-8f93950e8f13.png">

**Comment by doodybrains** [comment]
this worked for me! 

open System Preferences > Security & Privacy > Accessibility (you might have to unlock the settings by clicking the lock icon in the bottom left hand corner) > check "Terminal" app in the list "Allow the apps below to control your computer"

**Comment by pronebird** [comment]
@doodybrains I believe folks use robotjs on CI. This is impossible to do there.

**Comment by doodybrains** [comment]
@pronebird oh ok. this helped me for my own use of robotjs..thought it might be related.

**Comment by nfrasser** [comment]
Another potential insight: We were bundling robotjs in a ".app" and had to set the [`NSAppleEventsUsageDescription`](https://developer.apple.com/documentation/bundleresources/information_property_list/nsappleeventsusagedescription?language=objc) in Info.plist to get the accessibility permissions prompt.

This is no longer an issue for me; the maintainer(s) may close this if the CI issue (as noted by @doodybrains) cannot be addressed.

**Comment by sancarn** [comment]
For me terminal was already checked. Unchecking and rechecking it did the trick! :)

**Comment by oktapodia** [comment]
It looks solved to me.
You may reopen this issue if it has been closed in error.

**Comment by brandonros** [comment]
https://github.com/octalmage/robotjs/issues/548

Mouse stuff seems broken to me in Catalina.

**Comment by aabuhijleh** [comment]
> For me terminal was already checked. Unchecking and rechecking it did the trick! :)

This is an issue I'm facing as well.  If you deploy a new version of the app, even if the accessibility permission is already granted to the older version, it needs to be ungranted then granted again for robotjs to work.

**Comment by greggreenhaw** [comment]
Any word on fixing mouse support in catalina?

**Comment by xiajingren** [comment]
macOS Monterey 12.3.1

Robotjs works perfectly in dev - does nothing in production, any news ？
