### ISSUE TITLE
mouseClick bug?

### ISSUE THREAD

**Issue by arjuna-dev** [octalmage/robotjs#426]
## Expected Behavior
The mouseClick function should work on the top-menu of OSX, and also to switch windows when other windows are clicked. 

## Current Behavior
It works only on the rest of the screen, not on the top-menu of OSX and also not to switch windows. 

## Possible Solution
No idea what's going on.

## Steps to Reproduce (for bugs)
`
const { app, globalShortcut } = require('electron')
var robot = require("robotjs");

app.on('ready', function(){

    globalShortcut.register('CommandOrControl+L', () => {
        robot.moveMouse(920, 30);
        // robot.moveMouse(920, 10);
        robot.mouseClick('left');
    })
    globalShortcut.register('CommandOrControl+P', () => {
        robot.mouseClick('left');
    })
  
})

//This works, but the shortcut doesn't...

robot.moveMouse(920, 23);
robot.mouseClick('left');`

## Context
Trying to get a shortcut to move and click to one of my favorite items in the top-menu of OSX.

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: v10.10.0
* npm version: 6.4.1
* Operating System: MacOS Mojave 10.14

**Comment by 1renhaO** [comment]
i have another problem, i used robotjs in electron, and use mouseToggle to control the mouse behavior, but i found it not worked, and i also ues it click the vscode(i know it write by electron), it also not worked. but i use it click another software not write by electron(just like chrome), it works, my english is not good, is there anything wrong for me?(i used macos(10.14.1 Beta), robotjs(0.5.1), electron(2.0.10) )
```javascript
                                if (data.oprType === 'mousedown') {
					var button = data.which === 3 ? 'right': 'left',
						posClient = {
							x: data.x,
							y: data.y,
						},
						screenClient = {
							width: data.screenWidth,
							height: data.screenHeight,
						},
						screenServer = {
							width: screen.width,
							height: screen.height,
						},
						posServer = transformPosition(posClient, screenClient, screenServer);
					if (posServer.x === 'outscreen' || posServer.y === 'outscreen') {
						console.log('receive out screen click');
						return;
					}
					robot.moveMouse(posServer.x, posServer.y);
					robot.mouseToggle('down', button);
				} else if (data.oprType === 'mouseup') {
					var button = data.which === 3 ? 'right': 'left',
						posClient = {
							x: data.x,
							y: data.y,
						},
						screenClient = {
							width: data.screenWidth,
							height: data.screenHeight,
						},
						screenServer = {
							width: screen.width,
							height: screen.height,
						},
						posServer = transformPosition(posClient, screenClient, screenServer);
					if (posServer.x === 'outscreen' || posServer.y === 'outscreen') {
						console.log('receive out screen click');
						return;
					}
					robot.moveMouse(posServer.x, posServer.y);
					robot.mouseToggle('up', button);
				}
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
