### ISSUE TITLE
Prebuilt packages missing - RHEL 7.5: npm install robotjs fails at prebuild step

### ISSUE THREAD

**Issue by rakou** [octalmage/robotjs#427]
npm install robotjs fails at prebuild step.

## Expected Behavior

npm install robotjs fails at prebuild step.

## Current Behavior

Instead of installing clean the installation fails at the prebuild step when it tries to download 

https://github.com/octalmage/robotjs/releases/download/v0.5.1/robotjs-v0.5.1-node-v64-linux-x64.tar.gz file which doesnt exist. (Not found at the location)

## Steps to Reproduce (for bugs)

1. npm install robotjs --loglevel verbose

## Your Environment

* RobotJS version: -0.5.1
* Node.js version: v10.10.0
* npm version: v6.4.1
* Operating System: RHEL 7.5

Installation Log:

prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.5.1/robotjs-v0.5.1-node-v64-linux-x64.tar.gz
prebuild-install WARN install connect ETIMEDOUT 192.30.253.113:443

**Comment by Dan5741** [comment]
Under the Building section in the documentation is states that 

> Python (v2.7 recommended, v3.x.x is not supported).

Make sure you download Python 2.7 and try to install it again. 

I had the same issue because I only had Python 3.6 installed on my computer. After I installed the correct Python version, the issue was resolved. 

Best,

Daniel Veinberg

**Comment by rakou** [comment]
> Under the Building section in the documentation is states that
> 
> > Python (v2.7 recommended, v3.x.x is not supported).
> 
> Make sure you download Python 2.7 and try to install it again.
> 
> I had the same issue because I only had Python 3.6 installed on my computer. After I installed the correct Python version, the issue was resolved.

**Comment by rakou** [comment]
> > Under the Building section in the documentation is states that
> > > Python (v2.7 recommended, v3.x.x is not supported).
> > 
> > 
> > Make sure you download Python 2.7 and try to install it again.
> > I had the same issue because I only had Python 3.6 installed on my computer. After I installed the correct Python version, the issue was resolved.

I am already running python 2.7

# python -V
Python 2.7.15rc1

As you can see that it tries to download the v64 version of the file and halts as the file doesn't exist.

> robotjs@0.5.1 install /node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.3
prebuild-install info looking for local prebuild @ prebuilds/robotjs-v0.5.1-node-v64-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-octalmage-robotjs-releases-download-v0.5.1-robotjs-v0.5.1-node-v64-linux-x64.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.5.1/robotjs-v0.5.1-node-v64-linux-x64.tar.gz

**Comment by Deltatiger** [comment]
Prebuild falls back to the manual build process.
Make sure you have all the following dependencies available.

'''
Python (v2.7 recommended, v3.x.x is not supported).
make.
A C/C++ compiler like GCC.
libxtst-dev and libpng++-dev (sudo apt-get install libxtst-dev libpng++-dev).
'''

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
