### ISSUE TITLE
captureScreen leaks memory in Linux

### ISSUE THREAD

**Issue by felipemanga** [octalmage/robotjs#441]
Continuously capturing the desktop eventually makes the system run out of RAM.

## Expected Behavior

Any memory allocated should be freed or, preferably, reused on the next capture.

## Current Behavior

The amount of memory taken up by node steadily increases into a few GB.

## Steps to Reproduce (for bugs)

```cpp
let robot = require("robotjs");
setInterval(function(){
    robot.captureScreen();
}, 20);
```

## Context

Trying to stream the screen to another device.

## Your Environment

* RobotJS version: 0.5.1 (latest on npm)
* Node.js version: 10.11.0
* npm version: 6.4.1
* Operating System: Linux (Ubuntu 18)

**Comment by yomiAdenaike01** [comment]
How did you get it to work because i keep getting npm version conflict errors.

**Comment by oktapodia** [comment]
@yomiAdenaike01 can you please create another issue with a reproducible example? Closing as it is stale.
