### ISSUE TITLE
Where I can find api documentation?

### ISSUE THREAD

**Issue by vithmel** [octalmage/robotjs#442]
Where I can find api documentation?

http://robotjs.io/

![2018-11-16_154640](https://user-images.githubusercontent.com/15888026/48625164-1840ff80-e9b7-11e8-9ed6-430a44a330d3.png)

**Comment by vithmel** [comment]
Api docs:
https://web.archive.org/web/20180402195859/https://robotjs.io/docs/syntax

**Comment by giubatt** [comment]
Looks like it's back

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
