### ISSUE TITLE
run at reactjs

### ISSUE THREAD

**Issue by lakshmankashyap** [octalmage/robotjs#444]
show error

`TypeError: Cannot set property 'capture' of undefined`

**Comment by Deltatiger** [comment]
Could you provide the code that you used ?

**Comment by huoyingjianshen** [comment]
> show error
> 
> `TypeError: Cannot set property 'capture' of undefined`

Maybe the robotjs can only run with cmd "node xxx.js" beacuse the function "module.exports.screen.capture" does not work on broswer directly.
So if you want to use it on your broswer program,you can follow this "https://github.com/ml1nk/robotjs-browser"(does not work on broswer directly).

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
