### ISSUE TITLE
ctrl+alt+suppr kill node on windows

### ISSUE THREAD

**Issue by pushkar13** [octalmage/robotjs#445]
run this under windows 10 :
setInterval(() => {
    var img = robot.screen.capture();
    console.log('capture');
},1000);
Just hit ctrl+alt+suppr and then cancel
Node is killed without any message...

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* RobotJS version:0.5.1
* Node.js version:8.9
* npm version:5.6
* Operating System:Windows 10

**Comment by pushkar13** [comment]
I think it's in robotjs.cc, return of copyMMBitmapFromDisplayInRect is not test
If NULL, second line will cause a null pointer exception

MMBitmapRef bitmap = copyMMBitmapFromDisplayInRect(MMRectMake(x, y, w, h));
uint32_t bufferSize = bitmap->bytewidth * bitmap->height;

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
