### ISSUE TITLE
Read WinTitle and WinClass

### ISSUE THREAD

**Issue by sl5net** [octalmage/robotjs#449]
I like to do context sensitive text manipulation with AHK. 
The easiest way to do it is tor read titleName and className and load library. waits user desicions and then write back to the clipboard then paste the text (i use it with windows, source at my github). 

If this could be added to the road map that would be awesome! 
I know that the titleName and className is may not cross platform? But who knows ?

Or is there a better more reliable method to edit/analyze typed text?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
