### ISSUE TITLE
Unable to work with electron 4.x ?

### ISSUE THREAD

**Issue by nj-neer** [octalmage/robotjs#450]
## Expected Behavior
An Electron app (4.x.x) containing robotjs should launch

## Current Behavior

Error message : Node is unable to find 'robot.js' module
![image](https://user-images.githubusercontent.com/9463585/50644276-a590e100-0f70-11e9-94ab-c9f4d89af963.png)

## Possible Solution
Downgrading electron version (work fine with 2.0.16)

## Steps to Reproduce (for bugs)

1. Create a simple electron app that contain robotjs
2. be sure to rebuild robotjs (i used [electron-rebuild](https://github.com/electron/electron-rebuild) )
3. launch your app (electron app.js)
4. Error message

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: 8.12.0
* npm version: 6.4.1
* Operating System: Windows 10 X64

**Comment by Bartastic** [comment]
I had the same issue - I found you need to rebuild, easiest way to do this is just run

"npm i robotjs"

and it should recompile.

**Comment by nj-neer** [comment]
Weird, i tought i rebuilded but it seem it didn't worked.

Work fine now, thanks !
