### ISSUE TITLE
Feature: draw on desktop

### ISSUE THREAD

**Issue by denishowe** [octalmage/robotjs#451]
I can _get_ the colour of a pixel on the screen, but I would also like to be able to _set_ pixels, i.e. draw on the screen.  I'd like to be able to choose whether to draw on the background (wallpaper, behind all windows) or right on top of everything.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
