### ISSUE TITLE
some mouse click on xvfb-run does not work

### ISSUE THREAD

**Issue by xwmbww** [octalmage/robotjs#453]
when running robotjs in xvfb-run (Linux virtual frame buffer) environment, some of the mouse clicks are not registered.
## Expected Behavior
the same sequence worked in DISPLAY=:0 (GUI console), however when working in xvfb-run environment it should produce the same result
## Current Behavior
some of the clicks are not registered
## Steps to Reproduce (for bugs)
  In this example we use selenium-server as the test application. We try to use images to drive to the point where it shows the drop down list of browsers.
  All steps passed when we run our test in DISPLAY=:0.
  The last step failed when we run our test in xvfb-run where DISPLAY=:99, and the reason of failure is due to the step before where clicking the "Selenium_SelectBrowsers_dropDownClosed" image is not registered by the webpage therefore it does not open the drop down list.
  Interestingly, the 3rd step and the 5th step have the same action, and the only difference is the target image is different. and the 3rd step worked on DISPLAY=:99.

  Scenario: Check Webdriver Hub page images - Create Session
    When  I visit "http://localhost:4444/wd/hub"
    Then  I should see the "Selenium_CreateSession_button" image on the screen
    When  I click the "Selenium_CreateSession_button" image on the screen
    Then  I should see the "Selenium_CreateNewSession_modal" image on the screen
    When  I click the "Selenium_SelectBrowsers_dropDownClosed" image on the screen
    Then  I should see the "Selenium_SelectBrowsers_dropDownOpened" image on the screen
## Context
We try to use robotjs and image actions to conduct GUI testing. We try to put our test to xvfb-run in order to run in the CI environment With this bug we can not run this test in the CI..

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: v8.11.4, v8.15.0
* npm version: 5.6.0
* Operating System: ubuntu 18.04

**Comment by xwmbww** [comment]
Update: I have also confirmed it failed on a different dropdown list clicking.
Here is the new test scenario:

  Scenario: Check demo page images - Drop-Down List
    Given I open the url "/"
    When  I scroll to element "footer"
    When  I click the "First_option" image on the screen
    Then  I should see the "First_option_Opened" image on the screen

where the demo-page has a generic dropdown list that is independent from the selenium-standalone server dropdown list.
Again, the same test passed with DISPLAY=:0;
and failed with xvfb-run --server-num=99 --server-args="-screen 0 1920x1200x16"

dropdown list HTML example:
<select id="waitForSelectedElement">
                    <option value="1" selected="">First option</option>
                    <option value="2">Second option</option>
                </select>

**Comment by xwmbww** [comment]
MP4 for passed on DISPLAY=:0
https://ufile.io/4ddoo

MP4 for failed on xvfb-run --server-num=99
https://ufile.io/24ny1

**Comment by xwmbww** [comment]
Update: It looks like the issue is gone. Not sure why.
However I have completely rebuilt the Ubuntu 18.04 VM, and used openjdk version "1.8.0_191" instead of Oracle Java.
Now the exact test scenario I mentioned above are passing as expected.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.

**Comment by AkiraWang89** [comment]
Hi, did you manage to make it work at the end? If yes, how? thanks
