### ISSUE TITLE
error on windows server when installing

### ISSUE THREAD

**Issue by Wqrld** [octalmage/robotjs#454]
expected: robotjs installs fine as a package

what happened:
screenshot as this was rdp
[screenshot](https://i.wqrld.net/Wqrld_FX)

**Comment by Wqrld** [comment]
Why is it even trying to use 15 year old libraries and programs that dont exist anymore

**Comment by vithmel** [comment]
Try this:
[https://github.com/octalmage/robotjs/issues/398#issuecomment-392380641](https://github.com/octalmage/robotjs/issues/398#issuecomment-392380641)

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
