### ISSUE TITLE
Turkish Characters not working via typeString on Windows

### ISSUE THREAD

**Issue by emreabaci** [octalmage/robotjs#456]
I am working remote control app and I use typeString keyboard API with Turkish characters(ÇçĞğİıÖöŞşÜü) in my app. Normal characters is working (abcd...) but Turkish characters is not working. How can I fix this issue? 
## Expected Behavior

robotjs.typeString("ç")
## Current Behavior

nothing or diffrence action some turkish characters.
I am testing this API in MS Word and results:
robotjs.typeString("ç") => nothing
robotjs.typeString("ş") => _
robotjs.typeString("i") => MS Word Print action
.
.
.
Additional info: I used robotjs.keyTab API with this Turkish charachters and result is invalid character error.
## Your Environment

* RobotJS version: v0.5.1
* Node.js version: v10.11.0
* npm version:
* Operating System: Windows 10 Pro N (x64) Turkish
* Electron.js version: v4.0.3

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
