### ISSUE TITLE
fatal error: X11/extensions/XTest.h: No such file or directory

### ISSUE THREAD

**Issue by EDMB-QA** [octalmage/robotjs#457]
Getting error in build. 

## Current Behavior
11:58:07     toggleKeyCode(key, down, flags);
11:58:07                                   ^
11:58:07   CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
11:58:07   CC(target) Release/obj.target/robotjs/src/mouse.o
11:58:07 ../src/mouse.c:12:35: fatal error: X11/extensions/XTest.h: No such file or directory
11:58:07   #include <X11/extensions/XTest.h>
11:58:07                                    ^
11:58:07 compilation terminated.
11:58:07 robotjs.target.mk:117: recipe for target 'Release/obj.target/robotjs/src/mouse.o' failed

I have tried to run sudo apt-get install libxtst-dev libpng++-dev. But got apt-get command not found error.

Need your help to resolve the issue.

**Comment by sridharatphotoboxdotcom** [comment]
Can someone help me to resolve this issue please

**Comment by s1hofmann** [comment]
> But got apt-get command not found error.

Which Linux distribution are you running?

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.

**Comment by igorcmelo** [comment]
> > But got apt-get command not found error.
> 
> Which Linux distribution are you running?

Hey. I am having this issue when I run `npm i robotjs`.
My Linux distro is Ubuntu 20.04 LTS.
