### ISSUE TITLE
node-gyp rebuild with electron node_headers does not work

### ISSUE THREAD

**Issue by rr326** [octalmage/robotjs#458]
## Expected Behavior
It should properly

## Current Behavior
The build fails

## Steps to Reproduce (for bugs)

1. Follow the steps to build electron [here](https://electronjs.org/docs/development/build-instructions-gn)
2. Then try `npm test`. This will go to `node_modules/robotjs` and do a `node-gyp rebuild`. This fails.

## Context
I can't get Electron's test environment to build properly. Please see [this electron issue](https://github.com/electron/electron/issues/16746) especially the debugging in [this comment](https://github.com/electron/electron/issues/16746#issuecomment-461077640)

Also, this is far outside my expertise. @nornagon suggested posting an issue here. Hopefully you can figure out what's going on becausue I can't. 

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: 10.15.0
* npm version: 6.4.1
* Operating System: macOS

**Comment by nornagon** [comment]
NB this is an issue with Electron 5, which is based on (pre-release) node 12.

You can build against this version with:

```sh
export npm_config_runtime=electron
export npm_config_disturl=https://atom.io/download/electron
export npm_config_target=5.0.0-beta.2
npm i
```

**Comment by nornagon** [comment]
Also, it looks like these build errors might be related to the removal of the long-deprecated `v8::Handle`, see https://electronjs.org/blog/nodejs-native-addons-and-electron-5 for more info.
