### ISSUE TITLE
Can't get drag working

### ISSUE THREAD

**Issue by MrAmericanMike** [octalmage/robotjs#461]
So I don't know if I'm doing something wrong, or if the drag is just not working

## Expected Behavior
The robot should hold click on the page and drag in a desired direction.

## Current Behavior
I see the mouse moving, but apparently it's not holding the left click down

```
moveMouseAndDrag(20, 260, 0, 200, 2);

    function moveMouseAndDrag(fromX, fromY, distanceX, distanceY, delay) {
        
        robot.setMouseDelay(delay);
        robot.moveMouse(fromX, fromY);
        robot.mouseToggle("down");
        setTimeout(() => {
            robot.mouseToggle("up");
        }, 5000);
        for(var x = fromX; x <= fromX+distanceX; x++){
            for(var y = fromY; y <= fromY+distanceY; y++){
                robot.dragMouse(x, y);                
            }            
        }
    } 
```

The Toggles do work, as when I try them, I can see the mouse left button is been held down for 5 seconds, however when the drag is happening the screen isn't panning as expected.

So the code works, works for things on my desktop, works for my browser window, however it doesn't work on the Electron Window.

PS: Nevermind the fact that the function is wrong as it wont work correctly when moving in 2 directions. Could the problem be the page I'm trying to run the code on?

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: 10.15.1
* npm version: 6.7.0
* Operating System: Windows 7 - 64

**Comment by ysuliu** [comment]
similar with https://github.com/octalmage/robotjs/issues/389

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
