### ISSUE TITLE
install window_build_tools Waiting for two hours, there was no movement.

### ISSUE THREAD

**Issue by jerry94test** [octalmage/robotjs#462]
C:\Users\Administrator\WebstormProjects\untitled>node -v
v10.15.1

C:\Users\Administrator\WebstormProjects\untitled>npm -v
6.4.1

C:\Users\Administrator\WebstormProjects\untitled>npm install --global --production windows-build-tools

Status from the installers:
---------- Visual Studio Build Tools ----------
Still waiting for installer log file...
------------------- Python --------------------
Successfully installed Python 2.7

Waiting for two hours, there was no movement.

**Comment by lhzwb2008** [comment]
same to you

**Comment by AirFusion45** [comment]
try `npm install --global --production windows-build-tools@4.0.0` as referenced in this issue: https://github.com/octalmage/robotjs/issues/398#issuecomment-493817762

**Comment by phancongtaidhsp** [comment]
ctrl+c to break command and install python later

**Comment by oktapodia** [comment]
Please ask them directly https://github.com/felixrieseberg/windows-build-tools :)
