### ISSUE TITLE
Can't install robotjs on Windows

### ISSUE THREAD

**Issue by dimka11** [octalmage/robotjs#464]
## Expected Behavior
package will be installed

## Current Behavior
package isn't installed

## Steps to Reproduce (for bugs)
npm install -g robotjs

## Context
C:\Users\Dima>npm isntall -g robotjs

> robotjs@0.5.1 install C:\Users\Dima\AppData\Roaming\npm\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.9.0 runtime=node arch=x64 platform=win32)

C:\Users\Dima\AppData\Roaming\npm\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Dima\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.18334
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dima\AppData\Roaming\npm\node_modules\robotjs
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dima\AppData\Roaming\npm-cache\_logs\2019-03-01T14_24_41_115Z-debug.log

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: v11.9.0
* npm version: 
* Operating System: 18334.1

**Comment by joshuatz** [comment]
Your Node.js version (v11.9.0) [maps to an ABI # of 67](https://nodejs.org/en/download/releases/#ref-1), but the highest ABI that there is (currently) a [pre-built binary](https://github.com/octalmage/robotjs/releases) for is 59. I had the same issue (I'm on ABI 64) and I had to follow the steps to allow RobotJS to build itself ([Windows instructions](https://github.com/octalmage/robotjs/issues/398#issuecomment-392380641)).

There are a bunch of both open and closed issues that pertain to the build process, so I recommend searching around if you or anyone else gets stuck. The readme should probably also make it clearer that if a pre-built does not exist, your computer is going to try and build it immediately when running npm install, without a more verbose error.

**Comment by Sonecaa** [comment]
npm install --global --production windows-build-tools

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.

**Comment by haider11234** [comment]
This is still continue because i'm facing the same can't install this module i think python is much better in installing modules

**Comment by mrkefir4ik** [comment]
faced same stuff here

**Comment by david-fiaty** [comment]
same here. it's a true nightmare to install on windows 10

**Comment by ReBo6250** [comment]
same issue

**Comment by FujiwaraChoki** [comment]
Facing same issue.
