### ISSUE TITLE
Image search using opencv

### ISSUE THREAD

**Issue by tiaod** [octalmage/robotjs#465]
What about using the opencv to search the image?
https://github.com/justadudewhohacks/opencv4nodejs/blob/dcaf4c5950b0120d12724cc2894c75b45f273be3/examples/templateMatching.js

**Comment by s1hofmann** [comment]
You might take a look at [nut.js](https://github.com/nut-tree/nut.js) where I built exactly that on top of robotjs and opencv4nodejs.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
