### ISSUE TITLE
robotJs Unable to fire click event on chrome browser.

### ISSUE THREAD

**Issue by SauravSuman980** [octalmage/robotjs#468]
robotJs Unable to fire click event on chrome browser.

mouseClick is not firing any event on chrome browser. I'm running a javascript code from the cmd and trying to click on a chrome tab. This event gets fired on every other application (even firefox) but the chrome.
## Expected Behavior
mouseClick method is supposed to click on the chrome tab to bring it to forefront.

## Current Behavior
click event not firing up at all when it is supposed to happen on chrome browser. No error either in the console.
![Capture](https://user-images.githubusercontent.com/47598831/54607245-e8dcf500-4a73-11e9-85e7-d1914f3eb823.PNG)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* RobotJS version:
* Node.js version:
* npm version:
* Operating System:

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
