### ISSUE TITLE
npm install failed under windows 

### ISSUE THREAD

**Issue by slifin** [octalmage/robotjs#47]
here is npm-debug.log
http://pastebin.com/pfgVDBrf

**Comment by octalmage** [comment]
Hmm I've seen this before but I'm not sure what causes it. I can't remeber what I had to install if anything to get RobotJS to build under Windows. I'll try to take a look tonight.

**Comment by Deltatiger** [comment]
I seem to be able to build this just fine. I did get an error for Python but a simple --python switch fixed it.
BTW I build using ``` npm install robotjs --python=C:\Python27 ``` (just to be clear. I may have done it differently)

**Comment by Deltatiger** [comment]
Seems to be an issue with install nan? The error logs dont make much sense to me though :smile:

**Comment by octalmage** [comment]
Yeah it's very confusing. @slifin, could you give us the console output from npm install robotjs? I'm more familiar with what those errors mean. :p

Thanks!

**Comment by Deltatiger** [comment]
The ``` '<!(node -e \'require("nan")\')' ``` in the binding.gyp does not seem to be working for me. Had to change it back to ```"<!(node -e \"require('nan')\")"``` to make it build again. Maybe this is causing the error ?

**Comment by octalmage** [comment]
Looks like on Windows you need:

* Python (v2.7.3 recommended, v3.x.x is not supported.
* Visual Studio 2013 (Express works fine!).

These are required for node-gyp to work correctly. 

https://github.com/TooTallNate/node-gyp

I'm working on getting the readme updated.

**Comment by octalmage** [comment]
I got the readme updated to link to the node-gyp readme: 

https://github.com/TooTallNate/node-gyp/#installation

if you're still having issues after installing the requirements please let me know!
