### ISSUE TITLE
moveCursorSmooth only working on Main Monitor (windows)

### ISSUE THREAD

**Issue by Bommel24** [octalmage/robotjs#470]
moveCursorSmooth ignores coordinates outside of the main movitor.

## Expected Behavior
work on all monitors

## Current Behavior
does only work on main monitor

## Possible Solution
let it work on all monitors

## Steps to Reproduce (for bugs)
1. set coordinates to second monitor (eg.: 2050, 50)
2. see the cursor not moving to the second monitor

## Context
I try to move the cursor to another monitor

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: v10.5.0
* Operating System: Windows 10

**Comment by ryanhuellen** [comment]
robotjs only supports a single monitor, as per stated by the author.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.
