### ISSUE TITLE
robot.typeString is not working with electron

### ISSUE THREAD

**Issue by islalobo** [octalmage/robotjs#472]
The annoying this with this issue is that it is working for my colleague on their machine, but it isn't working for me and we're at a loss for how to debug.

## Expected Behavior
The expectation is that when the user hits the shortcut, which is successfully registered, that the string will appear on the screen in whatever active window the user has open

```
app.on('ready', () => {
  setTrayItem();

  const ret = globalShortcut.register('Alt+Z', () => {
    robot.typeString("Hello World");
  });

  if (!ret) {
    console.log('registration failed');
  }

});
```

## Current Behavior
Nothing happens

## Your Environment
* RobotJS version: "robotjs": "^0.5.1"
* Electron: "electron": "^4.0.0",
* Chromium 69.0.3497.106, 
* Node 10.11.0, 
* V8 6.9.427.24
* npm version: 6.4.1
* Operating System: macOS 10.14.2

**Comment by kakalote2008** [comment]
the same to me, macOS 10.14.4.
after let the terminal controls my mac, mouse click works well, but the keyboard still no response.

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
