### ISSUE TITLE
Vulnerability in tar-fs

### ISSUE THREAD

**Issue by pronebird** [octalmage/robotjs#476]
Please update tar-fs because of vulnerability found in it today:

<img width="748" alt="Screenshot 2019-05-02 at 15 24 18" src="https://user-images.githubusercontent.com/704044/57078337-5eccb100-6cee-11e9-8df6-9a02b867b5d4.png">

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
