### ISSUE TITLE
[Feature] create canUseKey function

### ISSUE THREAD

**Issue by JCQuintas** [octalmage/robotjs#477]
Create a function that, given a string, return if the key is implemented and can be used in scripts. Would help prevent crashes when using outside input.

Example usage:

```javascript
robotjs.canUseKey('汉') // false

robotjs.canUseKey('a') // true
```

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
