### ISSUE TITLE
Running RobotJS on GlobalMu online - Win 10

### ISSUE THREAD

**Issue by gloatoriginal** [octalmage/robotjs#480]
I am trying to setup an autoclicker for GlobalMu online, I am on Windows 10, I am using the latest robotjs installation, the game is in window mode.
## Expected Behavior
I expect the mouseclick to behave the same on my desktop as it does in the game window

## Current Behavior
The mouse click event works outside of the game, and I can even have the mouseclick the tab for the game, but when in game it doesn't recognize any mouse events from robotjs. ?

## Possible Solution
Would this be Windows, I'm assuming the game maybe has a blocker?

## Steps to Reproduce (for bugs)
1.Here is my Code
`var robot = require("robotjs");

setInterval(function () {
    var now = new Date();
    robot.mouseClick("right");
    console.log(now.getHours() + ":" + now.getMinutes() + ":" + now.getSeconds());
    console.log("success");
}, 1000);`

2.I am able to node app.js and start the app, and get the console logs the whole time
3.I am receiving right clicks everywhere on my desktop, however the game doesn't recognize any clicks (windowed mode)
4. Any help is sincerely appreciated, I've searched on other topics and I might be missing something and apologize if I have.

## Context
Nothing too terrible, I'm just having fun with botting, not trying to ruin any games or get out of control, I just enjoy automation. any help or response is appreciated, I understand if you don't support specific games.

## Your Environment

* RobotJS version:  "robotjs": "^0.5.1"
* Node.js version: v10.15.0
* npm version: 6.4.1
* Operating System: Windows 10 Enterprise 64bit

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
    You may reopen this issue if it has been closed in error.
