### ISSUE TITLE
add MouseWheel

### ISSUE THREAD

**Issue by wanglong167** [octalmage/robotjs#49]
rt MouseWheel

**Comment by Deltatiger** [comment]
@octalmage I will start working on this in Windows.

**Comment by octalmage** [comment]
@Deltatiger sounds good! I believe someone already started this, let me find the fork.

**Comment by octalmage** [comment]
@Deltatiger @anand-seeenivasagam started it here: 

https://github.com/anand-seeenivasagam/robotjs/blob/4b8d11a26046dc6e97acf23b768e043c4c3332a2/src/mouse.c#L127

But, it's missing the Windows code. So please have at it! 

Once you get your branch up and running create a PR and I'll add the Mac/Linux code.

**Comment by wanglong167** [comment]
tks

**Comment by killroy42** [comment]
Has this feature progressed in the meantime? I'm afraid my C-fu is not sufficient to pick up the torch.

**Comment by octalmage** [comment]
@killroy42 It's implemented! 

https://github.com/octalmage/robotjs/wiki/Syntax#scrollmousemagnitude-direction
