### ISSUE TITLE
Numlock, Scrolllock, Capslock and break key support

### ISSUE THREAD

**Issue by innovate-invent** [octalmage/robotjs#490]
There is no support for typing the "Break" key or toggling "Capslock".
https://en.wikipedia.org/wiki/Break_key

## Expected Behavior
var robot = require("robotjs");
robot.keyTap("break");
robot.keyTap("numlock"); //Toggle numlock
robot.keyToggle("numlock", "down") // Enable numlock
robot.keyToggle("numlock", "up") // Disable numlock
robot.keyTap("scrolllock"); //Toggle scrolllock
robot.keyToggle("scrolllock", "down") // Enable scrolllock
robot.keyToggle("scrolllock", "up") // Disable scrollock
robot.keyTap("capslock"); //Toggle capslock
robot.keyToggle("capslock", "down") // Enable capslock
robot.keyToggle("capslock", "up") // Disable capslock

## Current Behavior
Unimplemented or undocumented.

## Context
I am using robotjs to implement a keyboard macro feature. The end user might have a use case requiring that key to be pressed.

Partial duplicate of #385

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
