### ISSUE TITLE
Error when using screen functions on ChromeOS

### ISSUE THREAD

**Issue by Kline-** [octalmage/robotjs#491]
## Expected Behavior
Trying the sample scripts to display pixel colors works properly.

## Current Behavior
The script crashes with an error. Seems to be anything using screen functions. Mouse functions work fine.

Console output:
<pre>X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  7
  Current serial number in output stream:  7</pre>

## Steps to Reproduce (for bugs)
1. Attempt to run any script using screen functions on ChromeOS (stable) via the Linux beta support.

```javascript
var robot = require("robotjs");

function mpos() {
	var mouse = robot.getMousePos();
	var img = robot.screen.capture();
	var color = img.colorAt(mouse.x,mouse.y);
	console.log("Mouse is at x:" + mouse.x + " y:" + mouse.y);
	console.log("Color is: " + color);
	setTimeout(mpos,5000);
}
mpos();
```

## Context
In the spirit of the project being an AHK substitute on Mac I'm looking for an AHK substitute on ChromeOS.

## Your Environment
* RobotJS version: 0.5.1
* Node.js version: 10.16.0
* npm version: 6.9.0
* Operating System: ChromeOS 74 / Debian 9.7

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
