### ISSUE TITLE
robot.screen.capture results in blank image

### ISSUE THREAD

**Issue by xmxstudio** [octalmage/robotjs#494]
calling robot.screen.capture() or robot.screen.capture(0,0,1920,1080) and saving to disk results in a blank(all black) image of correct dimensions.

## Expected Behavior
it should capture the desktop and provide a valid image

## Current Behavior
it creates a valid size but all black image.

## Steps to Reproduce (for bugs)

1. `var screenCaptureToFile = function(path) {

    return new Promise((resolve, reject) => {

        try {

            var picture = robot.screen.capture(0,0,100,100);

            var image = new jimp(picture.width, picture.height, function(err, img) {

                img.bitmap.data = picture.image;

                img.getBuffer(jimp.MIME_PNG, (err, png) => {

                    image.write(path, resolve);

                });

            });

        } catch (e) {

            console.error(e);

            reject(e);

        }

    })`
2. call screenCaptureToFile('test.png')
3. open result test.png to find correct dimensions but all black

## Context
I'm running an express website where a user clicks a button to save the servers desktop screenshot so it can be further processed and then served. I've tried running it via nodemon, sudo nodemon, npm start, sudo npm start. Nothing seems to be working. It appears as though the capture desktop function doesnt work with my current setup.

## Your Environment

* RobotJS version:  not sure
* Node.js version: 8.2.1
* npm version: 6.10.1
* Operating System: Kubuntu 18.04lts ..  i3wm, plasma/kde, mate, cinnamon ... x11

**Comment by Waxo** [comment]
Hey,

I tried this according to the docs:
```js
const r = require('robotjs');
const Jimp = require('jimp');
const uuid = require('uuid/v4');

const swapRedAndBlueChannel = bmp => {
  for (let i = 0; i < (bmp.width * bmp.height) * 4; i +=4) { // swap red and blue channel
    [bmp.image[i], bmp.image[i+2]] = [bmp.image[i+2], bmp.image[i]]; // red channel
  }
};

const screen = async f => {
  const bmp = r.screen.capture(1537,66,1016,631);
  swapRedAndBlueChannel(bmp); // possible side effect using a pointer here
  const img = new Jimp({data: bmp.image, width: bmp.width, height: bmp.height});
  img.write(`out/${f}-${uuid()}.jpg`);
};

screen('bob');
```

This works for me

**Comment by brandonwaring** [comment]
If you're using MacOS I would suggest using the native screen capture. It's much more efficient, plus you have tons of options such as record video. Run `screencapture -help` to see the list. 

I was converting 400x600 screen captures using robotjs and jimp to save a file at around 45 seconds. Using screen capture was instant. 

This is what worked for me, and there are other ways to interact with terminal as well. 
`
const shell = require('shelljs');
// -R flag to define coordinates 
shell.exec('screencapture -R 0,0,400,600 ~/dev/bot/test2.png');
`

**Comment by brandonwaring** [comment]
Probably should add, from what I understand the capture method on robot JS creates the bit map, and you need to get the color from each pixel and assign it to the image you create. Hence why it takes a while to build an image when its larger. 

`
let jimg = new Jimp(w, h);

for (let x = 0; x < w; x++) {

    for (let y = 0; y < h; y++) {

		stamp = Date.now();

        // hex is a string, rrggbb format

        let hex = rimg.colorAt(x, y);

        // Jimp expects an Int, with RGBA data,

        // so add FF as 'full opaque' to RGB color

        let num = parseInt(hex+"ff", 16)

        // Set pixel manually

        jimg.setPixelColor(num, x, y);

    }
}
`

**Comment by oktapodia** [comment]
It looks like this issue has been resolved, closing.
You may reopen this issue if it has been closed in error.
