### ISSUE TITLE
getPixelColor crashes process if UAC prompt is open

### ISSUE THREAD

**Issue by Venryx** [octalmage/robotjs#495]
## Expected Behavior
I expect that calling getPixelColor will never cause my whole node-js program to crash, without an error message or anything else to help find the cause.

## Current Behavior
The above. I have a timer in my program that checks the color of a pixel each second. I noticed that occasionally my program would just crash without any error message.

After quite a bit of debugging (commenting out tons of stuff), I eventually found it is caused by a call to `getPixelColor` that occurs when a Windows UAC prompt is open. When this happens, apparently my entire program crashes -- and no info whatsoever is provided in the console as to why.

## Possible Solution
Whatever is causing the library to crash (and thereby the whole node-js program) when accessing the pixel-color (with UAC prompt open), should have error checking around it. (or whatever else needs to be done here -- not sure of the low-level details)

## Steps to Reproduce (for bugs)

Reproduction is simple.

1. Create a new folder.
2. Create a file `Main.js` with this code:
```
let robotjs = require("robotjs");
setInterval(()=> {
	robotjs.getPixelColor(0, 0);
}, 1000);
```
3. Create a file `package.json` with this content:
```
{
  "name": "get-pixel-color-uac-bug",
  "dependencies": {
    "robotjs": "0.5.1"
  }
}
```
4. Run `npm install` in folder.
5. Run `node Main.js`. You'll see that the program keeps running since a timer is active.
6. Cause a UAC prompt to open, by trying to open something as an Administrator.
7. Go back to the terminal. You'll see that the node process has crashed without any information given.

## Context
It's causing my automation helper program to crash whenever I run something as administrator. The fact that try-catch blocks and other node-js-side error-handling do nothing to prevent the whole-program crashing makes it difficult for me to work around other than by asking it be fixed in this library.

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: v8.11.2
* npm version: 5.10.0
* Operating System: Windows 10 (x64)

**Comment by Venryx** [comment]
In the meantime, I'm using this alternate way of getting a pixel's color (using [node-ffi](https://github.com/node-ffi/node-ffi)):
```
import ffi from "ffi";
import chroma from "chroma-js";

var user32 = new ffi.Library("user32", {
	"GetDC": ["int32", ["int32"]],
	"ReleaseDC": ["int32", ["int32", "int32"]],
});
var gdi32 = new ffi.Library("gdi32", {
	"GetPixel": ["uint32", ["int32", "int32", "int32"]],
});

export function GetPixelColor(x: number, y: number) {
	let hdc = user32.GetDC(0);
	let pixel = gdi32.GetPixel(hdc, x, y);
	user32.ReleaseDC(0, hdc);
	let color = chroma(pixel & 0x000000FF, (pixel & 0x0000FF00) >> 8, (pixel & 0x00FF0000) >> 16);
	return color.hex().substr(1); // to match with robotjs.getPixelColor() returns
}
```

Works fine, though it probably has worse performance than robotjs since it uses ffi -- [which apparently is relatively slow according to the creators](https://github.com/node-ffi/node-ffi#call-overhead). (though it's seemed fine for my uses)

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 90 days.
You may reopen this issue if it has been closed in error.
