### ISSUE TITLE
Support of newer node, electron 

### ISSUE THREAD

**Issue by SimanovichSiarhei** [octalmage/robotjs#498]
Hi @octalmage, 

First of all many thanks for your job done in this module.
I'd like to ask for a push of newer prebuilt binaries to the repo to support newer versions of electron (5.x and 6.x).

I guess community here will really appreciate they can continue use this awesome module in their projects, thanks in advance

**Comment by danutzcodrescu** [comment]
+1

**Comment by oktapodia** [comment]
A new version of robotjs supporting the latest NodeJS version will be published soon.
