### ISSUE TITLE
Logo/Mascot.

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#5]
I'd like a little robot mascot for RobotJS. 

I'm a fan of the PhoneGap robots: 

![](http://phonegap.com/css/images/graphic_build_bot.png)

and these: 

![](http://i.imgur.com/ntg5D86.jpg)

Definitely something vector and friendly.

**Comment by ariporad** [comment]
What if we did something Wizard-of-Oz-related, but with a robot instead of a person? ie. ~~Man~~ Robot behind the screen? That sounds kind of terrible, but a robot in a hot-air balloon might work.

**Comment by octalmage** [comment]
I like it, just seems difficult to convey with a logo. The idea of a robot controlling something makes sense for the project though!

**Comment by raphaelbastide** [comment]
What about just a robot’s hand? Simple enough to be a logo, and pretty exclusive!

Here is a (really) quick draft:

![robotjs](https://cloud.githubusercontent.com/assets/193122/8981965/fc1b9e10-36bc-11e5-8ad4-fe3df14afdbc.png)

**Comment by octalmage** [comment]
I like it, but I really want a cute little robot. I think @mjchamplin is going to put something together.

**Comment by mjchamplin** [comment]
##Full Disclosure, I hadn't looked at this thread before I started. I could definitely expand on this and make it 3d / isometric if that's what we're into.

![robot](https://cloud.githubusercontent.com/assets/1672613/9590213/dd83fff6-4ff8-11e5-8359-25e6be7ce522.png)
The original, full-sized robot. 

![logobot](https://cloud.githubusercontent.com/assets/1672613/9590283/4fc881ea-4ff9-11e5-9245-81822716518c.png)
The smaller "logobot" who is simpler with less detail, for icon display or possibly with the "RobotJS" wordmark.
