### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file ' ■/.obj'

### ISSUE THREAD

**Issue by Adrriii** [octalmage/robotjs#500]
This happens when installing. I'm just trying to use this as a dependency.

## Steps to Reproduce (for bugs)
1. npm install --global --production windows-build-tools
2. npm install -g node-gyp
3. node-gyp rebuild
4. npm install robotjs
5. npm install

## Your Environment
I have both VS2017 and VS2019 installed, but had to install MSBuild (which it is using, see screenshot).
I have .NET SDK 2.0, 2.1 and 2.2 installed.
* RobotJS version: 0.5.1
* Node.js version: v10.15.3
* npm version: 6.10.3
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/16978299/62712744-b79d9b00-b9fb-11e9-8cf3-28f7a713d4b0.png)

**Comment by oktapodia** [comment]
You need to install the `windows-build-tools` first on windows. Please follow [the documentation](https://github.com/octalmage/robotjs#building)

**Comment by Adrriii** [comment]
Well, as I said, they were installed globally. If you look at the step i took, they are from the documentation.

I since have found another way though, so thanks
