### ISSUE TITLE
typeString 请教提交中文字符串utf-8编码格式的方法

### ISSUE THREAD

**Issue by webyou0** [octalmage/robotjs#502]
类似这样的执行，不能填充到我需要的区域
robot.typeString('中文'); 
请问是否有特别的方法或者后续升级您的程序

**Comment by 12Tall** [comment]
看下这篇文章或许有用：[将中文暂存到剪切板](https://blog.csdn.net/zhang767653317/article/details/59590522?utm_source=blogxgwz9)

**Comment by 12Tall** [comment]
好像太久了~  
写了一个极简单的Addon，在win 下应该可用。  
<https://github.com/12Tall/nc/tree/master/nc_keyboard>

**Comment by oktapodia** [comment]
Sorry, can you please write in english?

**Comment by 12Tall** [comment]
> Sorry, can you please write in English? Closing this one.

Thank you @oktapodia,there are many programmers  want to  type both unicode and ascii string like Chinese directly with robot.js. so we are wandering will it be provided in new version.
