### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by SpencerC** [octalmage/robotjs#51]
On OSX, calling getMousePos() when on a monitor above my main screen returns: { x: 293, y: 18446744073709552000 }

Requesting the mouse position through cocoa returns the mouse position relative to the origin of the main screen, for example: { x: 293, y: -291 }

**Comment by octalmage** [comment]
Hey @SpencerC! This was fixed in #48, I just haven't published it to npm yet. Try using RobotJS from master and let me know how it works! 

I'll get a new version published tonight.

**Comment by octalmage** [comment]
I just published RobotJS v0.2.2 which resolve this. If you're still having issues please let me know!
