### ISSUE TITLE
错误	C2660	 “v8::Value::Int32Value”: 函数不接受 0 个参数	robotjs	..node_modules\robotjs\src\robotjs.cc

### ISSUE THREAD

**Issue by LiYongYi** [octalmage/robotjs#510]
错误	C2660	 “v8::Value::Int32Value”: 函数不接受 0 个参数	robotjs	..node_modules\robotjs\src\robotjs.cc

**Comment by psvmc** [comment]
I have the same problem

**Comment by iziziziziziz** [comment]
I have the same problem

**Comment by oktapodia** [comment]
A new version of robotjs supporting the latest NodeJS version will be published soon.

**Comment by liketurbo** [comment]
1. Please use `nvm` and switch to the version `node@8`
2. Complete installation of all prerequisites from [node-gyp](https://github.com/nodejs/node-gyp)

**Comment by dalang81** [comment]
版本升级就好了
