### ISSUE TITLE
Error running robotjs on electron

### ISSUE THREAD

**Issue by Angshu1** [octalmage/robotjs#534]
I tried to rebuild robotjs then this error https://imgur.com/a/eVAB26i
after i tried to start then this error https://imgur.com/a/9zjHfNq

any help would be appreciated 
 
## Environment

* RobotJS version:lastest
* Node.js version:lastest
* npm version:latest
* Operating System:win 10 64Bit

**Comment by oktapodia** [comment]
Are you sure that you followed that part of the documentation? https://github.com/octalmage/robotjs#building

Also, please set the versions in your issue

**Comment by Angshu1** [comment]
> Are you sure that you followed that part of the documentation? https://github.com/octalmage/robotjs#building
> 
> Also, please set the versions in your issue

Yep did everything

**Comment by mznet** [comment]
@Angshu1 This problem doesn't seem a robotjs problem. A related issue has been [opened](https://github.com/nodejs/node-gyp/issues/1933). I'm not a windows user and can't help you directly but this link would be able to resolve your problem.

**Comment by oktapodia** [comment]
Thank you @mznet, closing it
