### ISSUE TITLE
scrollMouse not working

### ISSUE THREAD

**Issue by Veiintc** [octalmage/robotjs#538]
## Expected Behavior

robot.scrollMouse(50, 50);
## Current Behavior

It not work;
## Possible Solution

when I replaced 
	SendInput(2, mouseScrollInputs, sizeof(mouseScrollInputs));
with
        SendInput(1, &mouseScrollInputs[0], sizeof(mouseScrollInputs[0]));
        SendInput(1, &mouseScrollInputs[1], sizeof(mouseScrollInputs[1]));
It work;

## Your Environment

* RobotJS version:0.6.0
* Operating System:win10

The scrollMouse does not work, or maybe I doing something wrong?

**Comment by Momo707577045** [comment]
only your answer is right

**Comment by Momo707577045** [comment]
### window 环境，scrollMouse 不生效问题
- 修改 node_modules\robotjs\src\mouse.c
- 修改 345 行代码 ```SendInput(2, mouseScrollInputs, sizeof(mouseScrollInputs));```
  修改为 ```
  SendInput(1, &mouseScrollInputs[0], sizeof(mouseScrollInputs[0]));
  SendInput(1, &mouseScrollInputs[1], sizeof(mouseScrollInputs[1]));
  ```
- 进入 node_modules\robotjs 目录，命令行执行 ```npm run install```
- 看到 node_modules\robotjs\build\Release\obj\robotjs\src\mouse.obj 文件的创建日期被更新
- 证明修改成功，重新程序即可看到最新效果

**Comment by Veiintc** [comment]
兄弟，中国人呀，这个问题好像官方已经合并代码可以了，只是一直没有发新版本，你可以看一下508的pr #508 
this problem is fixed  #508

**Comment by leoxiaoping** [comment]
老乡见老乡

**Comment by dexterllait25** [comment]
Great Leoxiaoping, it works well for me.
Thank you very much
