### ISSUE TITLE
Maximum typing speed is rather slow

### ISSUE THREAD

**Issue by gavin-haynes-grow** [octalmage/robotjs#547]
Why does keypress.c always sleep 62-125 ms per tap?

**Comment by bm-kenji-nakamura** [comment]
https://github.com/octalmage/robotjs/issues/530

**Comment by PatrykSitko** [comment]
Have same issue. My app cannot work properly because of this issue. Changed to 1 by hand. [[Project](https://github.com/PatrykSitko/pokken-dx-tournament-controller-pc)]
