### ISSUE TITLE
moveMouse() Apply values incorrectly

### ISSUE THREAD

**Issue by Sergey-Churilin** [octalmage/robotjs#561]
## Expected Behavior
robot.moveMouse() apply values correctly.

## Current Behavior
robot.moveMouse() add offset to passed values

## Steps to Reproduce (for bugs)
Precondition
You should have two displays.
Issue is reproduced when your opened window is on the second display.

1. Clone or download sample from https://github.com/Sergey-Churilin/robot-sample
2. Perform all the steps from Readme.
3. Run the app and move the window to the secondary display
4. During app running, change position of displays in Display Settings of the OS

In the sample I just apply values from mouse position on click event.
I don't think that it is reproducible only in connection with Electron

## Your Environment
* RobotJS version: 0.6.0
* Node.js version:12.16.1
* npm version: 6.13.7
* Operating System: Window 10

**Comment by Kyusung4698** [comment]
Hi, i actually run into this issue as well. You can call `.updateScreenMetrics()` to update the cached system metrics prior moving the mouse. This seems to get cached once [here](https://github.com/octalmage/robotjs/blob/24231df7641abb778ce5add71a91a5faf4dbb597/src/mouse.c#L129).

**Comment by Sergey-Churilin** [comment]
Hi @Kyusung4698 , thanks for idea, it solves my problem!
