### ISSUE TITLE
Domain Name. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#58]
I'm going to start working on branding and I'd like to find a good domain. This will later host the forums and possibly a blog. 

On Twitter I have @robotjavascript, but robotjavascript.com is taken. And of course robotjs.com is taken. robotjs.io is open but it's a little pricy and I feel like I want something more creative. That's probably what I'll fallback on if I can't find anything else. 

Maybe something like robotjs.rocks? Or AutomationIs.cool?

Hit me with your suggestions!

**Comment by Zero2020** [comment]
How about botjs, or maybe autobot.js but then again that might not be where you want to go with it. I will keep thinking about it. This is my first time here, and when i seen that you were into autohotkey i was sold in helping if i can.

**Comment by octalmage** [comment]
We're keeping the name RobotJS! I was looking for a domain name. 

And I appreciate it!

**Comment by 1j01** [comment]
Domain | Price | Link
---------|----------|--------
robotjs.tk | FREE | [Get it now!](https://my.freenom.com/domains.php)
robotjs.ml	 | FREE | [Get it now!](https://my.freenom.com/domains.php)
robotjs.ga | FREE | [Get it now!](https://my.freenom.com/domains.php)
robotjs.cf | FREE | [Get it now!](https://my.freenom.com/domains.php)
robotjs.gq | FREE | [Get it now!](https://my.freenom.com/domains.php)

Cheers :smile:

**Comment by maxbook** [comment]
it's so simple robotjs.io :D

**Comment by maxbook** [comment]
And is available :)

**Comment by dkrutsko** [comment]
oh nice, robotjs.io is available for 50 bucks over at hover, I remember those used to cost closer to 80.

**Comment by 1j01** [comment]
@dkrutsko or [$32.88/year at namecheap](https://www.namecheap.com/domains/registration/results.aspx?domain=robotjs&tlds=io)

**Comment by dkrutsko** [comment]
@1j01 Oh nice, even better! Though I *might* have been suckered into paying the extra twenty bucks for the convenience of having all my domains in one place. robotjs.net also appears to be available. I wish I was this lucky with my project domains.

**Comment by aequasi** [comment]
+1 for robotjs.io

**Comment by Kickball** [comment]
+1 for robotjs.io

**Comment by petre2dor** [comment]
+1 for robotjs.io

**Comment by sungwoncho** [comment]
robotjs.io sounds perfect.

**Comment by octalmage** [comment]
Agreed! I'll make it happen! 

Thanks for the input everyone.
