### ISSUE TITLE
mouseClick() resets mouse location

### ISSUE THREAD

**Issue by yogurtsyum** [octalmage/robotjs#581]
## Expected Behavior

It clicks at the current mouse location.

## Current Behavior

It clicks at the top left of the screen even if thats not the current mouse location.

## Steps to Reproduce (for bugs)

1. Try <robotjs>.mouseClick();
2. 
3. 
4. 

## Context

To click at the current mouse location.

## Your Environment

* RobotJS version: 0.6.0
* Node.js version: 12.14.0
* npm version: 6.13.4
* Operating System: macOS

**Comment by samupp2758** [comment]
Same Here!

**Comment by yogurtsyum** [comment]
Just to confirm, I am still having this issue. It appears this repository's issues are being closed because they are old even though they weren't resolved.

**Comment by IndyVC** [comment]
I am not having this issue. Post full code so they can really look at it.
