### ISSUE TITLE
installing Robotjs in windows

### ISSUE THREAD

**Issue by kshirish** [octalmage/robotjs#59]
See the attached image, I am unable to install it on windows. Tell me if you need additional information about the steps.

![capture](https://cloud.githubusercontent.com/assets/5382293/9001723/b7b5a7e0-3778-11e5-93f3-9388398ccbe0.PNG)

**Comment by octalmage** [comment]
It looks like you're using a pretty old version of node-gyp, could you try updating, then re-compiling? 

Thanks!

**Comment by octalmage** [comment]
I'm going to close this, if you're still having issues after updating please let me know!
