### ISSUE TITLE
Trigger Cursor style changes

### ISSUE THREAD

**Issue by zachatrocity** [octalmage/robotjs#61]
I was wondering if it would be possible to add the ability to trigger the different cursors like wait, pointer,  cross. I know in C++ for windows it can be done using the [Set Cursor](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648393%28v=vs.85%29.aspx) function. I'm open to submitting a pull request I just wanted to check and see if that's even doable. 

In linux it could possibly be done like the answer to [this](http://stackoverflow.com/questions/3583746/c-change-the-cursor-in-an-x-window) stackoverflow post.

**Comment by octalmage** [comment]
It's doable, but it think it would be better as a separate module. I'll take a look and see what I can put together.

**Comment by octalmage** [comment]
Unfortunately I'm having a difficult time finding a way to do this on Mac. I might still make this though, I want the ability to hide/show the mouse and that functionality could be apart of the same library.

**Comment by zachatrocity** [comment]
That would be awesome! Thanks for your hard work.

**Comment by octalmage** [comment]
No problem! Thanks for the idea!

**Comment by dkrutsko** [comment]
This is a pretty cool suggestion by the way, thanks! Qt and maybe SDL would be good reference points if you're looking for a way to implement it.

**Comment by petre2dor** [comment]
+1 for the idea

**Comment by Zeukkari** [comment]
+1

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 240 days.
    You may reopen this issue if it has been closed in error.

**Comment by EmptyCrown** [comment]
Hello! Has there been any update on this? Didn't see anything in the documentation. I'm specifically interested in just being able to hide the cursor on Windows.
