### ISSUE TITLE
Failed to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by MaxioTech** [octalmage/robotjs#616]
When I tried to install it with `npm install robotjs` on Ubuntu 20.04 it failed.

## Expected Behavior
Install

## Current Behavior
Fails to install on Ubuntu 20.04

## Possible Solution
...

## Steps to Reproduce (for bugs)
...

## Context
I don't know why it should fail as both npm and node is both the lastest version.

## Your Environment
* RobotJS version: 0.6.0
* Node.js version: 14.14.0
* npm version: 6.14.8
* Operating System: Ubuntu 20.04 Linux x64

**Comment by MaxioTech** [comment]
## [FIXED]
I fixed the issue.

**Comment by pazzazzo** [comment]
How ?
