### ISSUE TITLE
robotjs does not install

### ISSUE THREAD

**Issue by RadiantUwU** [octalmage/robotjs#618]
## Expected Behavior

for the module to install
## Current Behavior

![image](https://user-images.githubusercontent.com/69520693/97426341-fe86f180-191b-11eb-9643-c18c23e5bfd3.png)

## Possible Solution

fix
## Steps to Reproduce (for bugs)

1.make it with a folder with unicode characters()
2.have same version of npm, nodejs, node-gyp and windows
3.install the module
4. get the error

## Context

I cannot install it
## Your Environment

* RobotJS version:latest for 28(d).10(m).2020
* Node.js version:v12.18.2
* npm version:v6.14.5
* Operating System:Windows 10 build 18362 x64

**Comment by RadiantUwU** [comment]
This issue will be closed, i found out its a node-gyp issue, not a robotjs issue

**Comment by pazzazzo** [comment]
How to solve it ?

**Comment by RadiantUwU** [comment]
> How to solve it ?

this is so old i actually forgot how i fixed it.
