### ISSUE TITLE
Looking for an actively maintained fork

### ISSUE THREAD

**Issue by Chappie74** [octalmage/robotjs#620]
Is there anyone out there that has an actively maintained/updated fork? It's a really good library but it looks like the devs aren't around anymore.

**Comment by s1hofmann** [comment]
I’m working on https://github.com/nut-tree/nut.js, an enhanced framework for desktop automation combining possibilities of robot-js with image matching via OpenCV.

It provides a nice API and additional features like highlighting desktop regions or retrieval of window coordinates / dimensions.

**Comment by KaKi87** [comment]
Although it won't return any interesting result in `robotjs`' case, you can firstly try [`useful-forks`](https://useful-forks.github.io/) when looking for, well, useful forks.

This tool helped me many times.

Have a nice week-end

**Comment by Chappie74** [comment]
Thank you. 🙂
