### ISSUE TITLE
Document website not available

### ISSUE THREAD

**Issue by QimatLuo** [octalmage/robotjs#623]
looks the domain is expired

**Comment by italodeandra** [comment]
Project is dead. RIP.

**Comment by italodeandra** [comment]
But for who's looking for an alternative for the documentation though: [Archive](https://web.archive.org/web/20200415014758/https://robotjs.io/docs/syntax)

**Comment by s1hofmann** [comment]
@QimatLuo @italodeandra In case you’re looking for an actively maintained alternative, I’m working on https://github.com/nut-tree/nut.js, an enhanced framework for desktop automation combining possibilities of robot-js with image matching via OpenCV.

It provides a nice API and additional features like highlighting desktop regions or retrieval of window coordinates / dimensions.

**Comment by bm-kenji-nakamura** [comment]
https://nicedoc.io/octalmage/robotjs

@QimatLuo Maybe moving here.
