### ISSUE TITLE
Keyboard API complete?

### ISSUE THREAD

**Issue by Hypercubed** [octalmage/robotjs#63]
Great work getting this working on windows.  NPM install is now no problem for me.

I'm wondering if the keyboard api is complete (the readme indicates it is)?  In AutoHotkey the send function accepts a minilanguage like: "{End}Sincerely,{enter 4}John Smith"  Any plans to implement that in robotjs... or should write my own wrapper?

**Comment by octalmage** [comment]
This is something we're discussing in #4. I think I want to implement something like this in Node and have it call the necessary C functions. Then you can run robot.keyboard.type("hello{enter}").  

I'm not sure yet, still focusing on features. This will probably be the last step towards 1.0.0.

**Comment by octalmage** [comment]
Also thanks! I'm so happy we got everything working. 

By complete I just mean you can accomplish everything, the syntax is still up for debate.

**Comment by octalmage** [comment]
I'm going to close this in favor of #4.
