### ISSUE TITLE
Blocking Delay function

### ISSUE THREAD

**Issue by Deltatiger** [octalmage/robotjs#66]
Some of the times I am having issues were I will have to wait to do something. Currently I am setting a SetTimeout function to achieve this delay. Since we are dealing with C modules why not add such a function to it ? It would use the Sleep in the C module. This will provide some level of code complexity reduction.

Though I may be wrong about it but this is a need that just cropped up.

**Comment by octalmage** [comment]
Every function should have a delay built in, and this resolved this issue for me on Mac. See #15. I would like to make this adjustable so a sleep isn't needed after each function, this is how AHK handles it. While I figure this out you can use this:

https://www.npmjs.com/package/sleep

.

**Comment by octalmage** [comment]
I'm going to close this in favor of #14, let continue this conversation there!
