### ISSUE TITLE
Can i host my server made using RobotJs library on Heroku?

### ISSUE THREAD

**Issue by m-maheshwari-04** [octalmage/robotjs#672]
I was trying to host but there where some issues in deployment. 

make: *** [robotjs.target.mk:120: Release/obj.target/robotjs/src/mouse.o] Error 1
       make: Leaving directory '/tmp/build_499e5fd9/node_modules/robotjs/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_499e5fd9/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
       gyp ERR! System Linux 4.4.0-1088-aws
       gyp ERR! command "/tmp/build_499e5fd9/.heroku/node/bin/node" "/tmp/build_499e5fd9/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_499e5fd9/node_modules/robotjs
       gyp ERR! node -v v11.10.0
       gyp ERR! node-gyp -v v5.1.0
       gyp ERR! not ok 
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! robotjs@0.6.0 install: `prebuild-install || node-gyp rebuild`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the robotjs@0.6.0 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.9J3jU/_logs/2021-06-02T06_07_54_834Z-debug.log
-----> Build failed

**Comment by dantheuber** [comment]
pretty sure you aren't going to have any mouse or keyboards to control on heroku.

**Comment by Edozie101** [comment]
Hey Im just trying to do this too, did you manage to get any instances of robot js running on heroku
