### ISSUE TITLE
Throw error if mouse event is out of bounds.

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#68]

**Comment by dkrutsko** [comment]
I'd argue it's almost better to let the OS take care of that.

**Comment by octalmage** [comment]
Error handling is always better, it can really help when you're debugging an application.

**Comment by aequasi** [comment]
If the OS takes care of it, you can't handle it when it happens though.

**Comment by octalmage** [comment]
On Mac the OS will let you attempt to put the mouse anywhere without error, it just moves to the furthest position it can go. Having RobotJS complain when this happens will let the developer know when there's a potential issue, if they're setting the mouse offscreen there's likely a bug.

**Comment by Deltatiger** [comment]
@octalmage Is it easier than the user using a getMousePos ? . I personally will let the user handle this situation. Or atleast provide an option for him to force such actions. (There maybe intentional use. Though I cannot come up with a solid example now.)

**Comment by octalmage** [comment]
Yeah I'm going to close this for now, I do think it should be implemented, but it breaks whatever multi-monitor support we have.
