### ISSUE TITLE
Ubuntu hides mouse cursor even when moving mouse with RobotJS moveMouse

### ISSUE THREAD

**Issue by HadiModarres** [octalmage/robotjs#686]
Ubuntu hides mouse cursor even when moving mouse with RobotJS moveMouse. 

## Expected Behavior

I need the cursor to show when I use RobotJS moveMouse

## Current Behavior

Cursor hides

## Steps to Reproduce (for bugs)

1. Use any modern Ubuntu distro with unclutter installed (unclutter comes by default with Ubuntu)
2. Use moveMouse to move the cursor
3. Mouse cursor hides after a couple of seconds

**Comment by JonasMatos0** [comment]
Hi, @HadiModarres Isn't disabling/removing unclutter a viable solution?
Other Debian-based distros like PopOS don't come with unclutter by default.

**Comment by HadiModarres** [comment]
Hey @JonasMatos0 

Yea `pkill unclutter` fixes it, I just wanted to see if there's a workaround for this, as it's awkward to ask the user to kill unclutter or the app to automatically kill it

**Comment by JonasMatos0** [comment]
Yeah, It's something specific to that environment. 
Solution is to run a script to disable unclutter before and another to reenable it after, in the same program execution.
