### ISSUE TITLE
Add toggle function for keyboard. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#7]
Allow holding keys down, and releasing them.

**Comment by maxogden** [comment]
I have done some work on this here https://github.com/maxogden/robotjs/tree/keyupdown

**Comment by octalmage** [comment]
Looks great! Submit a pull request!

**Comment by maxogden** [comment]
@octalmage thanks, will do! gonna finish a prototype of a project i'm using it in first (https://github.com/maxogden/screenshare) and then I will -- It's bound to change a bit more still

**Comment by octalmage** [comment]
No thank you! And screenshare looks awesome, I'll have to check it out. 

Sounds good! Really appreciate the help man, I've been super busy recently. 

I'll try to start work on the screen/bitmap related functions this week, I've got it worked out on paper.

**Comment by octalmage** [comment]
@maxogden unrelated, but do you mind if I add ScreenCat to the Wiki: 

https://github.com/octalmage/robotjs/wiki/Projects-using-RobotJS

I'm trying to put together a list of projects using RobotJS, similar to [nw.js](https://github.com/nwjs/nw.js/wiki/List-of-apps-and-companies-using-nw.js) (same format).

**Comment by maxogden** [comment]
sure
