### ISSUE TITLE
io.js v3 support. 

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#71]
nan has been updated to v2 to support io.js v3, but it requires significant code changes.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798 (Node.js v4.0.0 support).

**Comment by octalmage** [comment]
Thanks! I'll check this out tonight. Should be pretty painless.

**Comment by jperasmus** [comment]
Hi, adding a friendly +1 for node v4 support.

**Comment by rogeru** [comment]
When do you plan to add node v4 support?

**Comment by octalmage** [comment]
See #87.

**Comment by sungwoncho** [comment]
+1 please

**Comment by octalmage** [comment]
The master branch has been updated to support Node.js v4 and io.js v3. 

Please test it and let me know how it works!

**Comment by abhishekgarg120** [comment]
Thank you @octalmage for this amazing project. cheers.

**Comment by octalmage** [comment]
RobotJS [v0.3.0](https://github.com/octalmage/robotjs/releases/tag/v0.3.0) has been released and published to npm!

This issue has been resolved.
