### ISSUE TITLE
Fails to install using NPM

### ISSUE THREAD

**Issue by MistakingManx** [octalmage/robotjs#712]
## Expected Behavior
RobotJS installs via `npm i robotjs`.

## Current Behavior
RobotJS fetches correctly and begins installation, but then proceeds to spam "gyp" errors and fails to install.

## Steps to Reproduce (for bugs)
1. `npm i robotjs`

## Context
I was trying to install the package so I could experiment with it.

## Your Environment
* RobotJS version: (latest)
* Node.js version: v17.0.1
* npm version: 8.3.0
* Operating System: Windows 10 Home

**Comment by MistakingManx** [comment]
`> npm i robotjs
npm ERR! code 1
npm ERR! path C:\Users\redacted\node_modules\robotjs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.0.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.6 found at "C:\Users\redacted\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python
.3.8_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\redacted\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstud
io.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\redacted\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\redacted\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib
\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Users\redacted\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\redacted\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Users\redacted\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\redacted\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\redacted\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\redacted\node_modules\robotjs
npm ERR! gyp ERR! node -v v17.0.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\redacted\AppData\Local\npm-cache\_logs\2022-04-10T18_01_16_563Z-debug-0.log`

**Comment by KavinHan** [comment]
@MistakingManx U can check the solution inside error message.
`
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
`

**Comment by MistakingManx** [comment]
I reported this because doing that didn't work?

**Comment by mankeheaven** [comment]
http://robotjs.io/docs/building
see this
It's written by c
![image](https://user-images.githubusercontent.com/17426397/203691767-33299fdf-d5b3-4bd7-a0ad-47951aa31bf0.png)
