### ISSUE TITLE
Key Toggles

### ISSUE THREAD

**Issue by dantheuber** [octalmage/robotjs#73]
It is extremely common for people to want to send commands such as "Ctrl+v" to toggle a paste command. I am in need of doing this now in my project, Quicklip, and i'd love to use robotjs for this, tho it doesnt appear that the current API allows for it. 

It would be extremely helpful to allow for an API like the following: 

```
robotjs.hold('ctrl').tap('v');
```

**Comment by octalmage** [comment]
Hey @dantheuber!

This is currently possible using keyTap or keyToggle. Something like this:

    robot.keyTap("v", "control");

I'll make sure the wiki gets updated!

**Comment by dantheuber** [comment]
Awesome, thanks octal! Glad the functionality was already there =)

Once i get it integrated, i'll add my application to your list of apps using robotjs!

**Comment by octalmage** [comment]
No problem! Quicklip looks cool, I'm excited to see RobotJS integrated.

**Comment by petre2dor** [comment]
There are plenty keyboard shortcuts with more that 2 keys. Is there a way to run commands like 
```
robot.keyTap("up", "alt", "control");
```
?

**Comment by jonaslund** [comment]
@petre2dor did you solve that issue?

**Comment by octalmage** [comment]
The modifier parameter supports arrays!
