### ISSUE TITLE
How to make screen of visible window on macos?

### ISSUE THREAD

**Issue by evoytenkoapps** [octalmage/robotjs#742]
How to make screen of visible window on macos?
i open ide and run code
but robotjs does not make an ide screen, it makes another screen, the one that is orange not grey with webstorm
How to fix it?
I think it has something to do with work macos

![wrong](https://github.com/octalmage/robotjs/assets/26488952/f027148c-8540-4009-aeeb-c9504971dd37)

<img width="1512" alt="expected" src="https://github.com/octalmage/robotjs/assets/26488952/e932b9fe-74fd-4e3a-b496-4f7ae690f8b0">
<img width="1512" alt="Снимок экрана 2023-05-29 в 09 58 27" src="https://github.com/octalmage/robotjs/assets/26488952/78bef5b0-45fc-4eca-ba1a-987b15c2af0c">

**Comment by s1hofmann** [comment]
@evoytenkoapps Same root cause as with https://github.com/nut-tree/nut.js/issues/469

You’ll have to give your process screen recording permissions

**Comment by evoytenkoapps** [comment]
yea. you a right.
i give permisions for screen recording to webstorm, and now its ok.
<img width="653" alt="Снимок экрана 2023-06-05 в 22 30 06" src="https://github.com/octalmage/robotjs/assets/26488952/f7552b3c-0458-415d-b9f7-86a542715dad">
