### ISSUE TITLE
Strip unneeded methods

### ISSUE THREAD

**Issue by jaruba** [octalmage/robotjs#76]
Would it be possible to strip unneeded methods? (ie: keep only ``.getMousePos()``)

I'd try to use this in [Powder Player](https://github.com/jaruba/PowderPlayer) (NW.js App) in an attempt to fix chromium's mouse hovering issues.

I would only need to know when the mouse is outside the window (something that chromium itself has serious problems with), all other methods seem very intrusive for unrelated apps (ie: not screen sharing, automation)

Thank you in advance. :)

**Comment by octalmage** [comment]
It's possible, just not really that easy or necessary.  Just don't use the other methods! :p

If you really want to do it you can remove the functions from src/robotjs.cc and remove the unrelated sources from bindings.gyp. Then run node-gyp rebuild. 

Good luck!

**Comment by jaruba** [comment]
> Just don't use the other methods! :p

I was sure you'd say that! :))

But my app is torrent related, there is enough paranoia from users when installing such apps. I can always play the "open source card" on these remarks, but it would also help to not have any intrusive methods in the code either.

Thanks for your help, it is greatly appreciated! :)

**Comment by octalmage** [comment]
Ha I understand! I just had to say it. 

Let me know if you need any help!
