### ISSUE TITLE
Media input/output ?

### ISSUE THREAD

**Issue by brunocascio** [octalmage/robotjs#82]
Hi guys!

I have seen this project seemed like a good idea, as is well decoupled, to integrate management features such as microphone and speakers, so that people with disabilities can use them.

**Comment by brunocascio** [comment]
An example of use, i say "Take an screenshot" and then take and screenshot.

**Comment by octalmage** [comment]
Hey Bruno! 

That falls outside the scope of this project, but check out  [node-speakable](https://github.com/sreuter/node-speakable). I've used this library and it works pretty good.

**Comment by aequasi** [comment]
Good call @octalmage

**Comment by brunocascio** [comment]
Okay, thanks! :)
