### ISSUE TITLE
'PrintScreen' keytap?

### ISSUE THREAD

**Issue by fritx** [octalmage/robotjs#83]
Excuse me. I just noticed the keycodes are very limited in robot.js
How could I make a keyTap with 'PrintScreen' (on Windows)?
Also, I just hacked into the code and changed something but it didn't work..

```c
K_F12 = VK_F12,
K_F13 = VK_F13,  // added
K_META = VK_LWIN,
```

My C/C++ is very poor though..

**Comment by Deltatiger** [comment]
The keycode is ```VK_SNAPSHOT```. I have not tested it yet but that should be the key. You could map it to a enum value like K_PRINTSCREEN then use it accordingly.

**Comment by fritx** [comment]
Wow. It works. Will this be included in this library in the future?

**Comment by Deltatiger** [comment]
@fritx  Robotjs is meant to be platform independent. I am not sure if this feature is present in all platforms. That parts needs to be cleared up (whether this kind of platform specific things can be added or not) @octalmage..

**Comment by octalmage** [comment]
I'm conflicted about platform specific features (see #34), but for something like this I'd say it's ok. This is something people are going to want to do, and if we don't implement it in RobotJS there won't be a good solution. My main goal with RobotJS is to fill in the gaps.

**Comment by fritx** [comment]
Thanks! Expecting something happens. Or any help that I can do?

**Comment by octalmage** [comment]
I'll spin up my VM and get it implemented now!

**Comment by fritx** [comment]
Cool! Awesome thanks :+1:
