### ISSUE TITLE
Listening for mouse and keypress events

### ISSUE THREAD

**Issue by deamme** [octalmage/robotjs#84]
Can I listen for mouse and keypress events and do something accordingly?

**Comment by octalmage** [comment]
I don't think I'll include this in RobotJS, but I'm considering making a separate module. See #55.

Personally I use nw.js or Electron for this. You can have global hotkeys with both projects.

**Comment by deamme** [comment]
@octalmage I see - Can NW.js and Electron detect mouse events?

**Comment by octalmage** [comment]
No, only key-presses (hotkeys).

**Comment by deamme** [comment]
Okay, thanks!

**Comment by octalmage** [comment]
No problem! I forgot to mention that RobotJS can get the mouse position.
