### ISSUE TITLE
[Question] Is there a way to press media keys like play/pause?

### ISSUE THREAD

**Issue by petre2dor** [octalmage/robotjs#91]
Most keyboards have them and, at least, Linux and Windows supports them by default.

**Comment by octalmage** [comment]
This isn't currently supported, but it's possible! I'll work on getting the keycodes added.

**Comment by vshymanskyy** [comment]
Just wanted to post same idea. Thanks! ;)

**Comment by octalmage** [comment]
Fix published to npm in RobotJS v0.3.7. Thanks again @vshymanskyy!
