### ISSUE TITLE
[windows] nan.h compile errors

### ISSUE THREAD

**Issue by lassdas** [octalmage/robotjs#94]
I tried to install robotjs via
npm install robotjs
but i got errors, is taht my fault?

https://gist.github.com/lassdas/af5dcc7cb895f106fd57

My setup:
Windows 7 Home Premium
Visual Studio Community 2013
Python 2.7.3

21ce43c06637e3b98e6f35fbcffc5965e3c2f1bc

I hope you can help me ;)

**Comment by octalmage** [comment]
Hi @lassdas, 

Node.js v4 isn't supported yet. See #87 

I hope to get everything updated this week.
