### ISSUE TITLE
typeString issue with Parallel Desktop running Windows 7 guest

### ISSUE THREAD

**Issue by sungwoncho** [octalmage/robotjs#96]
All characters in the argument of `typeString` is typed as 'a' on Windows 7 guest on Parallel Desktop. RobotJS is running on OSX.

```javascript
var robot = require('robotjs')
robot.typeString('foo bar baz');
```

The above code results in `aaaaaaaaaaa` on Windows 7 guest.

**Comment by octalmage** [comment]
Sorry I missed this! I'll look into it tomorrow.

**Comment by octalmage** [comment]
I believe this has been fixed! let me know if it's still an issue.
